#!/usr/bin/env python3
"""Author source-ordered learning sets for Chapters 30-31 (Frontal Lobe, Praxicons).

Source: the scanned sheets read visually at 2x PyMuPDF renders --
  uploads/02.pdf PDF87-93 = Book p555-561 and uploads/03.pdf PDF1 = Book p562.
Printed page numbers were verified on the renders (p555, p556, p557, p558, p559
visible; 02.pdf PDF92 = p560 bracketed by PDF91 = 559 and PDF93 = 561; 03.pdf
PDF1 corner reads "62" and PDF2 = p563 opens "TEMPORAL AND OCCIPITAL LOBE").

Each row is a four-option book-study question in the same JSON contract used for
Chapters 9-29 and 33-38: reasoning-first formats only (recall, scenario, numeric,
oddoneout, management), strictly printed-page order, and every explanation ending
with its exact (Book pX) citation. No fill-up or matching worksheets are authored.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data"


def make_chapter(number, title, page_range, unit_specs):
    questions = []
    units = []
    for unit_no, (section, unit_title, guide, rows) in enumerate(unit_specs, 1):
        if "\n" not in guide:
            sentences = []
            buf = ""
            for word in guide.split(" "):
                buf = (buf + " " + word).strip()
                if word.endswith((".", "!", "?")):
                    sentences.append(buf)
                    buf = ""
            if buf:
                sentences.append(buf)
            if len(sentences) >= 2:
                mid = (len(sentences) + 1) // 2
                guide = "\n".join([" ".join(sentences[:mid]), " ".join(sentences[mid:])])
            else:
                words = guide.split()
                third = max(1, len(words) // 2)
                guide = " ".join(words[:third]) + "\n" + " ".join(words[third:])
        ids = []
        for page, fmt, stem, correct, distractors, explanation in rows:
            qid = f"MED-C{number}-{len(questions)+1:02d}"
            choices = [correct, *distractors]
            shift = (len(questions) * 3 + number) % 4
            choices = choices[shift:] + choices[:shift]
            questions.append({
                "id": qid, "sec": section, "page": page, "fmt": fmt,
                "q": stem, "opts": choices, "ans": choices.index(correct),
                "exp": explanation + f" (Book p{page})",
            })
            ids.append(qid)
        units.append({
            "id": f"MED-U{number}-{unit_no}", "ch": number, "n": unit_no,
            "title": f"{unit_no}. {unit_title}", "sec": section,
            "guide": guide, "qs": ids,
        })
    return {"chapter": number, "title": title, "pageRange": page_range,
            "questions": questions, "units": units}


def q(page, fmt, stem, correct, *distractors, exp):
    assert len(distractors) == 3, (stem, distractors)
    return (page, fmt, stem, correct, list(distractors), exp)


def write(chapter):
    path = OUT / f"ch{chapter['chapter']:02d}.json"
    path.write_text(json.dumps(chapter, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{path.name}: {len(chapter['questions'])} questions / {len(chapter['units'])} units")


# ---------------------------------------------------------------------------
# CHAPTER 30 - FRONTAL LOBE (Book p555-559)
# ---------------------------------------------------------------------------
ch30 = make_chapter(30, "Frontal Lobe", "555-559", [
("Frontal-lobe entry: MMSE screening and the superolateral surface map",
 "Frontal-lobe entry: MMSE screening and the superolateral surface map",
 "The chapter opens with the mini-mental state examination (MMSE) as a higher-mental-function screen and the ORAR LC component list. The anatomy section begins with the superolateral surface figure, its lobe colour coding, the frontal gyral labels and the four functional cortices drawn beneath it.", [
 q(555,"recall","On the opening page, what is the printed purpose of the mini-mental state examination (MMSE)?","It helps to assess higher mental functions / cognitive status","It grades muscle strength and tone in the limbs","It localises a visual field defect to the occipital lobe","It screens cardiac autonomic neuropathy",exp="The page introduces the mini-mental State Examination (mmse) with the line 'Helps to assess Higher mental functions/cognitive status.'"),
 q(555,"recall","Under which printed heading are the six MMSE components listed?","Based on: ORAR LC","Based on: JIPFA","Based on: CLASP","Based on: FAST",exp="'Based on :' is followed by the red mnemonic ORAR LC and then the six bulleted components."),
 q(555,"oddoneout","Which element is NOT one of the six MMSE components bulleted on this page?","Naming","Orientation","Attention","Copying",exp="The printed bullets read Orientation, Registration, Attention, Recall, Language, Copying; naming is not listed among them."),
 q(555,"scenario","A patient is asked to write a sentence of his own and then to copy the printed figure. Which two MMSE components do these two tasks test?","Language and Copying","Registration and Attention","Orientation and Recall","Registration and Copying",exp="Written output is the Language component and the figure-copying task is the Copying component of the printed ORAR LC list."),
 q(555,"recall","Under what printed sub-heading is the first brain diagram presented?","Superolateral surface","Medial surface","Inferior surface","Basal surface",exp="'Anatomy of Frontal Lobe' is immediately followed by the line 'Superolateral surface :' above the coloured lateral-view diagram."),
 q(555,"recall","In the superolateral diagram, which lobe is coloured yellow and lies directly behind the sulcus marked central sulcus?","Parietal lobe","Frontal lobe (pink)","Temporal lobe (green)","Occipital lobe (uncoloured)",exp="The figure shades the frontal lobe pink, the parietal lobe yellow behind the central sulcus, the temporal lobe green and leaves the occipital lobe unshaded."),
 q(555,"recall","In the same figure, which two parts are labelled within the inferior frontal gyrus?","Pars opercularis and pars triangularis","Pars cuneata and pars limitans","Pars orbitalis and pars recta","Pars marginalis and pars angularis",exp="The inferior frontal gyrus label carries the printed sub-labels 'Pars opercularis' and 'Pars triangularis'."),
 q(555,"recall","In the lower functional map on the same page, which cortex is marked over the superior temporal region?","Auditory cortex","Visual cortex","Somatosensory cortex","Premotor cortex",exp="The functional map points the Auditory cortex label into the temporal lobe region, while the Visual cortex label is placed on the occipital pole."),
 q(555,"oddoneout","The second functional map on the page labels four cortices directly on the hemisphere. Which cortex is NOT one of them?","Olfactory cortex","Motor cortex","Somatosensory cortex","Visual cortex",exp="The functional map points out Motor cortex, Somatosensory cortex, Auditory cortex and Visual cortex; no olfactory cortex is labelled."),
]),
("Areas on the frontal lobe: lateral map, medial surface and orbital surface",
 "Areas on the frontal lobe: lateral map, medial surface and orbital surface",
 "The functional map of frontal areas pairs area 4 with the precentral gyrus, areas 6 and 8 with premotor, supplementary-motor and frontal eye functions, areas 9-12 with prefrontal cortex and areas 44-45 with Broca's motor speech area. The medial and inferior surface figures add the cingulate, paracentral, rectus and orbital gyral anatomy.", [
 q(556,"recall","In the 'Areas on frontal lobe' list, which area is printed as the primary motor area on the precentral gyrus?","Area 4","Area 6","Area 8","Area 44",exp="The right-hand column of the list prints 'Area : 4 Primary motor area (Pre central gyrus)'."),
 q(556,"oddoneout","Which area-function pairing is NOT printed in this figure's list?","Area 6 - frontal eye field","Area 6 - premotor area","Area 8 - supplementary motor area (medially)","Area 8 - frontal eye field",exp="The list assigns area 6 to premotor area only, while both the supplementary motor area (medially) and the frontal eye field are printed as area 8."),
 q(556,"recall","Which bracket annotation on the left of the list groups the premotor and supplementary-motor entries?","Anterior to 1 degree motor area","Posterior to primary sensory cortex","Superior to the calcarine sulcus","Lateral to the sylvian fissure",exp="A brace collects the area 6 and area 8 entries under the note 'Anterior to 1 degree motor area'."),
 q(556,"numeric","Which Brodmann areas are printed for the prefrontal area, and with which positional note?","Areas 9, 10, 11, 12 - anterior to area 6 and 8","Areas 1, 2, 3 - posterior to the central sulcus","Areas 17, 18, 19 - below the calcarine fissure","Areas 41, 42 - above the superior temporal gyrus",exp="The prefrontal entry reads 'Area : 9,10,11,12' with the line '(Anterior to area 6 & 8)'."),
 q(556,"scenario","A tumour destroys the posterior part of the left inferior frontal gyrus. Which printed area label and eponym fit the destroyed cortex?","Areas 44 and 45, the motor speech area of Broca","Areas 41 and 42 in the superior temporal gyrus","Areas 9 to 12 in the frontal pole","Areas 17 and 18 in the occipital cortex",exp="The functional map prints area 44, 45 as the motor speech area of Broca in the inferior frontal gyrus."),
 q(556,"recall","Which sulcus is labelled on the right of the lateral diagram, separating the frontal operculum from the temporal lobe?","Lateral sulcus / Sylvian fissure","Central sulcus","Intraparietal sulcus","Marginal ramus",exp="The right-side label of the functional figure reads 'Lateral sulcus/ Sylvian fissure', and the caption below states 'Functional frontal lobe anatomy'."),
 q(556,"recall","On the printed medial surface, which pink-labelled gyrus curves immediately above the corpus callosum and below the cingulate sulcus?","Cingulate gyrus","Cuneus","Lingual gyrus","Fusiform gyrus",exp="The medial-surface drawing labels CINGULATE GYRUS between the cingulate sulcus above and the corpus callosum below."),
 q(556,"recall","On the printed medial surface, which structure is boxed in pink at the superior margin, immediately behind the label printed as marginal ramus?","Paracentral lobule","Uncus","Gyrus rectus","Isthmus of the cingulate gyrus",exp="The medial-surface drawing boxes PARACENTRAL LOBULE in pink at the superior medial margin, with the marginal ramus labelled just in front of it."),
 q(556,"recall","On the same medial figure, which two lobules are printed behind the paracentral lobule, one above and one below the parieto-occipital sulcus?","Precuneus above and cuneus below","Cuneus above and precuneus below","Lingual gyrus above and cuneus below","Parahippocampal gyrus above and gyrus rectus below",exp="The medial-surface drawing labels PRECUNEUS above and CUNEUS below the parieto-occipital sulcus, behind the paracentral lobule."),
 q(556,"recall","Which visual and medial-temporal landmarks does the printed medial figure pair up?","Calcarine fissure above the lingual gyrus, with the uncus at the front of the hippocampal gyrus","Calcarine fissure below the cuneus, with the uncus inside the paracentral lobule","Lingual gyrus above the calcarine fissure, with the gyrus rectus in the temporal lobe","Fusiform gyrus replacing the hippocampal gyrus, with no uncus drawn",exp="The medial figure draws the Calcarine fissure over the LINGUAL GYRUS and shows the hippocampal gyrus ending anteriorly at the labelled uncus, with the fusiform gyrus below it."),
 q(556,"recall","On the inferior (orbital) surface, which sulcus separates the gyrus rectus from the medial orbital gyrus?","Olfactory sulcus","Calcarine sulcus","Collateral sulcus","Central sulcus",exp="The orbital figure prints GYRUS RECTUS, then 'Olfactory sulcus' with an arrow, then MED. ORB. GYRUS."),
 q(556,"recall","Which gyri are printed around the H-shaped orbital sulcus on the inferior surface?","Medial and lateral orbital gyri, further split into anterior and posterior orbital gyri","Superior and middle frontal gyri, split by the frontal sulci","Orbital and rectus gyri only, with no anterior or posterior division","Parahippocampal and cingulate gyri",exp="The inferior-surface figure prints MED. ORB. GYRUS and LAT. ORB. GYRUS beside the orbital sulcus, with ANTr. ORBITAL GYRUS above and POST. ORB. GYRUS below."),
 q(556,"recall","Which configuration is annotated for the orbital sulcus on the inferior surface figure?","H shaped","Y shaped","Cruciate","Circular",exp="The arrow to the orbital sulcus carries the printed note 'Orbital sulcus (H shaped)', with ANTr., POST., MED. and LAT. orbital gyri labelled around it."),
]),
("Area 4, premotor/SMA roles, the movement ladder and the motor homunculus",
 "Area 4, premotor/SMA roles, the movement ladder and the motor homunculus",
 "Functions of the frontal lobe begin with area 4, its 30% share of motor fibres and the Betz cells. Premotor and supplementary-motor cortex supply the preparation of movement and, when injured bilaterally, tone changes with primitive reflexes. The printed planning-to-finesse ladder and the motor homunculus close the page.", [
 q(557,"numeric","What proportion of motor fibres is printed as originating from area 4 / primary motor cortex?","Only 30%","About 60%","About 80%","Essentially all of them",exp="The area 4 block opens with 'Only 30% motor fibres originate from here.'"),
 q(557,"recall","Which two properties are printed for the Betz cells of area 4?","Specialized cells with the lowest threshold to initiate motor activity","Largest cortical interneurons inhibiting antagonists","Cells that only fire during sleep atonia","Cells whose loss produces fluent aphasia",exp="'Betz cells present :' is followed by 'Specialized cells.' and 'Lowest threshold to initiate motor activity.'"),
 q(557,"recall","What action is credited directly to area 4 in the printed list?","It initiates fine skilled voluntary movement","It plans the movement with the basal ganglia","It provides the finesse of the ongoing movement","It generates praxicons for sensory guidance",exp="The third bullet of the area 4 block reads Initiate fine skilled voluntary movement, while planning and finesse are given to the basal ganglia and cerebellum."),
 q(557,"numeric","How much of the motor-fibre output is attributed to the premotor area and supplementary motor area together on this page?","30% of motor fibres originate here","40% of motor fibres originate here","60% of motor fibres originate here","10% of motor fibres originate here",exp="The PMA and SMA block prints '30% motor fibers originate here.'"),
 q(557,"oddoneout","Which role is NOT one of the three printed ways premotor/SMA prepares a fine skilled voluntary movement?","Saccade suppression","Tone of posture","Proximal muscle alignment","Antagonist muscle inhibition",exp="The preparation list is exactly tone of posture, proximal muscle alignment and antagonist muscle inhibition."),
 q(557,"scenario","Bilateral frontal injury removes premotor and supplementary-motor inhibition. Which printed consequences follow?","Spasticity (tone issue) and primitive reflexes","Flaccidity with areflexia","Chorea with athetosis","Isolated rest tremor",exp="The block lists 'B/I lesion spasticity (Tone issue).' with the sub-bullet 'Primitive reflexes.'"),
 q(557,"scenario","A resident is told that in Parkinson disease the earliest stage of a planned movement is disturbed. According to the printed ladder, which stage and structure are involved?","Planning and coordination - basal ganglia","Preparation and setting up - PMA/SMA","Initiation - primary motor area","Finesse - cerebellum",exp="The ladder begins with Planning and coordination credited to the basal ganglia."),
 q(557,"recall","Which structures are printed as responsible for the 'Prepare (setting up)' step of the ladder?","PMA/SMA","Basal ganglia and thalamus","Primary motor area alone","Cerebellum and inferior olive",exp="The second step of the ladder assigns Prepare (setting up) to PMA/SMA."),
 q(557,"recall","Which step of the ladder is assigned to the cerebellum in the printed figure?","Finesse","Planning & coordination","Initiation","Antagonist muscle inhibition",exp="The ladder ends 'Finesse : by Cerebellum', while Initiation is given to the 1 degree motor area."),
 q(557,"scenario","A patient has an infarct confined to the superolateral convexity hand and face area. Which printed vascular territory is involved?","Middle cerebral artery territory on the superolateral surface","Anterior cerebral artery territory on the medial surface","Posterior cerebral artery territory on the inferior surface","Basilar perforators to the brainstem",exp="The homunculus note states 'Face & upper limb : Superolateral surface (supplied by middle Cerebral Artery/MCA).'"),
 q(557,"recall","On which surface and arterial supply does the printed homunculus place the lower limb?","Medial surface, supplied by the anterior cerebral artery (ACA)","Superolateral surface, supplied by the middle cerebral artery","Inferior surface, supplied by the posterior cerebral artery","Insular surface, supplied by the lenticulostriate arteries",exp="The left-hand note reads 'Lower limb : medial surface (Supplied by anterior cerebral artery (ACA)).'"),
 q(557,"recall","Which cluster of labels is printed with arrows at the mouth region of the motor homunculus figure?","Mastication, salivation and vocalization","Coughing, sneezing and hiccup","Blinking, staring and pupil constriction","Swallowing only, with no other label",exp="Along the face region the figure prints Jaw, Tongue, Swallowing and then the arrowed labels MASTICATION, SALIVATION and VOCALIZATION."),
]),
("Vascular and motor-cortex lesions, the frontal eye field and Broca's area",
 "Vascular and motor-cortex lesions, the frontal eye field and Broca's area",
 "The homunculus anatomy converts into vessel syndromes: MCA lesions spare the leg and ACA lesions do the reverse with incontinence. Motor-cortex lesion effects and the definition of the upper motor neuron precede the frontal eye field pathway diagram. The page closes with gaze rules and the Broca fluency note.", [
 q(558,"recall","Which deficit pair is printed for an MCA lesion in this section?","Face and upper limb weakness","Lower limb weakness with incontinence","Bilateral leg paraparesis only","Isolated axial truncal ataxia",exp="The first line under the homunculus continuation reads 'MCA lesion : Face & U/L weakness.'"),
 q(558,"scenario","An elderly patient has new right-leg weakness and cannot reach the toilet in time; a medial frontal infarct is found. Which printed syndrome matches this picture?","ACA lesion: lower limb weakness plus urinary incontinence from the paracentral lobule","MCA lesion: face and upper limb weakness with the leg spared","PCA lesion: contralateral hemianopia with macular sparing","Lenticulostriate lesion: pure motor hemiparesis without cortical signs",exp="The printed ACA line pairs lower limb weakness with urinary incontinence, the bladder representation being in the paracentral lobule on the medial surface."),
 q(558,"recall","Which cortical structure is named in parentheses as the reason ACA lesions cause urinary incontinence?","Paracentral lobule on the medial surface","Cingulate gyrus on the medial surface","Inferior temporal gyrus on the basal surface","Precentral sulcus on the lateral surface",exp="The ACA line attributes incontinence to the 'paracentral lobule on medial surface'."),
 q(558,"recall","In 'Lesion of motor cortex', which class of movement is bracketed as the one lost in contralateral weakness?","Fine skilled voluntary movements","Gross proximal movements","Involuntary reflex movements","Oculocephalic movements",exp="The list opens 'C/l weakness (Fine skilled voluntary movements).'"),
 q(558,"recall","What tone change is printed for a motor-cortex (UMN) lesion?","Spasticity (hypertonia)","Flaccidity (hypotonia)","Waxing and waning rigidity","No change in tone",exp="The second bullet reads 'uMN lesion : Spasticity (Hypertonia).'"),
 q(558,"oddoneout","Which statement about limb involvement in a motor-cortex lesion is NOT consistent with the printed text?","The leg is always the most severely affected limb","Face and upper limb are involved","Lower limb predominant weakness may occur depending on the vessel affected","Distribution follows the motor homunculus",exp="The page prints 'Fare & upper Limb (Lower limb predominant weakness depending on vessel/side affected) (motor Homunculus)', so dominance is vessel- and side-dependent, never always the leg."),
 q(558,"scenario","A meningioma over the edge of the left precentral gyrus causes rhythmic jerking that starts in the right hand and climbs up the arm. Which printed term is used for this?","Jacksonian march","Absence seizure status","Akinetic mutism","Primitive reflex release",exp="The final lesion bullet reads 'Initiate lesion : C/l motor simple partial seizure : Jacksonian march.' (printed as an irritative-type lesion)."),
 q(558,"recall","How does the source define the upper motor neuron on this page?","From cortex till the anterior horn cell (in grey matter)","From the basal ganglia to the thalamus","From the internal capsule to the muscle spindle only","From the pontine reticular formation to the spinal cord",exp="The last bullet of the lesion block reads 'upper motor Neuron (uMN) : From cortex till anterior horn cell (In grey matter).'"),
 q(558,"recall","In the printed frontal eye field legend, what does MLF stand for?","medial Longitudinal Fasciculus","Middle Lateral Fissure","Motor Lobe Field","Medial Limbic Fiber",exp="The legend lists PPRF - Para Pontine Reticular Formation, LR - Lateral Rectus, MR - medial Rectus and MLF - medial Longitudinal Fasciculus."),
 q(558,"recall","In the same printed legend, PPRF is expanded as which structure?","Para pontine reticular formation","Posterior precentral reticular fasciculus","Primary pupillary reflex fibre","Medial pontine reticular formation",exp="The legend beside the flowchart reads PPRF - Para Pontine Reticular Formation, alongside LR - Lateral Rectus and MR - medial Rectus."),
 q(558,"scenario","The printed flowchart for the left frontal lobe is intact. Stimulation of the left frontal eye field produces which combination?","Activation of the right lateral rectus and the left medial rectus, so the eyes look right","Activation of the left lateral rectus only, so the eyes look left","Bilateral medial rectus contraction, so the eyes converge","No movement, because the pathway crosses twice",exp="The bullet reads '(L) FEF -> Activates (R) LR & (L) MR -> look to (R).'"),
 q(558,"scenario","A destructive stroke knocks out the left frontal eye field. Where do the patient's eyes rest, per the printed rule?","They look left, towards the side of the lesion","They look right, away from the lesion","They deviate downward","They cannot fix in either horizontal direction",exp="'(L) FEF lesion -> Cannot look (R) -> patient looks (L) (side of lesion)', concluded as 'Frontal lobe lesion -> Patient look towards side of lesion.'"),
 q(558,"management","At the bedside you must decide whether a horizontal gaze palsy is frontal or pontine. Using the printed rules, which interpretation is correct?","Eyes looking towards the lesion means a frontal lesion; eyes looking away means a PPRF brainstem lesion","Eyes looking towards the lesion means a PPRF lesion; eyes looking away means a frontal lesion","Either pattern localises to the frontal eye field alone","Either pattern localises to the medial longitudinal fasciculus alone",exp="The printed rules contrast a frontal lobe lesion, where the patient looks towards the side of the lesion, with a brainstem PPRF lesion, where the eyes look away from the side of the lesion."),
 q(558,"recall","In the printed flowchart, the nucleus labelled VI sends its red output directly to which labelled muscle?","Right lateral rectus","Left medial rectus","Superior oblique","Inferior rectus",exp="The flowchart shows the VI box with a red arrow to 'Right lateral rectus', and PPRF driving VI."),
 q(558,"recall","The red tract that runs from the VI nucleus across to the III nucleus is highlighted with which label in the printed diagram?","MLF","PPRF","DLPN","NPH VN",exp="The pink highlighted label pointing at that crossing red tract is 'MLF'; the III box in turn points to 'Medial rectus'."),
 q(558,"recall","What language deficit is printed for Broca's area (areas 44, 45)?","Fluency affected - non fluent aphasia","Comprehension affected with fluent output","Impaired naming with preserved repetition","Impaired reading with preserved writing",exp="The Broca block reads 'Fluency affected (Non fluent aphasia).'"),
 q(558,"scenario","A patient speaks fluently with empty content and cannot follow commands. Which printed rule places this lesion?","Posterior to the central sulcus, where comprehension is affected","Anterior to the central sulcus, where fluency is affected","In area 4, where initiation of movement is affected","In the supplementary motor area, where tone is affected",exp="The page assigns fluency loss to lesions anterior to the central sulcus and the closing Note assigns comprehension loss to lesions posterior to it."),
]),
("Prefrontal cortex map, JIPFA behaviour and bilateral frontal pathology",
 "Prefrontal cortex map, JIPFA behaviour and bilateral frontal pathology",
 "The prefrontal table matches dorsolateral, medial, orbital and polar cortex to executive, emotional, behavioural and theory-of-mind functions. Apathy to akinetic mutism grades the loss of energisation, and JIPFA lists the behavioural components. Bilateral frontal pathology adds incontinence, primitive reflexes and gait apraxia.", [
 q(559,"recall","Which Brodmann areas head the prefrontal cortex heading on this page?","Areas 9, 10, 11 and 12","Areas 4 and 6","Areas 44 and 45","Areas 17 and 18",exp="The page title reads 'pre Frontal Cortex (PFC) / Area. 9, 10, 11, 12 :'."),
 q(559,"recall","In the printed Parts-Function table, which part is paired with executive function?","Dorsolateral PFC","Medial PFC (cingulate gyrus)","Orbital PFC","Frontal pole",exp="Row one of the table pairs Dorsolateral PFC with 'Executive function'."),
 q(559,"recall","Which prefrontal part is annotated as the cingulate gyrus, and with which function?","Medial PFC - emotion and motivation","Orbital PFC - emotion and motivation","Frontal pole - emotion and motivation","Dorsolateral PFC - behavioural response",exp="The table prints 'medial PFC (cingulate gyrus)' against 'Emotion & motivation'."),
 q(559,"oddoneout","Which part-function pairing is NOT the one printed in this table?","Dorsolateral PFC - theory of mind","Orbital PFC - behavioural response","Frontal pole - theory of mind","Medial PFC - emotion and motivation",exp="The table assigns executive function to the dorsolateral PFC, while orbital, medial and polar rows are exactly behavioural response, emotion & motivation and theory of mind."),
 q(559,"oddoneout","Executive function is printed as a time/frame-dependent goal-directed activity with three components. Which is the odd one out?","Antagonist muscle inhibition","Cognitive inhibition","Response inhibition","Set shifting (flexibility)",exp="The three printed components are cognitive inhibition, response inhibition and set shifting (flexibility); antagonist muscle inhibition belongs to the premotor list on p557."),
 q(559,"recall","How does the printed text annotate 'set shifting' inside the executive-function list?","As flexibility","As inhibition of reflexes","As a speed measure","As a verbal fluency task",exp="The third bullet reads 'Set shifting (flexibility).'"),
 q(559,"scenario","A patient with a medial frontal lesion sits passively, initiating nothing but still arouses to strong stimuli. Which printed severity stage is this, using the ladder on the page?","Akinetic mutism, the severe end after apathy and abulia","Abulia, the mild end of the ladder","Apathy, the severe end of the ladder","Response inhibition, the executive end",exp="The energisation block prints 'when lost : Apathy (mild) -> Abulia -> Akinetic mutism (severe).'"),
 q(559,"recall","On what basis is the behavioural response of the orbital PFC said to operate?","Reward and punishment","Circadian arousal only","Proprioceptive feedback","Conditioned reflex arcs",exp="The behavioural response block reads 'Based on reward/punishment.'"),
 q(559,"recall","Which mnemonic is printed for the components of behavioural response?","JIPFA","ORAR LC","FAST","CLASP",exp="The list prints 'Includes : JIPFA.' followed by the five expansions."),
 q(559,"oddoneout","Which item does NOT appear in the printed expansion of JIPFA?","Attention","Judgement","Insight","Abstract thinking",exp="JIPFA expands to Judgement, Insight, Problem solving/personality, Fluency and Abstract thinking."),
 q(559,"recall","How is metacognition defined in the printed theory-of-mind block?","Understanding oneself","Understanding others' motor plans","Awareness of the contralateral visual field","Graded attention span",exp="The theory-of-mind bullets read 'Sympathy, empathy.' and 'metacognition : understanding oneself.'"),
 q(559,"scenario","A patient cannot infer what a colleague believes about a meeting, though memory and language are intact. Which printed prefrontal part and function are implicated?","Frontal pole - theory of mind","Dorsolateral PFC - executive function","Orbital PFC - reward and punishment behaviour","Area 4 - initiation of movement",exp="The table pairs the Frontal pole with 'Theory of mind', the block that lists sympathy, empathy and metacognition."),
 q(559,"recall","Which mechanism is printed for primitive reflexes in bilateral frontal lobe pathology?","Due to pre motor cortex involvement","Due to basal ganglia dopamine loss","Due to posterior fossa compression","Due to peripheral neuropathy",exp="The B/L FRONTAL LOBE PATHOLOGY list prints 'Primitive reflexes (d/t pre motor cortex involvement).'"),
 q(559,"recall","How does the page characterise akinetic mutism within the bilateral frontal list?","As the worst form of apathy","As the mildest form of abulia","As a seizure phenomenon","As a cerebellar sign",exp="The list states 'Akinetic mutism : worst form of apathy.'"),
 q(559,"scenario","A patient with ventriculomegaly cannot start walking and describes the feet as glued to the floor. Which printed term and explanation apply?","Gait apraxia in normal pressure hydrocephalus - ignition failure, foot feels stuck to floor","Spastic gait due to corticospinal tract lesion","Ataxic gait due to cerebellar degeneration","Sensory gait due to posterior column loss",exp="The final bullet reads 'Gait apraxia : Seen in Normal Pressure Hydrocephalus (Ignition failure : Foot feels like stuck to floor).'"),
 q(559,"management","A neurologist plans the bedside screen for a patient with suspected frontal involvement and wants the six printed MMSE domains plus the frontal apathy ladder in one note. Which combination is correct?","Orientation, Registration, Attention, Recall, Language, Copying; apathy then abulia then akinetic mutism","Naming, Repetition, Comprehension, Reading, Writing, Calculation; apathy then stupor then coma","Fixation, Pursuit, Saccades, Convergence, Nystagmus, Dysmetria; abulia then apathy then mutism","Tone, Power, Reflexes, Coordination, Gait, Sensation; akinetic mutism then abulia then apathy",exp="The MMSE components are printed on p555 as Orientation, Registration, Attention, Recall, Language and Copying, and p559 grades lost energisation as Apathy (mild) -> Abulia -> Akinetic mutism (severe)."),
]),
])

# ---------------------------------------------------------------------------
# CHAPTER 31 - PRAXICONS (Book p560-562)
# ---------------------------------------------------------------------------
ch31 = make_chapter(31, "Praxicons", "560-562", [
("Parietal lobe map, the 40/30/30 motor-fibre origins and the postcentral gyrus",
 "Parietal lobe map, the 40/30/30 motor-fibre origins and the postcentral gyrus",
 "The chapter opens behind the central sulcus with the parietal map: primary sensory cortex areas 3, 1 and 2, the intraparietal sulcus dividing superior from inferior parietal lobule, and the praxicon, gnosic and Gerstmann annotations. The note on motor-fibre origins and the postcentral gyrus syndrome complete the page.", [
 q(560,"recall","The Praxicons chapter begins by locating the parietal lobe in what relation to the central sulcus?","Posterior to the central sulcus","Anterior to the central sulcus","Medial to the parieto-occipital sulcus","Inferior to the sylvian fissure only",exp="Under the 'Parietal lobe' heading the printed line reads 'Posterior to central sulcus.'"),
 q(560,"numeric","Which Brodmann areas are printed inside the orange box over the postcentral gyrus?","Areas 3, 1, 2","Areas 4 and 6","Areas 5 and 7","Areas 44 and 45",exp="The highlighted label reads 'Primary sensory cortex (area 3, 1, 2)'."),
 q(560,"recall","Which parietal subdivision carries the printed annotation '(Praxicons)'?","Superior parietal lobule","Inferior parietal lobule","Supramarginal gyrus","Angular gyrus",exp="The grey annotation on the figure states 'Superior parietal lobule (Praxicons)'."),
 q(560,"oddoneout","Which annotation pairing is NOT printed on this parietal figure?","Inferior parietal lobule (Gerstmann syndrome)","Posterior parietal lobule in the yellow highlight","Supramarginal gyrus (Gnosis)","Angular gyrus (Gerstmann syndrome)",exp="The green label for the inferior parietal lobule carries no syndrome name, while the posterior parietal lobule is highlighted, the supramarginal gyrus is annotated Gnosis and the angular gyrus carries the Gerstmann syndrome note."),
 q(560,"recall","Which sulcus is drawn and labelled between the superior and inferior parietal lobules?","Intraparietal sulcus","Post central sulcus","Superior temporal sulcus","Parieto-occipital sulcus",exp="The figure labels 'intraparietal sulcus' running between the SUP. PARIETAL LOBULE and INF. PARIETAL LOBULE."),
 q(560,"recall","Below the parietal lobules, which two sulci are labelled on the same printed figure?","Sylvian fissure and superior temporal sulcus","Central sulcus and post central sulcus","Calcarine fissure and parieto-occipital sulcus","Collateral sulcus and olfactory sulcus",exp="The parietal figure labels the Sylvian fissure and the superior temporal sulcus beneath the inferior parietal lobule, with the parieto-occipital association area highlighted behind them."),
 q(560,"numeric","In the printed 'Origin of motor fibres' note, what share is attributed to the primary sensory cortex?","40%","30%","20%","50%",exp="The three branches read 1 degree sensory cortex (40%), 1 degree motor cortex (30%) and Premotor and supplementary motor cortex (30%)."),
 q(560,"recall","Which two origins share the remaining 60% equally in that note?","Primary motor cortex and premotor/supplementary motor cortex","Primary sensory cortex and primary motor cortex","Premotor cortex and supplementary motor area","Parieto-occipital association area and angular gyrus",exp="The note gives 30% to the 1 degree motor cortex and 30% to the premotor and supplementary motor cortex."),
 q(560,"recall","Which artery does the printed postcentral gyrus line name for the contralateral upper motor neuron weakness?","Middle cerebral artery","Anterior cerebral artery","Posterior cerebral artery","Anterior spinal artery",exp="The postcentral gyrus list reads C/L upper motor Neuron (UMN) weakness : middle cerebral artery."),
 q(560,"recall","In the postcentral gyrus syndrome, how are tone and the frontal eye field printed?","Tone less affected; frontal eye field spared","Tone increased markedly; frontal eye field palsied","Both tone and the frontal eye field are lost","Both tone and the frontal eye field are exaggerated",exp="The postcentral gyrus list prints tone as less affected and the frontal eye field as spared."),
 q(560,"recall","What explanation does the closing note give for tone and FEF being handled differently in parietal lesions?","Their association with the pre-motor and supplementary motor area","Their representation in the thalamus","Their dual blood supply from the PCA","Their brainstem autonomy",exp="The note states 'Association with Pre-motor and Supplementary motor area : Tone, FEF.'"),
 q(560,"oddoneout","Cortical sensations are printed as impaired after a postcentral lesion. Which modality is NOT in the printed list?","Vibration sense at the malleolus","Tactile localization","Two point discrimination","Graphesthesia",exp="The four printed cortical sensations are tactile localization, two point discrimination, stereognosis and graphesthesia; vibration is not listed."),
 q(560,"scenario","A patient cannot recognise a key placed in the hand although primary sensation is intact, and graphesthesia is lost. Which cortical sensation is being tested by the key task?","Stereognosis","Tactile localization","Two point discrimination","Graphesthesia",exp="Stereognosis, the recognition of an object by touch, is one of the four cortical sensations listed as impaired."),
]),
("Superior parietal praxicons, apraxia types and the inferior parietal lobule",
 "Superior parietal praxicons, apraxia types and the inferior parietal lobule",
 "The superior parietal lobule generates praxicons, and its injury produces the printed definition of apraxia with an ideational/ideomotor split. The inferior parietal lobule adds gnosis and visual agnosia, then handedness dominance percentages and the non-dominant pseudoapraxia picture.", [
 q(561,"recall","What does the printed line credit the superior parietal lobule with generating?","Praxicons: movement formula / sensory guidance for movement","Broca's motor speech programme","The pupillary light reflex arc","Cortical pain discrimination",exp="Under SUPERIOR PARIETAL LOBULE the text reads 'generate Praxicons : movement formula/sensory guidance for movement.'"),
 q(561,"recall","Which functions must be normal for the printed definition of apraxia to apply?","Cerebellum, motor and sensory function and comprehension","Vision, hearing and speech output only","Memory, mood and sleep","Bladder control, gait and tone",exp="Apraxia is defined as 'Inability to execute a learnt voluntary skilled action despite normal cerebellum, motor & sensory function and comprehension.'"),
 q(561,"recall","What specific failure is printed for a superior parietal lobule lesion?","Inability to generate praxicons","Inability to perceive pain","Inability to fixate","Inability to recall autobiographical events",exp="The second bullet reads 'Lesion in SPL : Inability to generate praxicons.'"),
 q(561,"scenario","Asked to wave goodbye, a patient knows exactly what is required and describes the gesture, but the hand produces a clumsy, wrong movement. Which printed type applies?","Ideomotor apraxia - idea present, execution poor","Ideational apraxia - idea absent","Constructional apraxia","Dressing apraxia",exp="The types are printed as 'Ideational apraxia : Idea absent.' and 'Ideomotor apraxia : Idea present -> Execution poor.'"),
 q(561,"recall","How is 'gnosis' defined in the inferior parietal section?","Ability to recognize an object by touch, vision or sound","Ability to initiate a learned movement","Ability to locate a point in space","Ability to copy a complex figure",exp="Under Supramarginal gyrus the text reads 'gnosis : Ability to recognize object by touch/vision/sound.'"),
 q(561,"recall","Visual agnosia is defined on the page as what, and which two areas are printed as affected?","Inability to identify by vision; supramarginal gyrus and parieto-occipital association area","Inability to see light; primary visual cortex and lateral geniculate","Inability to name colours; fusiform gyrus only","Inability to perceive motion; superior colliculus only",exp="The visual agnosia block reads 'Inability to identify by vision' with areas 'Supramarginal gyrus' and 'Parieto-occipital association area : Visuospatial orientation'."),
 q(561,"recall","What annotation is printed for the parieto-occipital association area in this block?","Visuospatial orientation","Motor formula generation","Auditory word recognition","Pain and temperature discrimination",exp="The figure labels 'Parieto-occipital association area : Visuospatial orientation' beside the parieto-occipital region."),
 q(561,"oddoneout","Four drawings are captioned visual agnosia on this page. Which object label is NOT printed beneath one of them?","Spider","Snake","Bug","Lamp",exp="The printed captions under the four drawings are snake, stereo or computer, bug and lamp; spider is not one of them."),
 q(561,"numeric","For a right-handed person, what are the printed percentages of parietal dominance?","Left lobe 90-95%, right lobe 5%","Left lobe 50-60%, right lobe 40%","Left lobe 40%, right lobe 60%","Left lobe 5%, right lobe 95%",exp="The table prints Right handed as right lobe 5% and left lobe 90-95%."),
 q(561,"numeric","For a left-handed person, which pair of printed percentages applies?","Right lobe 40%, left lobe 50-60%","Right lobe 5%, left lobe 95%","Right lobe 60%, left lobe 40%","Right lobe 50%, left lobe 50%",exp="The second table row prints Left handed: right lobe 40% and left lobe 50-60%."),
 q(561,"recall","What additional function is stated to belong to the dominant lobe?","Language","Grip strength","Pupillary reflex","Bladder inhibition",exp="Beneath the handedness table the line reads 'Language is part of dominant lobe.'"),
 q(561,"scenario","A patient with a right parietal lesion cannot button a shirt or copy an intersecting-square figure, yet strength and comprehension are normal. Which printed non-dominant term covers this pair?","Pseudoapraxia, comprising constructional and dressing apraxia","Ideational apraxia from superior parietal praxicon loss","Gerstman syndrome of the dominant angular gyrus","Ideomotor apraxia from anterior callosal disconnection",exp="The non-dominant parietal lobe heading lists pseudoapraxia with constructional apraxia and dressing apraxia, the latter illustrated by being unable to put on a jacket."),
 q(561,"recall","How is constructional apraxia defined in the printed text?","Inability to perceive and imagine geometric relation","Inability to speak fluently","Inability to recognise faces","Inability to plan saccades",exp="The bullet reads 'Constructional apraxia : Inability to perceive and imagine geometric relation.'"),
 q(561,"scenario","After a right parietal infarct a patient gets lost between his own bedroom and bathroom although memory and vision are intact. Which printed non-dominant deficit explains this?","Visuospatial disorientation - inability to differentiate places","Topographic memory loss with pure alexia","Ideational apraxia with an absent idea","Gerstman syndrome with acalculia",exp="The last bullet of the page defines visuospatial disorientation as the inability to differentiate places, illustrated by the bedroom and bathroom example."),
]),
("Hemispatial neglect, the angular gyrus and alexia without agraphia",
 "Hemispatial neglect, the angular gyrus and alexia without agraphia",
 "Neglect, its asymmetrical hemispheric table and topographic agnosia open the closing page, illustrated by Rey-Osterrieth copies, a flower and a clock. Angular gyrus functions and the four-part Gerstman syndrome follow, ending with the left PCA plus splenium disconnection ladder and the lobe-wise visual field defects.", [
 q(562,"recall","Hemispatial neglect is bracketed on this page with which two terms?","Anosognosia and Asomatognosia","Agnosia and aphemia","Astereognosis and agraphia","Acalculia and anomia",exp="The bullet reads 'Hemispatial neglect (Anosognosia/Asomatognosia) : visual scanning (Body schema) -> Neglect of activities related to one of the hemispheres.'"),
 q(562,"recall","Which higher-order process is named in parentheses as the mechanism of neglect on this page?","Visual scanning (body schema)","Motor planning (praxis formula)","Auditory stream segregation","Working-memory encoding",exp="The printed gloss is 'visual scanning (Body schema)' before the neglect definition."),
 q(562,"oddoneout","According to the printed right-versus-left parietal table, which statement is NOT correct?","Left parietal lesions produce right hemispatial neglect","Right parietal lobe subserves extrapersonal space on the right and the left","Left parietal lobe subserves extrapersonal space on the right only","Left parietal lobe lesion shows no abnormality",exp="The table prints left parietal extrapersonal space as 'Right' and its lesion row as 'No abnormality', so neglect of the right field is not a left parietal sign."),
 q(562,"recall","Which side of space is neglected after a right parietal lesion, as printed?","Left hemispatial neglect","Right hemispatial neglect","Bilateral neglect of all space","No neglect at all",exp="The right parietal column lists the lesion row as 'Left hemispatal neglect' (as printed)."),
 q(562,"recall","How is topographic agnosia defined on this page?","Loss of orientation to topography","Loss of ability to draw figures","Loss of face recognition","Loss of colour naming",exp="The bullet reads 'Topographic agnosia : Loss of orientation to topography.'"),
 q(562,"scenario","A patient draws a clock face with the numerals crowded onto one side instead of spread around it. Which printed caption does this illustration carry?","Hemispatial neglect","Constructional apraxia","Topographic agnosia","Visual agnosia",exp="The flower and clock drawings on the right of the page are captioned Hemispatial neglect, while the copied geometric figures are captioned Constructional apraxia By patient."),
 q(562,"scenario","You must document a parietal patient's copying deficit with the figure the book reproduces. Which named figure and comparison does the printed illustration use?","Rey-Osterrieth Complex Figure (ROCF), original figure versus the patient's copies","Stroop colour-word card, colour condition versus word condition","Boston Naming Test plate set with the patient's naming score","Ishihara plate series, normal colour vision versus acquired defect",exp="The left-hand drawing is labelled as the Rey-Osterrieth Complex Figure (ROCF) figure versus patient, with the A1, A2 and A3 patient copies beneath it."),
 q(562,"oddoneout","Which function is NOT listed among the printed angular gyrus functions?","Calculation","Reading","Writing","Naming",exp="The functions column prints Reading, Writing, Naming and 'Spatial orientation with respect to finger, number, body sites'; calculation appears only as acalculia in Gerstman syndrome."),
 q(562,"recall","Spatial orientation at the angular gyrus is specified with respect to which three items?","Finger, number and body sites","Colour, shape and motion","Pitch, rhythm and loudness","Flexion, extension and rotation",exp="The fourth function bullet reads 'Spatial orientation with respect to finger, number, body sites.'"),
 q(562,"recall","Gerstman syndrome is printed as the result of which lesion?","Lesion of the dominant angular gyrus","Lesion of the non-dominant superior parietal lobule","Lesion of the orbital frontal cortex","Lesion of the posterior limb of the internal capsule",exp="The Gerstman column opens 'Lesion of dominant angular gyrus.'"),
 q(562,"oddoneout","Which feature is NOT part of the printed Gerstman syndrome list?","Limb-kinetic apraxia of the contralateral hand","Alexia (impaired reading) with agraphia (impaired writing)","Anomia, that is impaired naming","Finger anomia, acalculia and right-to-left disorientation",exp="The printed syndrome lists alexia with agraphia, anomia and finger anomia/acalculia/right-to-left disorientation; limb-kinetic apraxia is not named."),
 q(562,"scenario","A patient can write a dictated sentence perfectly but cannot read back what he has just written. Which printed vascular-anatomical combination explains this?","Left PCA infarct plus splenium of the corpus callosum","Left MCA superior division infarct only","Right MCA inferior division infarct","Bilateral anterior cerebral artery infarcts",exp="The note reads 'Left Posterior Cerebral Artery (PCA) Infarct + Splenium of corpus callosum', with the disconnection arm giving 'Alexia without agraphia'."),
 q(562,"recall","How is the disconnection syndrome defined in that printed branch?","Loss of connection between cortices","Loss of thalamocortical relay only","Loss of peripheral optic radiation in the temporal lobe","Loss of brainstem internuclear fibres",exp="The right-hand branch states 'Disconnection syndrome (Loss of connection between cortices).'"),
 q(562,"recall","In the occipital-lobe branch of the same note, macular sparing is paired with which field defect?","Contralateral (right) homonymous hemianopia","Ipsilateral homonymous hemianopia","Bitemporal hemianopia","Inferior quadrantanopia of one eye",exp="The branch prints 'Vision normal (macular sparing)' and 'C/L (Right) homonymous hemianopia'."),
 q(562,"recall","Pure alexia is printed as a lesion of which gyrus?","Fusiform gyrus","Supramarginal gyrus","Cingulate gyrus","Inferior temporal gyrus",exp="The bullet reads 'Pure Alexia : Lesion of fusiform gyrus.'"),
 q(562,"oddoneout","The printed lobe-wise visual abnormalities list matches each lobe to a defect. Which pairing is wrong?","Frontal lobe - inferior homonymous quadrantanopia","Parietal lobe - inferior homonymous quadrantanopia (pie in floor)","Temporal lobe - superior homonymous quadrantanopia (pie in sky)","Frontal lobe - contralateral hemianopia",exp="The list prints frontal lobe as C/L hemianopia, parietal as inferior quadrantanopia (pie in floor) and temporal as superior quadrantanopia (pie in sky)."),
 q(562,"management","A patient after a left temporal lobe resection reports trouble seeing material above eye level on the right. Which printed pattern and side fit this complaint?","Contralateral superior homonymous quadrantanopia, pie in the sky","Contralateral inferior homonymous quadrantanopia, pie in the floor","Ipsilateral hemianopia with macular sparing","Bitemporal hemianopia with loss of colour vision",exp="The printed table assigns the temporal lobe 'U/L superior homonymous quadrantanopia (Pie in sky)', the parietal lobe the pie-in-floor counterpart and the frontal lobe a C/L hemianopia."),
]),
])

write(ch30)
write(ch31)
