#!/usr/bin/env python3
"""Author source-ordered learning sets for Chapters 27–29.

The source pages are scanned pages p532–554 from uploads/02.pdf (PDF64–86),
read visually from 2× PyMuPDF renders with FILE-tagged verification. Each row
is a four-option book-study question in the same JSON contract used for
Chapters 9–26 and 33–38: reasoning-first formats only (recall, scenario,
numeric, oddoneout, management), strictly printed-page order, and every
explanation ending with its exact (Book pX) citation.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data"


def make_chapter(number, title, page_range, unit_specs):
    questions = []
    units = []
    for unit_no, (section, unit_title, guide, rows) in enumerate(unit_specs, 1):
        if "\n" not in guide:
            sentences = []
            buf = ""
            for word in guide.split(" "):
                buf = (buf + " " + word).strip()
                if word.endswith((".", "!", "?")):
                    sentences.append(buf)
                    buf = ""
            if buf:
                sentences.append(buf)
            if len(sentences) >= 2:
                mid = (len(sentences) + 1) // 2
                guide = "\n".join([" ".join(sentences[:mid]), " ".join(sentences[mid:])])
            else:
                words = guide.split()
                third = max(1, len(words) // 2)
                guide = " ".join(words[:third]) + "\n" + " ".join(words[third:])
        ids = []
        for page, fmt, stem, correct, distractors, explanation in rows:
            qid = f"MED-C{number}-{len(questions)+1:02d}"
            choices = [correct, *distractors]
            shift = (len(questions) * 3 + number) % 4
            choices = choices[shift:] + choices[:shift]
            questions.append({
                "id": qid, "sec": section, "page": page, "fmt": fmt,
                "q": stem, "opts": choices, "ans": choices.index(correct),
                "exp": explanation + f" (Book p{page})",
            })
            ids.append(qid)
        units.append({
            "id": f"MED-U{number}-{unit_no}", "ch": number, "n": unit_no,
            "title": f"{unit_no}. {unit_title}", "sec": section,
            "guide": guide, "qs": ids,
        })
    return {"chapter": number, "title": title, "pageRange": page_range,
            "questions": questions, "units": units}


def q(page, fmt, stem, correct, *distractors, exp):
    assert len(distractors) == 3, (stem, distractors)
    return (page, fmt, stem, correct, list(distractors), exp)


def write(chapter):
    path = OUT / f"ch{chapter['chapter']:02d}.json"
    path.write_text(json.dumps(chapter, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{path.name}: {len(chapter['questions'])} questions / {len(chapter['units'])} units")


ch27 = make_chapter(27, "Spondyloarthritis", "532-542", [
("Spondyloarthritis classification, shared features and non-radiographic axial SpA",
 "Spondyloarthritis classification, shared features and non-radiographic axial SpA",
 "The chapter opens with the axial, peripheral and juvenile SpA tree and shared features. Non-radiographic axial SpA clinical features, MRI note and 5% progression in 5–10 years are kept in printed order. Radiographic conversion brings sacroiliitis x-ray features and extra-articular may be seen.", [
 q(532,"recall","Which branch of the printed SpA classification tree lists shoulder and hip as root joints?","Axial spondyloarthropathy","Peripheral spondyloarthropathy limited to knee and elbow","Juvenile idiopathic arthritis (juvenile onset SpA)","Isolated enthesitis without articular involvement",exp="The classification tree places shoulder and hip (root joints) under axial SpA, which then divides into non-radiographic and radiographic axial SpA."),
 q(532,"recall","Which trio is printed under the peripheral SpA arm of the classification tree?","Reactive arthritis, psoriatic arthritis and IBD (enteropathic) arthritis","Ankylosing spondylitis, DISH and gout","Rheumatoid arthritis, SLE and scleroderma","GCA, Takayasu arteritis and PAN",exp="Peripheral SpA (peripheral involvement greater than axial) lists reactive arthritis, psoriatic arthritis and IBD enteropathic arthritis."),
 q(532,"recall","How does the source equate juvenile idiopathic arthritis within the SpA tree?","JIA is also called juvenile onset SpA","JIA is a subset of radiographic axial SpA only","JIA is excluded from the SpA classification","JIA equals non-radiographic axial SpA with no peripheral disease",exp="The tree annotates juvenile idiopathic arthritis as AKA juvenile onset SpA."),
 q(532,"recall","Which HLA association and degree are printed among SpA shared features?","HLA B27 association in varying degrees","HLA B51 as the universal SpA marker","HLA DR4 in 100% of cases only","No HLA association is printed",exp="Shared features begin with HLA B27 association (varying degrees)."),
 q(532,"recall","What is the printed most common extra-articular manifestation of SpA?","Acute anterior alternating asymmetric uveitis (4A uveitis)","Chronic posterior uveitis only","Episcleritis without uveitis","Keratitis as the sole ocular feature",exp="Features list m/c extra-articular manifestation as acute anterior alternating asymmetric uveitis (4A uveitis)."),
 q(532,"oddoneout","Which statement among the printed SpA features favors SpA over rheumatoid arthritis?","Absence of rheumatoid factor and of subcutaneous nodules with RA extra-articular features","Significant familial aggregation with HLA B27 association","4A uveitis as the most common extra-articular manifestation","Association with plaque-type psoriasis in the peripheral arm",exp="SpA features print absence of rheumatoid factor and absence of subcutaneous nodules and extra-articular features of RA."),
 q(532,"scenario","A young patient has inflammatory back pain worse with rest and better with activity, alternating buttock pain, and no plain-film sacroiliitis. Which printed label applies?","Non-radiographic axial SpA","Radiographic axial SpA (ankylosing spondylitis)","Enteropathic arthritis with axial pattern","DISH with metabolic syndrome",exp="Non-radiographic axial SpA clinical features are inflammatory back pain (exacerbated by rest, relieved by activity), alternating buttock pain due to sacroiliitis and deep low back pain, with no radiographic evidence of sacroiliitis."),
 q(532,"recall","What imaging and serology notes are printed for non-radiographic axial SpA?","No radiographic sacroiliitis; MRI may show active sacroiliitis; may have HLA B27","Plain x-ray always shows grade 3 sacroiliitis; MRI never informative","RF-positive serology is required","HLA B27 is always negative by definition",exp="Non-radiographic axial SpA: no radiographic evidence (x-ray features of sacroiliitis), MRI may show active sacroiliitis and it may have HLA B27 association."),
 q(532,"numeric","What proportion of non-radiographic axial SpA converts to radiographic axial SpA over 5–10 years, and what does the right arm list?","5% in 5–10 years; x-ray features include syndesmophytes, bony ankylosis, bamboo spine and spinal fracture","50% in 1 year; only soft-tissue swelling","10% in 20 years; only disc space narrowing","90% in 5 years; only osteopenia without syndesmophytes",exp="The conversion arrow prints 5% in 5–10 years to radiographic axial SpA whose x-ray features of sacroiliitis are syndesmophytes, bony ankylosis, bamboo spine and spinal fracture; extra-articular manifestations may be seen."),
]),
("Radiographic axial SpA pathogenesis, presentation and inflammatory back pain",
 "Radiographic axial SpA pathogenesis, presentation and inflammatory back pain",
 "Inflammatory granulation tissue erodes disc structures and calcifies annular fibres into syndesmophytes. Vertical osteophytes, gliding, bony ankylosis, bamboo spine and square-wave vertebra complete the mechanical chain. Complication, mediators, synovitis–enthesitis presentation and inflammatory back pain aspects follow source order.", [
 q(533,"recall","According to the pathogenesis block, inflammatory granulation tissue directly causes which two changes?","Erosion of annulus fibrosis and nucleus pulposus, and calcification of peripheral annular fibres producing syndesmophytes","Isolated disc herniation without calcification","Subchondral cyst formation only","Pure ligamentous hypertrophy without erosion",exp="Inflammatory granulation tissue lists erosion of annulus fibrosis and nucleus pulposus, and calcification of peripheral fibres of annulus fibrosis as syndesmophytes."),
 q(533,"recall","How does the source characterize the vertical osteophyte that arises from syndesmophyte calcification?","Thin, delicate, marginal and symmetrical","Thick, coarse, non-marginal and asymmetrical","Lateral and non-continuous with the disc","Restricted to the posterior elements only",exp="Under the calcification arm the vertical osteophyte is annotated thin, delicate, marginal, symmetrical."),
 q(533,"recall","What mechanical sequence is printed after gliding of vertebra over one another?","Bony ankylosis leading to bamboo spine and square-wave vertebra (loss of concavity)","Fresh fracture without fusion","Prolapsed disc with vacuum phenomenon","Isolated osteophyte lipping without fusion",exp="Gliding of vertebra over one another leads to bony ankylosis, producing bamboo spine and square wave vertebra (loss of concavity)."),
 q(533,"numeric","Which complication level is printed as most common for spinal fracture in this chapter?","C5–C6","L4–L5","T10–T11","C1–C2 only",exp="Complication lists spinal fracture with m/c site C5–C6."),
 q(533,"recall","Which inflammatory mediators are printed for radiographic axial SpA?","TNF alpha, IL-17 and IL-23","IL-6 and IL-1 only","Complement C3 and C4","TGF-beta and PDGF alone",exp="Inflammatory mediators listed are TNF alpha and IL-17, IL-23."),
 q(533,"recall","What dual presentation framework organizes the clinical features of radiographic axial SpA?","Synovitis plus enthesitis","Purpura plus arthralgia only","Tophi plus calcinosis","Urticaria plus vasculitis",exp="Presentation is structured as synovitis plus enthesitis (inflammation of tendon, ligament, capsule, fascia)."),
 q(533,"scenario","Bilateral sacroiliitis on imaging in early axial disease is described in the source as what?","The hallmark and earliest manifestation","A late complication only","An exclusive feature of psoriatic arthritis","A contraindication to exercise therapy",exp="Under synovitis, B/L sacroiliitis is annotated as hallmark and earliest manifestation."),
 q(533,"numeric","What sex ratio, age group and HLA frequency are printed for ankylosing spondylitis presentation?","M:F 3:1, early 20s, HLA B27 in 90% of AS","F:M 3:1, late 60s, HLA B27 in 10%","Equal sex ratio, children under 10, B27 negative","M:F 9:1, age over 50, B27 in 50%",exp="Presentation prints M:F = 3:1, age early 20s and HLA B27 association in 90% of AS."),
 q(533,"recall","Among enthesitis sites, which is called classical in the source?","Achilles tendinitis","Plantar fasciitis alone","Costochondritis alone","Lateral epicondylitis",exp="Enthesitis examples: Achilles tendinitis is annotated classical; plantar fasciitis and costochondritis follow."),
 q(533,"scenario","A patient reports morning back stiffness lasting about 45 minutes that improves with exercise and NSAIDs but not with rest. Which printed aspects are satisfied?","Duration over 3 months, improvement with exercise, improvement with NSAIDs and no improvement with rest","Onset after age 60 with rapid response to bed rest","Shorter than 2 weeks with worsening on activity","Location confined to the neck with no buttock pain",exp="Inflammatory back pain aspects: duration >3 months (chronic), improvement with exercise, improvement with NSAIDs and no improvement of pain with rest; morning stiffness minimum 30 minutes."),
 q(533,"recall","Which onset and location details are printed for inflammatory back pain?","Onset before 45 years with lower-back location and alternating buttock pain","Onset after 70 years confined to the thoracic spine","Onset in childhood with isolated cervical pain","No defined age with constant midline pain only",exp="Aspects list onset before 45 yrs, location lower back and alternating buttock pain."),
 q(533,"numeric","What minimum morning stiffness duration and waking-from-sleep feature are printed?","Morning stiffness of at least 30 minutes with waking from sleep due to back pain","Stiffness under 10 minutes without nocturnal waking","All-day stiffness only","No morning stiffness is characteristic",exp="Aspects include waking up from sleep due to back pain and morning stiffness (minimum 30 mins)."),
 q(533,"scenario","Involvement of shoulders and hip joints in axial SpA is annotated in the source as indicating what?","Poor prognosis","Complete drug-free remission","Exclusion of HLA B27 association","Indication to stop exercise therapy",exp="The final inflammatory-back-pain aspect annotates involvement of shoulders and hip joint as poor prognosis."),
 q(533,"recall","Which extra-articular list belongs to radiographic axial SpA on this page?","4A uveitis (m/c), aortic regurgitation/ascending aortitis/conduction blocks, secondary IgA nephropathy, upper-lobe NSIP, enthesitis-related chest pain and osteoporosis","Only palmar plantar pustulosis without eye disease","Isolated cerebral vasculitis","Membranous nephropathy with Hearing loss only",exp="Extra-articular features print 4A uveitis m/c; CVS aortic regurgitation, ascending aortitis, conduction blocks; renal secondary IgA nephropathy; lungs upper lobe interstitial lung disease (NSIP); chest pain from costochondritis/manubriosternal enthesitis plus ascending thoracic spine; and osteoporosis."),
 q(533,"scenario","Chest pain in a patient with ankylosing spondylitis is attributed in the text to which mechanism?","Enthesitis at costochondritis or manubriosternal joint plus ascending thoracic spine involvement","Acute coronary syndrome only","Pulmonary embolism alone","Pericardial effusion without enthesitis",exp="Chest pain is d/t enthesitis at costochondritis or manubriosternal joint plus ascending thoracic spine."),
]),
("Investigation: MRI-STIR, sacroiliitis x-ray grading and radiographic signs",
 "Investigation: MRI-STIR, sacroiliitis x-ray grading and radiographic signs",
 "Upper-lobe ILD and osteoporosis ranking notes precede the MRI-STIR block. Plain x-ray grades 0–4 of sacroiliitis with the earliest sign and bamboo spine close the imaging unit. Dagger, trolley-track, Romanus, shiny-corner and square-wave signs are kept as printed definitions.", [
 q(534,"recall","Which conditions are paired with upper-lobe interstitial lung disease in the printed note?","Sarcoidosis and ankylosing spondylitis","RA and systemic sclerosis only","SLE and polymyositis","PAN and EGPA",exp="Note: Upper Lobe ILD — sarcoidosis, ankylosing spondylitis."),
 q(534,"numeric","What osteoporosis frequency ranking is printed?","RA > AS > sarcoidosis > SLE","SLE > RA > AS > sarcoidosis","AS > RA > SLE > sarcoidosis","Sarcoidosis > SLE > RA > AS",exp="Note prints osteoporosis: RA > AS > sarcoidosis > SLE."),
 q(534,"recall","What does STIR stand for in the printed investigation note, and how is hyperintensity interpreted?","Short Tau Inversion Recovery; hyperintensity is inconclusive","Signal Transfer Inversion Recovery; hyperintensity is diagnostic","Saturation Through Inversion Recovery; hyperintensity excludes disease","Short Time Inversion Region; hyperintensity is pathognomonic",exp="Investigation: MRI — STIR sequence; STIR = Short Tau Inversion Recovery; hyperintensity: inconclusive."),
 q(534,"recall","Which MRI panel labels are printed beneath the sacroiliac images?","Semi-coronal T1, semi-coronal T1FS, semi-coronal STIR and semi-axial STIR","Only AP pelvis and lateral views","T2 maps without T1 images","Diffusion tensor imaging only",exp="The MRI strip is captioned semi-coronal T1, semi-coronal T1FS, semi-coronal STIR and semi-axial STIR."),
 q(534,"recall","What is printed as grade 0 of sacroiliitis on plain x-ray?","Normal joints","Blurring plus sclerosis","Loss of margins with widening","Joint ankylosis",exp="Grade 0 caption reads normal joints."),
 q(534,"numeric","Which grade description and timing label apply to the earliest x-ray sign of sacroiliitis?","Grade 1: slight blurring of cortical margins of the lower one-third of each joint; earliest x-ray sign","Grade 2: blurring and sclerosis only","Grade 3: loss of margins and widening of joint space","Grade 4: complete joint ankylosis",exp="Grade 1 shows slight blurring of cortical margins of lower 1/3rd of each joint and is marked earliest x-ray sign."),
 q(534,"recall","What two findings define grade 2 of sacroiliitis in the source?","Blurring and sclerosis","Loss of margins and joint-space widening","Joint ankylosis only","Pure osteopenia without blurring",exp="Grade 2 caption: blurring + sclerosis."),
 q(534,"recall","What two findings define grade 3 of sacroiliitis?","Loss of margins and widening of joint space","Blurring and sclerosis","Normal cortices with narrow space","Complete bony fusion",exp="Grade 3 lists loss of margins and widening of joint space."),
 q(534,"recall","What single finding defines grade 4 of sacroiliitis?","Joint ankylosis","Marginal blurring","Sclerotic band only","Subchondral cyst only",exp="Grade 4 caption: joint ankylosis."),
 q(534,"scenario","Bilateral sacroiliitis reported as grade 2/3 with a separate bamboo-spine film matches which printed pair of captions?","B/L sacroiliitis (grade 2/3) and bamboo spine","Unilateral grade 1 only and square vertebra","Grade 0 with normal spine","Grade 4 ankylosis with disc herniation",exp="The page captions B/L sacroiliitis (grade 2/3) and a bamboo spine image."),
 q(535,"recall","Which structure calcification produces the dagger sign on AP spine films?","Interspinous ligament","Joint capsule only","Ligamentum flavum alone","Annulus fibrosus only",exp="Dagger sign: calcification of interspinous ligament; shown with dagger spine, rail-road sign and trolley-track sign panels."),
 q(535,"recall","Which structure calcification produces the trolley track sign?","Joint capsule","Interspinous ligament only","Disc space only","Spinous process tip only",exp="Trolley track sign: calcification of joint capsule."),
 q(535,"recall","What is the Romanus sign and its printed downstream signs?","Erosion of the vertebral corner, then shiny-corner sclerosis, then square-wave vertebra with loss of concavity","Sclerosis isolated to the sacrum","Disc calcification without corner change","Soft-tissue swelling alone",exp="Romanus sign: erosion of corner; shiny corner sign: sclerosis of vertebra; square wave vertebra: vertebra become square-like."),
 q(535,"numeric","In the modified Schober test, what are the landmark and the A-to-B distance marked on the diagram?","Posterior superior iliac spine landmark with A to B = 15 cm (10 cm above plus 5 cm below)","Iliac crest with A to B = 5 cm","ASIS with A to B = 20 cm","Sacrococcygeal junction with A to B = 25 cm",exp="Landmark is posterior superior iliac spine; diagram labels A to B = 15 cm with 10 cm and 5 cm segments."),
 q(535,"scenario","During modified Schober testing the patient bends forward with knees extended and the A-to-B span measures 17 cm. How is this classified?","Abnormal, because A to B under 20 cm is abnormal","Normal, because the minimum is 15 cm","Normal only if the knees are flexed","Indicative of grade 4 sacroiliitis",exp="Forward bending with knee in extension; A to B 20 cm (minimum) is normal, less than 20 cm is abnormal."),
 q(535,"management","How are non-radiographic axial SpA and ankylosing spondylitis managed first in the printed algorithm?","Non-radiographic axial SpA: NSAIDs when needed; AS: exercise and physiotherapy as most important","Bed rest for both until symptoms resolve","Opioids as first line for both","Immediate biologics without NSAIDs",exp="Treatment: non-radiological axial SpA — NSAIDs when needed; AS — exercise, physiotherapy (most important)."),
 q(535,"numeric","Which first-line NSAID regimen and duration purpose are printed for AS?","Indomethacin 50 mg TID (also naproxen, ibuprofen); first line that prevents progression; duration 2–3 weeks","Colchicine 0.6 mg daily for 6 months","Prednisolone 60 mg taper over 8 weeks","Methotrexate 15 mg weekly as first line",exp="NSAID: indomethacin 50 mg TID, naproxen, ibuprofen — first line, prevent progression of disease, duration 2–3 wks."),
]),
("Advanced therapy, DISH and reactive arthritis onset",
 "Advanced therapy, DISH and reactive arthritis onset",
 "Adalimumab, secukinumab and intra-articular steroids complete axial therapy. DISH demographics, metabolic link and flowing-wax x-ray appearance open the differential block. Reiter's triad, 4A uveitis, demographics, infection-to-arthritis timing and trigger organisms stay in printed order.", [
 q(536,"management","Which biologic pair is printed after the NSAID block for axial SpA?","Anti-TNF alpha: adalimumab; anti-IL-17: secukinumab","Anti-IL-6: tocilizumab; anti-CD20: rituximab","Abatacept and anakinra as the only options","JAK inhibitor tofacitinib plus baricitinib",exp="The treatment continuation prints anti TNF alpha: adalimumab and anti IL-17: secukinumab."),
 q(536,"management","What is the printed role of intra-articular steroids in this chapter?","For pain relief","To induce bony ankylosis","As disease-modifying monotherapy","To replace exercise therapy",exp="Intra-articular steroids: for pain relief."),
 q(536,"recall","What demographic and inflammatory profile is printed for DISH?","Elderly male, non-inflammatory, part of metabolic syndrome","Young female with raised ESR as the rule","Children with HLA B27 association","Acute inflammatory monoarthritis of the first MTP",exp="DISH (diffuse idiopathic skeletal hyperostosis): elderly male, non-inflammatory, part of metabolic syndrome."),
 q(536,"recall","Which structural and radiographic features complete the printed DISH description?","Ligamentous calcification with flowing wax appearance on x-ray","Marginal syndesmophytes with bamboo spine only","Punched-out erosions with overhanging edges","Chondrocalcinosis of the knee only",exp="DISH lists ligamentous calcification and flowing wax appearance in x-ray; dorsal and lumbar spine films illustrate the flow."),
 q(536,"recall","What former name and classic triad are printed for reactive arthritis?","Reiter's syndrome: urethritis, arthritis, conjunctivitis","Whipple disease triad of malabsorption and arthralgia","Behcet triad of oral and genital ulcers with uveitis only","Reiter as a seronegative RA subtype",exp="Reactive arthritis was previously known as Reiter's syndrome (urethritis, arthritis, conjunctivitis)."),
 q(536,"recall","Which extra-articular feature and demographic pattern are printed for reactive arthritis?","4A uveitis as most common; male greater than female, age 20–40 years","Chronic posterior uveitis with female predominance over 60","No ocular involvement with equal sex ratio in children","Episcleritis only after age 70",exp="m/c extra-articular manifestation: 4A uveitis; m > F, 20–40 yrs."),
 q(536,"numeric","What interval and axial involvement percentage appear on the infection-to-arthritis flowchart?","Infection after 2–4 weeks leads to arthritis, with axial involvement in 30%","Infection same day with axial involvement in 5%","Infection after 6 months with axial involvement in 80%","No latency with axial involvement in 10%",exp="Flowchart: infection → 2–4 weeks → arthritis with peripheral and axial (30%) arms."),
 q(536,"numeric","What percentage of reactive arthritis episodes is printed as progressing to chronic arthritis?","20%","5%","50%","80%",exp="The flowchart prints 20% progressing to chronic arthritis."),
 q(536,"numeric","Which genitourinary trigger and sex ratio are printed as most common worldwide?","Chlamydia trachomatis with M:F 9:1","Neisseria gonorrhoeae with M:F 1:1","Ureaplasma with female predominance","Salmonella with equal sex ratio",exp="Genitourinary: Chlamydia trachomatis (m/c cause worldwide) with M:F = 9:1."),
 q(536,"numeric","Which gastrointestinal trigger is most common in India, and what is its sex ratio?","Shigella flexneri with M:F 1:1","Campylobacter jejuni with M:F 9:1","Salmonella with M:F 3:1","E. coli with male predominance",exp="Gastrointestinal: Shigella flexneri (m/c cause in India) with M:F = 1:1; Salmonella and Campylobacter follow."),
 q(536,"oddoneout","Which organisms are explicitly excluded as causative agents of reactive arthritis on this page?","E. coli and Neisseria","Salmonella and Campylobacter","Shigella flexneri","Chlamydia trachomatis",exp="Note: E. coli and neisseria are not causative agents."),
]),
("Reactive arthritis clinical course, mucocutaneous lesions and axial involvement",
 "Reactive arthritis clinical course, mucocutaneous lesions and axial involvement",
 "Sterile arthritis, PCR detection and HLA-B27 chronicity precede the asymmetrical pattern. Synovitis–enthesitis–dactylitis, keratoderma and circinate balanitis with psoriasis d/d follow. Axial 30% with fluffy non-marginal syndesmophytes closes the block.", [
 q(537,"scenario","Synovial fluid cultures are sterile but PCR detects organism DNA inside synovial monocytes. Which printed concept applies?","Acute sterile arthritis with organisms inside synovial monocytes detected by PCR","Culture-positive septic arthritis","Crystal-proven gout without infection","Non-inflammatory osteoarthritis",exp="Acute sterile arthritis: organism not isolated from synovial fluid; organisms inside monocytes of synovium are detected by PCR of synovial fluid."),
 q(537,"numeric","What HLA B27 percentage in reactive arthritis is linked to chronicity and prognosis?","50%–70% of cases","5%–10%","Over 95%","0% by definition",exp="HLA B-27 association in 50%–70% cases is linked to chronicity and prognosis."),
 q(537,"scenario","A patient's arthritis starts in one knee and later adds joints asymmetrically with pain. Which printed pattern is this?","Asymmetrical peripheral arthritis starting at the knee with oligoarthritis greater than monoarthritis, additive and painful","Symmetrical small-joint polyarthritis of MCP joints only","Isolated axial disease without peripheral joints","Non-inflammatory mechanical pain",exp="Asymmetrical peripheral arthritis: starts at knee joint; oligoarthritis greater than monoarthritis; additive — progressive involvement of joints; painful."),
 q(537,"recall","Which clinical manifestation triad is printed for reactive arthritis?","Synovitis plus predominant enthesitis plus dactylitis","Tophi plus calcinosis plus uveitis","Purpura plus arthritis plus nephritis","Fever plus rash plus lymphadenopathy alone",exp="Clinical manifestations: synovitis plus predominant enthesitis plus dactylitis; images show Achilles enthesitis and sausage-digit dactylitis."),
 q(537,"recall","How are keratoderma blennorrhagicum and circinate balanitis described?","Keratoderma: hyperkeratotic crusty painless vesicles on palms and soles; balanitis: shallow painless erythematous glans ulcers","Both are painful ulcerative lesions only on soles","Keratoderma is pustular only on the trunk","Balanitis is a scarring phimosis",exp="1. Keratoderma blennorrhagicum: hyperkeratotic, crusty vesicles on palms and soles, painless. 2. Circinate balanitis: shallow erythematous ulcers of glans penis, painless."),
 q(537,"recall","What is the printed differential diagnosis of keratoderma blennorrhagicum?","Palmo-plantar psoriasis","Secondary syphilis only","Disseminated gonococcemia only","Pompholyx alone",exp="Note: D/d for keratoderma blennorrhagicum — palmo-plantar psoriasis."),
 q(537,"numeric","What percentage develops axial involvement in reactive arthritis, and what pattern of sacroiliitis is printed?","30% with asymmetric sacroiliitis","10% with symmetric sacroiliitis only","80% with no sacroiliitis","5% with complete ankylosis at onset",exp="Axial involvement of reactive arthritis (30%) with asymmetric sacroiliitis."),
 q(537,"recall","Which syndesmophyte morphology is printed for reactive arthritis axial disease?","Thick, large, coarse, fluffy and non-marginal due to paravertebral ossification","Thin, delicate, marginal and symmetrical","Punched-out and periarticular only","Sclerotic and banded without ossification",exp="Syndesmophytes d/t paravertebral ossification: thick, large, coarse, fluffy, non-marginal."),
]),
("Reactive arthritis systemic features, treatment and enteropathic arthritis",
 "Reactive arthritis systemic features, treatment and enteropathic arthritis",
 "Cardiac and renal extras plus severity-independent outcome lead investigations. Gonococcal migratory note and the indomethacin–sulfasalazine ladder complete reactive therapy. Enteropathic epidemiology, axial features and the LMAP versus SMAP-u table follow in printed order.", [
 q(538,"recall","Which cardiac and renal extra-articular features are printed for reactive arthritis?","Aortic regurgitation (most common) with conduction blocks; secondary IgA nephropathy","Mitral stenosis with membranous nephropathy","Hypertrophic cardiomyopathy with amyloidosis","Pericarditis only with minimal-change disease",exp="Other manifestations: heart — aortic regurgitation (m/c), conduction blocks; kidney — secondary IgA nephropathy."),
 q(538,"recall","What outcome statement is printed for reactive arthritis chronicity?","Outcome/chronicity is unrelated to initial severity","Only severe index episodes become chronic","Chronic arthritis occurs only after eye involvement","Severity fully predicts joint destruction",exp="Outcome/chronicity: unrelated to initial severity."),
 q(538,"recall","Which laboratory and microbiology investigations are printed?","Raised ESR/CRP and synovial-fluid PCR that identifies the organism","Low ESR with negative PCR as the rule","Plain x-ray alone without labs","Serum RF as the diagnostic test",exp="Investigations: ESR CRP increased; synovial fluid PCR identifies organism."),
 q(538,"scenario","Migratory upper- and lower-limb arthritis is highlighted in the source against which organism?","Gonococcal arthritis","Chlamydial arthritis only","Shigella arthritis","Crystal arthritis",exp="Note: gonococcal arthritis has migratory upper limb and lower limb arthritis."),
 q(538,"management","Which reactive arthritis treatment triplet is printed?","Indomethacin 50 mg TID, intra-articular steroid for pain, and sulfasalazine for chronic disease (15%–20%)","Colchicine plus allopurinol only","Methotrexate as first line without NSAIDs","Tocilizumab monotherapy",exp="Treatment: NSAIDs — indomethacin 50 mg TID; intraarticular steroid to alleviate pain; DMARD — sulfasalazine for chronic reactive arthritis (15%–20%)."),
 q(538,"recall","What alternate name, sex ratio and IBD hierarchy are printed for enteropathic arthritis?","IBD-associated arthritis; M:F 1:1; Crohn disease greater than ulcerative colitis","Seronegative spondyloarthritis with male predominance; UC greater than Crohn","Rheumatoid-like with female predominance","Psoriatic variant with no bowel link",exp="Enteropathic arthritis AKA IBD associated arthritis; M:F = 1:1; Crohn's disease greater than ulcerative colitis."),
 q(538,"numeric","Which peripheral versus axial pattern percentages are printed for enteropathic arthritis?","Peripheral 25% greater than axial 10%","Peripheral 10% with axial 25%","Equal 50% and 50%","Axial 80% with peripheral 5%",exp="Peripheral (25%) greater than axial pattern (10%)."),
 q(538,"recall","Which features define axial enteropathic arthritis on this page?","Presentation similar to ankylosing spondylitis with HLA B27 in 50%, symmetric sacroiliitis, no correlation to bowel activity, no enthesitis or dactylitis","Asymmetric sacroiliitis with dactylitis as the rule","Strict correlation with bowel flares","Exclusive DIP involvement",exp="Axial arthritis: presentation similar to ankylosing spondylitis; HLA B-27 association in 50% cases; symmetric sacroiliitis; no correlation to bowel activity; no enthesitis, dactylitis."),
 q(538,"recall","In the peripheral arthritis table, which associations belong to Type 1 LMAP arthritis?","Episcleritis, erythema nodosum and arthritis, with flares correlating with bowel disease and more common occurrence","Uveitis with no correlation and less common occurrence","Isolated dactylitis without bowel link","Sacroiliitis without peripheral joints",exp="Type 1 LMAP arthritis: more common; flares correlate with bowel disease; associated factors episcleritis, erythema nodosum, arthritis — versus Type 2 SMAP-u: less common, no correlation, uveitis."),
]),
("LMAP versus SMAP-u, stool markers and psoriatic arthritis basics",
 "LMAP versus SMAP-u, stool markers and psoriatic arthritis basics",
 "The arthritis-pattern table contrasts large-joint self-limited disease with aggressive small-joint polyarthritis needing anti-TNF. Stool calprotectin/lactoferrin note transitions to psoriatic arthritis epidemiology and HLA links. The 60/30/30 rule with 90% nail changes and systemic manifestations stay source-ordered.", [
 q(539,"recall","Which pattern description belongs to Type 1 LMAP arthritis?","Large joint (knee predominant), migratory, asymmetric, pauciarticular with lower limb greater than upper limb","Small joint MCP, aggressive chronic symmetric polyarticular","Strictly axial with no peripheral joints","DIP-predominant with pencil-in-cup only",exp="Type 1 LMAP arthritis row: large joint (knee predominant), migratory, asymmetric, pauciarticular arthritis (lower limb greater than upper limb)."),
 q(539,"management","Which treatment and prognosis pair is printed for Type 1 LMAP arthritis?","Self-limiting with good prognosis","Anti-TNF alpha (infliximab) as drug of choice","Chronic steroid dependence","Joint replacement at diagnosis",exp="Type 1 treatment/prognosis: self-limiting, good prognosis."),
 q(539,"recall","Which pattern belongs to Type 2 SMAP-u arthritis?","Small joint (MCP), migratory, aggressive chronic, symmetrical polyarticular arthritis","Large-joint monoarthritis that is self-limited","Isolated enthesitis without synovitis","Non-inflammatory osteoarthritis only",exp="Type 2 SMAP-u arthritis: small joint (MCP), migratory, aggressive, chronic, symmetrical, polyarticular arthritis."),
 q(539,"management","What is the printed drug of choice for Type 2 SMAP-u arthritis?","Anti-TNF alpha — infliximab","Hydroxychloroquine alone","Colchicine for bowel flares","Indomethacin as monotherapy only",exp="Type 2 treatment: anti TNF alpha — DOC, infliximab."),
 q(539,"recall","Which stool markers are printed for monitoring bowel flares?","Calprotectin and lactoferrin","Occult blood alone as the sole marker","Fecal calcuria","Stool pH only",exp="Note: calprotectin, lactoferrin in stools for bowel flare."),
 q(539,"numeric","What proportion of psoriatic cases develops arthritis, and which psoriasis type is linked?","7%–40% with plaque-type psoriasis","1%–2% with guttate only","Over 90% with pustular only","0% with erythrodermic",exp="Psoriatic arthritis: 7%–40% of psoriatic cases develop arthritis; plaque type psoriasis."),
 q(539,"numeric","What age, sex ratio and HLA associations are printed for psoriatic arthritis?","Age over 40, M:F 1:1, HLA CW-06 02 and HLA B27 for arthritis","Age under 20 with HLA DR4 only","Female predominance 9:1 with B27 negative","No HLA association",exp="Age greater than 40 yrs; M:F = 1:1; HLA CW-06 02, HLA B27 (arthritis)."),
 q(539,"numeric","How does the 60/30/30 rule distribute psoriasis–arthritis order, and what nail percentage is bracketed?","60% psoriasis then arthritis; 20% both together; 20% arthritis then psoriasis; nail changes in 90%","50/30/20 with nail changes in 50%","70/20/10 with nail changes in 20%","All present simultaneously in 100%",exp="60/30/30 rule: 60% psoriasis → arthritis, 20% psoriasis + arthritis, 20% arthritis → psoriasis, plus nail changes in 90%."),
 q(539,"recall","Which clinical manifestation cluster is printed for psoriatic arthritis?","Synovitis, dactylitis, enthesitis and axial involvement of the cervical spine","Isolated DIP osteoarthritis without inflammation","Tophi with hyperuricemia","Only axial disease without dactylitis",exp="Clinical manifestation: synovitis + dactylitis + enthesitis + axial involvement (cervical spine)."),
 q(539,"recall","Which joint morphology and mucocutaneous statement are printed?","Thick, non-marginal, asymmetric arthritis with no mucocutaneous involvement at the articular assessment","Thin marginal symmetrical syndesmophytes with obligatory rash","Punched-out erosions with pathognomonic nail loss only","Pure cartilage loss without bone change",exp="Thick, non-marginal, asymmetric arthritis; no mucocutaneous involvement is listed in the manifestation block."),
 q(539,"recall","Which cardiac, renal and ocular extras complete the psoriatic arthritis list?","Aortic regurgitation with conduction block; secondary IgA nephropathy; bilateral chronic posterior uveitis","Mitral prolapse with interstitial nephritis and anterior uveitis","Heart failure with amyloidosis only","No ocular or renal associations",exp="CVS: aortic regurgitation, conduction block; renal: 2° IgA nephropathy; B/L chronic posterior uveitis."),
]),
("Psoriasis variants, nail signs and Wright–Moll classification",
 "Psoriasis variants, nail signs and Wright–Moll classification",
 "Guttate/erythrodermic forms are separated from arthritis while pustular disease is most destructive. Five nail photographs with oil-drop sign as classical map the 90% nail-change rule. Wright–Moll five patterns including arthritis mutilans close the unit in printed order.", [
 q(540,"oddoneout","Which psoriasis forms are annotated as not associated with arthritis?","Guttate psoriasis and erythrodermis psoriasis","Plaque psoriasis and psoriatic arthritis","Pustular psoriasis","Nail psoriasis with arthritis",exp="The captions guttate psoriasis and erythrodermis psoriasis carry the note not associated with arthritis."),
 q(540,"scenario","Pustular psoriasis with destructive joint disease prompts which printed instruction?","Rule out HIV; it is the most destructive arthritis pattern","Start allopurinol immediately","Assume HLA B27 negative disease","Withhold all systemic therapy",exp="Pustular psoriasis: most destructive arthritis; rule out HIV."),
 q(540,"numeric","What percentage of psoriatic patients has nail changes, and what yellow-margin pattern is printed?","90% with longitudinal yellow nail margin","20% with isolated onycholysis only","5% with no colour change","100% with complete nail loss at onset",exp="Nail changes (90%): yellow nail margin (longitudinal)."),
 q(540,"recall","Which four nail photographs are labeled on this page?","Deep and coarse nail pitting; onycholysis with subungual hyperkeratosis; oil drop sign (classical); longitudinal ridging","Spoon nails, Beau lines only","Leukonychia and koilonychia","Onychomycosis and paronychia",exp="Nail panels: deep and coarse nail pitting; onycholysis with subungual hyperkeratosis; oil drop sign (classical); longitudinal ridging."),
 q(540,"recall","Which nail sign is explicitly called classical?","Oil drop sign","Pitting alone","Onycholysis alone","Longitudinal ridging alone",exp="The oil drop sign panel is annotated classical."),
 q(540,"recall","Which pattern is the most common type in the Wright and Moll classification?","Symmetric polyarthritis with DIP involvement, skin lesions and nail changes, differentially RA in small joints","Arthritis mutilans","Axial spondyloarthritis alone","Isolated dactylitis",exp="Wright and Moll: symmetric polyarthritis (m/c type) — involvement of DIP, skin lesion, nail changes; D/d RA (involvement of small joints)."),
 q(540,"recall","Which remaining Wright–Moll patterns are printed?","Asymmetrical oligoarthritis; predominant DIP arthritis; predominant spondyloarthritis (axial 5%, cervical predominance); arthritis mutilans with complete destruction","Only mutilans and axial forms","Guttate and pustular rows","DISH and CPPD rows",exp="Classification continues with asymmetrical oligoarthritis, predominant DIP arthritis, predominant spondyloarthritis (axial pattern 5%, cervical predominance) and arthritis mutilans: complete destruction."),
 q(540,"numeric","What axial percentage and region predominance are printed for the spondyloarthritis pattern of psoriatic arthritis?","Axial pattern 5% with cervical predominance","Axial pattern 50% with lumbar predominance","Axial 100% with no region preference","Axial involvement is excluded",exp="Predominant spondyloarthritis: axial pattern (5%), cervical predominance."),
]),
("Psoriatic versus rheumatoid features, progression and hand radiographs",
 "Psoriatic versus rheumatoid features, progression and hand radiographs",
 "Mutilans, dactylitis and corn-foot images open the unit. The eight-row PsA-versus-RA comparison table and rapid bony ankylosis with CASPER follow. Ivory phalanx and thin vertical symmetrical syndesmophytes close the page.", [
 q(541,"recall","Which three clinical images are captioned on this page?","Arthritis mutilans, dactylitis and corn foot","Gouty tophi, chalky deposit and bursitis","Heberden nodes, Bouchard nodes and swan neck","Septic joint, erysipelas and cellulitis",exp="Image captions: arthritis mutilans; dactylitis; corn foot."),
 q(541,"recall","In the PsA versus RA table, how is psoriasis scored in each column?","Psoriatic arthritis plus; rheumatoid arthritis minus","Both positive equally","RA positive, PsA negative","Neither column scores it",exp="Difference table row Psoriasis: psoriatic arthritis +, rheumatoid arthritis −."),
 q(541,"oddoneout","Which row favors rheumatoid arthritis rather than psoriatic arthritis in the printed table?","Symmetric disease scored ++ in RA versus + in PsA","Asymmetry scored ++ in PsA","Enthesopathy present only in PsA","Nail dystrophy present only in PsA",exp="Symmetric: RA ++ greater than PsA +, while asymmetric, enthesopathy, dactylitis, nail dystrophy and HIV association favor PsA."),
 q(541,"oddoneout","Which features are printed as present in psoriatic arthritis but absent in rheumatoid arthritis?","Enthesopathy, dactylitis, nail dystrophy and HIV association","Symmetric polyarticular involvement","Rheumatoid nodules","Erosions with preserved joint space",exp="Table rows enthesopathy, dactylitis, nail dystrophy and HIV association are + for PsA and − for RA."),
 q(541,"recall","What progression statement and classification criteria are printed for psoriatic arthritis?","Rapid progression to bony ankylosis with CASPER criteria and no diagnostic testing","Slow progression with ACR 1987 as the only criteria","No bony change with mandatory serology","Joint fusion excluded by definition",exp="Progression: rapid progression to bony ankylosis; CASPER criteria; no diagnostic testing."),
 q(541,"recall","What does the ivory phalanx radiograph represent in this chapter?","A psoriatic hand finding shown beside the progression notes","A gouty tophus with rat-bite erosions","A septic arthritis with osteomyelitis only","A DISH flowing-wax spine",exp="The page pairs an ivory phalanx hand film with the progression and CASPER notes for psoriatic arthritis."),
 q(541,"recall","How are syndesmophytes defined in the AP vertebral diagram on this page?","Thin, vertical and symmetrical","Thick, coarse and asymmetrical only","Lateral and non-marginal only","Absent in psoriatic disease",exp="Syndesmophytes: thin, vertical and symmetrical in the AP illustration."),
]),
("Psoriatic spinal and hand radiographic signs plus systemic therapy",
 "Psoriatic spinal and hand radiographic signs plus systemic therapy",
 "Paravertebral ossification and non-marginal syndesmophytes contrast with axial AS morphology. Pencil-in-cup, whiskering, telescoping and the 100% ray pattern define PsA hands. The seven-drug ladder from anti-TNF to tofacitinib closes Chapter 27 in printed order.", [
 q(542,"recall","How is paravertebral ossification characterized and which diseases are listed?","Large, coarse and asymmetrical; seen in Reiter's syndrome and psoriatic arthropathy","Thin and marginal only in ankylosing spondylitis","Restricted to DISH alone","Excluded from seronegative spondyloarthropathies",exp="Paravertebral ossification: large, coarse, asymmetrical; seen in Reiter's syndrome and psoriatic arthropathy; the film is captioned non-marginal syndesmophyte."),
 q(542,"recall","What is the pencil-in-cup deformity shown on the hand film and diagram?","Tapered proximal phalanx fitting a widened distal articular cup","A normal joint-space measurement","A gouty overhanging edge lesion","A fracture-dislocation pattern",exp="Pencil-in-cup deformity is illustrated radiographically and schematically versus a normal phalanx."),
 q(542,"recall","How is whiskering defined in the source?","Marginal erosion with adjacent bone proliferation","Sclerosis of the vertebral corner only","Soft-tissue swelling without erosion","Punched-out lesion with sclerotic rim only",exp="Whiskering: marginal erosion with adjacent bone proliferation."),
 q(542,"recall","What two additional hand signs are listed with whiskering?","Telescoping of digits and ray pattern erosion of MCP, PIP and DIP in the same finger (100% psoriatic x-ray)","Heberden nodes and swan-neck deformity only","Tophi and rat-bite erosions","Nail pitting alone without bone change",exp="Telescoping of digits; ray pattern — erosion of MCP, PIP, DIP in same finger; 100% psoriatic X-ray."),
 q(542,"management","Which full medication list is printed for psoriatic arthritis?","Anti-TNF alpha drugs, apremilast (PDE4 inhibitor), methotrexate, leflunomide, ustekinumab, secukinumab and tofacitinib","Colchicine and allopurinol only","Sulfasalazine monotherapy without biologics","Warfarin and NSAIDs only",exp="Treatment lists anti TNF alpha drugs, apremilast (PDE 4 inhibitor), methotrexate, leflunomide, ustekinumab, secukinumab and tofacitinib."),
 q(542,"recall","Which mechanism label is attached to apremilast in the printed ladder?","PDE4 inhibitor","JAK1-selective inhibitor only","IL-17A neutralizer only","Xanthine oxidase inhibitor",exp="Apremilast is annotated PDE 4 inhibitor."),
]),
])

ch28 = make_chapter(28, "Crystal Arthropathies", "543-551", [
("Crystal types, inflammasome pathogenesis and uric-acid metabolism",
 "Crystal types, inflammasome pathogenesis and uric-acid metabolism",
 "Four crystal classes and the inflammasome→IL-1β axis open the chapter. MSUM presentations and the purine-to-uric-acid pathway with absent uricase follow in printed order. AMP/GMP branches and xanthine oxidase positions are retained exactly.", [
 q(543,"recall","Which four crystal types are listed at the start of the chapter?","Monosodium urate monohydrate (MSUM), CPPD, basic calcium phosphate (hydroxyapatite) and calcium oxalate","Cholesterol, cystine, bilirubin and protein crystals only","Uric acid, calcium carbonate, magnesium and phosphate","Drug crystals, immunoglobulin, lipid and mucin",exp="Types: 1. monosodium urate monohydrate (msum); 2. calcium pyrophosphate dihydrate (CPPD); 3. basic calcium phosphate (BCP) — calcium hydroxy apatite; 4. calcium oxalate."),
 q(543,"recall","How is basic calcium phosphate specified chemically on this page?","Calcium hydroxy apatite Ca5(PO4)3OH","Calcium pyrophosphate dihydrate","Monosodium urate dihydrate","Calcium oxalate monohydrate only",exp="BCP is written as calcium hydroxy apatite Ca5(PO4)3OH."),
 q(543,"recall","Which pathogenesis label and pathway open the crystal arthropathy block?","Autoinflammatory syndrome with activation of the inflammasomal pathway converting pro-IL1β to IL-1β","Pure mechanical wear without inflammation","Complement-mediated type III reaction only","Antibody-mediated cytopenia",exp="Pathogenesis: autoinflammatory syndrome; activation of inflammasomal pathway; inflammasomes are innate-immunity intracellular protein complexes containing caspases that convert Pro-IL1β to IL-1β."),
 q(543,"recall","Which definition of inflammasomes is printed?","Innate immunity intracellular protein complex containing caspases","Extracellular antibody aggregate","Mitochondrial electron-transport complex","Nuclear transcription factor only",exp="Parenthetical note: inflammasomes — innate immunity, intracellular protein complex containing caspases."),
 q(543,"recall","Which three presentations are listed for monosodium urate monohydrate disease?","Asymptomatic hyperuricemia, renal manifestations and gouty arthritis","Only tophaceous gout and calculi","Acute urate nephropathy alone","Pseudogout and chondrocalcinosis",exp="MSUM presentations: asymptomatic hyperuricemia, renal manifestations, gouty arthritis."),
 q(543,"recall","What is the printed dietary/endogenous source of uric acid?","Purines — adenine and guanine","Exogenous oxalate only","Cholesterol esters","Branched-chain amino acids alone",exp="URIC ACID source: purines (adenine, guanine)."),
 q(543,"recall","Which enzyme converts hypoxanthine and xanthine toward uric acid in the printed pathway?","Xanthine oxidase","Uricase","Adenosine deaminase","Alcohol dehydrogenase",exp="The metabolism diagram places xanthine oxidase on the hypoxanthine→xanthine→uric acid steps."),
 q(543,"recall","What does the printed note about uricase state for humans?","Uricase converts uric acid to allantoin, which is not present in humans, so uric acid is not metabolised","Humans express uricase abundantly","Allantoin is the main human end-product","Uricase is renal only",exp="Note: uric acid —uricase→ allantoin (not present in humans → uric acid not metabolised)."),
 q(543,"recall","In the AMP arm of the printed pathway, which enzyme acts between adenosine and inosine?","Adenosine deaminase","Xanthine oxidase","Uricase","PRPP synthase",exp="AMP → adenosine —(adenosine deaminase)→ inosine → hypoxanthine → xanthine → uric acid."),
]),
("Purine pools, stone thresholds and the four-compartment renal model",
 "Purine pools, stone thresholds and the four-compartment renal model",
 "Dietary and endogenous purines feed a 1.2 g uric-acid pool with intestinal and renal excretion. Stone risk thresholds and the 100/50/40/10 tubular model follow. Net 90% reabsorption, PCT-only handling and FEUA in RTA close the unit.", [
 q(544,"numeric","What uric-acid pool size and daily excretion splits are printed on the purine diagram?","Pool 1.2 g; intestine 0.2 g/day and kidney 0.5 g/day with overall excretion 0.7 g/day","Pool 5 g with renal excretion only 0.05 g","Pool 0.2 g with faecal loss 2 g","No defined pool with 3 g daily loss",exp="Diagram: uric acid pool 1.2 g; intestine (0.2 g/day); kidney (0.5 g/day); excretion (0.7 g/day)."),
 q(544,"numeric","What excretion rate is labelled to produce uricosuria?","Greater than 7 mg/kg/d","Greater than 2 mg/kg/d only","Greater than 20 mg/kg/d","Less than 1 mg/kg/d",exp="Excretion greater than 7 mg/kg/d → uricosuria."),
 q(544,"numeric","Which three stone-formation thresholds and components are tabulated?","Uric acid greater than 7 mg/kg/d (hyperuricosuria); calcium greater than 4 (hypercalciuria, most common); citrate less than 11 (hypocitraturia)","Uric acid over 3 only; calcium over 8; citrate over 20","All stones above 10 mg/kg/d","No numeric thresholds are printed",exp="Important causes of stone formation: >7 uric acid — hyperuricosuria; >4 calcium — hypercalciuria (m/c); <11 citrate — hypocitraturia."),
 q(544,"numeric","Which component is most common for stone formation in the printed table?","Calcium (hypercalciuria)","Uric acid","Citrate","Oxalate only",exp="The calcium row is annotated m/c for stone formation."),
 q(544,"numeric","What mnemonic numbers summarize the four-compartment model of renal uric-acid handling?","100 / 50 / 40 / 10","50 / 25 / 10 / 5","90 / 90 / 10 / 10","100 / 100 / 100 / 100",exp="4 compartment model: 100 / 50 / 40 / 10."),
 q(544,"recall","What handling steps map to the four compartments?","100% filtered in glomerulus; 100% reabsorbed at S1; 50% secreted at S2; 40% reabsorbed at S3; 10% excreted in urine","Only filtration with no reabsorption","Secretion exclusively at S3","Excretion before filtration",exp="Model: 100% filtered in glomerulus; 100% reabsorbed at S1; 50% secreted at S2; 40% reabsorbed at S3; 10% excreted in urine."),
 q(544,"numeric","What net reabsorption percentage of filtered uric acid is printed?","90%","10%","50%","0%",exp="Net reabsorption of 90% of filtered uric acid."),
 q(544,"recall","Where do uric acid and phosphorus metabolism take place according to the source?","Only in the proximal convoluted tubule","Entirely in the loop of Henle","Collecting duct exclusively","Glomerulus only",exp="Uric acid and phosphorus metabolism takes place only in PCT."),
 q(544,"numeric","How does fractional excretion of uric acid and phosphorus change in proximal versus distal RTA?","Raised in proximal RTA; normal in distal RTA","Normal in proximal; raised in distal","Low in both","High only in distal",exp="Fractional excretion of uric acid and phosphorus: increased in proximal RTA; normal in distal RTA."),
]),
("Asymptomatic hyperuricemia: thresholds, genetics and drug causes",
 "Asymptomatic hyperuricemia: thresholds, genetics and drug causes",
 "Metabolic-syndrome link and sex-specific thresholds open the unit. Pregnancy-age nephron pathway and the genetic enzyme table with Lesch-Nyhan/von Gierke follow. CANT LEAP drugs and progression to chronic tophaceous gout close the page.", [
 q(545,"recall","How is hyperuricemia framed relative to metabolic syndrome in the source?","Hyperuricemia is a part of metabolic syndrome","It excludes metabolic syndrome","It is only renal","It is exclusively genetic",exp="Asymptomatic hyperuricemia: hyperuricemia is a part of metabolic syndrome."),
 q(545,"numeric","What sex-specific diagnostic levels are printed for hyperuricemia?","Greater than 6 mg/dl in females and greater than 7 mg/dl in males","Equal to 5 mg/dl for both sexes","Greater than 10 mg/dl for both","Less than 4 mg/dl for both",exp="Levels: greater than 6 mg/dl in females, greater than 7 mg/dl in males."),
 q(545,"recall","What pregnancy-age pathway to adult metabolic syndrome is diagrammed?","Increasing maternal age → small-for-gestational-age babies → pre-eclampsia → decreased nephron number → adult metabolic syndrome","Younger age → macrosomia → no nephron effect","Post-term only with normal nephrons","No proposed pathway",exp="Age at pregnancy flow: ↑age → small for gestational age babies → pre-eclampsia → ↓nephron number → metabolic syndrome as adults."),
 q(545,"numeric","What is the majority genetic split printed for unidentified hyperuricemia causes?","90% under-excretion and 10% over-production of urate","90% over-production and 10% under-excretion","Equal 50/50","100% over-production",exp="Unidentified (majority): 90% under-excretion, 10% over-production of urate."),
 q(545,"recall","Which syndrome results from HGPRTase deficiency with its printed features?","Lesch-Nyhan syndrome with hyperuricemia, self-mutilation and mental retardation","von Gierke disease with hepatomegaly only","Classic galactosemia","Wilson disease with kayser-fleischer rings",exp="HGPRTase deficiency → Lesch Nyhan syndrome: hyperuricemia, self-mutilation, mental retardation."),
 q(545,"recall","Which enzyme defect and clinical cluster define von Gierke disease on this page?","Glucose-6-phosphatase deficiency (glycogen storage disease type 1) with hepatomegaly, hyperlipidemia, hyperuricemia, doll facies, hypoglycemia and seizures","Fructose-1-phosphate aldolase deficiency alone","PRPP synthase overactivity only","HGPRTase deficiency",exp="Glucose 6 phosphatase deficiency → von Gierke's disease / glycogen storage disease type 1 with hepatomegaly, hyperlipidemia, hyperuricemia, doll facies, hypoglycemia and seizures."),
 q(545,"recall","Which two remaining genetic defects are listed without disease names in the table?","Fructose-1-phosphate aldolase deficiency and PRPP synthase overactivity","Uricase deficiency and xanthinuria","Cystinuria and Hartnup disease","Wilson and hemochromatosis",exp="Table rows: fructose 1 phosphate aldolase deficiency; phosphoribosyl pyrophosphate (PRPP) synthase overactivity."),
 q(545,"recall","Which drug list is encoded by the printed CANT LEAP mnemonic?","Cyclosporine, alcohol, nicotine, thiazides, loop diuretics, ethambutol, low-dose aspirin and pyrazinamide","Penicillamine, amiodarone, nitrofurantoin, ketamine, loop blockers, estrogen, ACE inhibitors, prednisolone","Only antivirals and statins","No drugs are implicated",exp="Secondary drug-induced hyperuricemia mnemonic CANT LEAP: cyclosporine, alcohol, nicotine, thiazide diuretics, loop diuretics, ethambutol, aspirin low dose, pyrazinamide."),
 q(545,"scenario","Prolonged asymptomatic hyperuricemia with recurrent flares evolves as the printed progression shows toward what end state?","Chronic tophaceous gout after multiple acute episodes","Spontaneous complete resolution","Isolated kidney stones only without arthritis","CPPD pseudogout",exp="Progression: prolonged asymptomatic hyperuricemia → increased risk of acute gout with multiple episodes → chronic tophaceous gout."),
]),
("Hyperuricemia modifiers, renal manifestations and acute gouty arthritis",
 "Hyperuricemia modifiers, renal manifestations and acute gouty arthritis",
 "Kelley threshold and modifiable factors precede the three renal outcomes. Acute gout demographics, King Henry label, first-attack features and four-stage table follow. Hot-red-dusky signs and 3–14-day duration are retained as printed.", [
 q(546,"numeric","What serum urate threshold is attributed to Kelley's textbook?","Greater than 6.8 mg/dl","Exactly 4.0 mg/dl","Over 12 mg/dl always","Under 5 mg/dl",exp="Note: greater than 6.8 mg/dl (Kelley's textbook)."),
 q(546,"oddoneout","Which listed factor does NOT belong among the printed modifiers of urate level?","Platelet count","Age with increasing gout tendency","Blood pressure and alcohol","Diet of seafood and red meat plus serum creatinine",exp="Factors affecting: age, blood pressure, alcohol, diet (sea food, red meat), Sr. creatinine — platelet count is not listed."),
 q(546,"numeric","When is serum urate said to rise in men and women, and what pregnancy state is noted?","Men at puberty; women at menopause; pregnancy is a hyperuricemic state","Men at menopause; women at puberty; pregnancy is normouricemic","Both sexes only after age 80","No sex-specific change",exp="Sr. urate increases in men at puberty, women at menopause; pregnancy is a hyperuricemic state."),
 q(546,"recall","Which three renal manifestations with pathogenesis are tabulated?","Uric acid nephropathy (TLS precipitation → AKI); urate nephropathy (prolonged hyperuricemia → CTID → CKD); urolithiasis (excretion greater than 7 mg/kg/day → stones)","Isolated hematuria and proteinuria only","Renal amyloidosis alone","Renal artery stenosis only",exp="Renal manifestations table: uric acid nephropathy via TLS precipitation in tubules → AKI; urate nephropathy via chronic tubulo-interstitial disease → CKD; urolithiasis when excretion exceeds 7 mg/kg/day."),
 q(546,"scenario","Tumour lysis syndrome causes urate precipitation in tubules with acute kidney injury. Which renal label applies?","Uric acid nephropathy","Chronic urate nephropathy (CTID)","Pure urolithiasis without AKI","IgA nephropathy",exp="Uric acid nephropathy pathogenesis: tumour lysis syndrome → precipitation of uric acid in tubules → AKI."),
 q(546,"numeric","What sex and age pattern is printed for acute gouty arthritis?","Male 80% greater than female (post-menopausal); age 40–60 years","Female predominance under 30","Equal ratio over 70","Children only",exp="Acute gouty arthritis: sex M (80%) greater than F (post-menopausal); age 40–60 yrs."),
 q(546,"recall","Which trigger and historical label are printed for acute gout?","Alcohol as most common trigger; disease of King due to presentation in King Henry","Seafood-only trigger; disease of Queen","Trauma only; disease of philosophers","No trigger; no historical label",exp="Trigger: alcohol (m/c); AKA disease of King (d/t presentation in King Henry)."),
 q(546,"numeric","What percentage of first attacks involves the first MTP joint, and what is uric-acid status in 40%?","85% first MTP; uric acid normal or low in 40%","50% knee with always-high urate","10% wrist only","0% MTP involvement",exp="First attack: 1st MTP joint (85%); uric acid normal or low in 40%."),
 q(546,"numeric","What percentage has polyarticular first attacks, and which associations are printed?","15% with myeloproliferative neoplasm and post-transplant association","40% with RA only","5% with gout-negative labs","90% with isolated knee disease",exp="15% have polyarticular involvement, associated with myeloproliferative neoplasm and post transplantation."),
 q(546,"numeric","What duration and joint signs are printed for the first acute attack?","3–14 days with hot, red, dusky swollen joint and periarticular erythema; pain peaks 4–12 hours","Single day with cold joint","Over 3 months continuously","Painless swelling only",exp="Duration 3–14 days; signs hot, red, dusky, swollen joint plus periarticular erythema; max intensity of pain 4–12 hrs."),
 q(546,"recall","Which four stages appear in the printed staging table?","High uric acid levels, acute gout, intercritical gout and chronic gout","Prodrome, flare, tophus and surgery only","Latent, primary, secondary and tertiary","No staging system is printed",exp="Staging: 1. high uric acid levels; 2. acute gout; 3. intercritical gout; 4. chronic gout with frequent pain and tophi formation."),
]),
("Subsequent attacks, synovial-fluid distinction and polarized-light proof",
 "Subsequent attacks, synovial-fluid distinction and polarized-light proof",
 "Ankle/knee/wrist subsequent attacks and symptom-free baseline notes lead investigations. Crystal versus septic synovial table with WBC cut-offs follows. Needle-shaped strong negative birefringence parallel to the light ray closes the unit.", [
 q(547,"recall","Which joints and course describe subsequent gout attacks?","Ankle, knee or wrist involvement with a variable course","First MTP only every time with fixed course","Shoulder exclusively","No subsequent attacks occur",exp="Subsequent attacks: involvement of ankle / knee / wrist; variable course."),
 q(547,"oddoneout","Which condition is listed with gout as having a symptom-free baseline?","Palindromic rheumatology (palindromic rheumatism)","Rheumatoid arthritis with continuous synovitis","Osteoarthritis with constant pain","Sepsis always symptomatic",exp="Symptom-free baseline seen in gout and palindromic rheumatology."),
 q(547,"oddoneout","Which pair is printed as causes of acute monoarticular arthritis?","Gout and septic arthritis","RA and SLE","OA and fibromyalgia","GCA and PMR",exp="Acute monoarticular arthritis seen in gout and septic arthritis."),
 q(547,"numeric","What WBC counts separate crystal arthritis from septic arthritis in the printed table?","Crystal 10,000–50,000 cells/ml; septic greater than 50,000","Crystal under 1,000; septic 2,000","Both always above 100,000","Equal counts in both",exp="Cytology table: WBC crystal arthritis 10,000–50,000; septic arthritis greater than 50,000."),
 q(547,"recall","How do focus of infection, culture/gram stain and other features differ in the table?","Crystal: no focus, negative culture/gram stain, presence of crystals; septic: focus positive, culture positive, immunosuppression plus","Both have positive cultures","Crystal has immunosuppression; septic has crystals","No differences are listed",exp="Table rows: focus of infection − versus +; culture and gram stain negative versus positive; other features — presence of crystals versus immunosuppression +."),
 q(547,"recall","What crystal morphology and birefringence are printed for gout on polarized light?","Needle-shaped crystals with strong negative birefringence","Rhomboid crystals with weak positive birefringence","Rectangular strongly positive crystals","Round non-birefringent bodies",exp="Polarized light microscopy: needle shaped crystals with strong negative birefringence."),
 q(547,"recall","What orientation note is printed for gout crystals under polarizing microscopy?","Needle-shaped crystals are kept parallel to the light ray","Crystals must be perpendicular only","No orientation is needed","Crystals dissolve before viewing",exp="Note polarising light microscopy: needle-shaped crystals kept parallel to light ray."),
]),
("Acute gout treatment, ACR criteria, intercritical course and chronic imaging",
 "Acute gout treatment, ACR criteria, intercritical course and chronic imaging",
 "First-line indomethacin, colchicine regimen and intra-articular steroids lead. Second-line anakinra, ACTH and pegloticase plus ACR triad follow. Intercritical 60% relapse, martel/rat-bite x-ray and knee ultrasound signs close the unit.", [
 q(548,"management","Which first-line agents are printed for acute gout?","Indomethacin 50 mg TDS, colchicine with its staged regimen, and intra-articular steroids","Allopurinol alone at presentation","Long-term warfarin","Methotrexate as sole therapy",exp="First line: NSAIDs indomethacin 50 mg TDS; colchicine; intra-articular steroids."),
 q(548,"recall","How does the printed colchicine regimen act and what schedule is given?","Prevents neutrophil migration and chemotaxis; 1.2 mg stat → 0.6 mg after 1 hr → 0.6 mg BD × 1 week → 0.6 mg OD × 3–6 months","Blocks xanthine oxidase with single 5 mg dose","Uricosuric once weekly only","No scheduled regimen printed",exp="Colchicine: prevents neutrophil migration & chemotaxis; 1.2 mg stat → 0.6 mg after 1 hr → 0.6 mg BD × 1 week → 0.6 mg OD × 3–6 months."),
 q(548,"management","Which second-line trio is printed for gout flares?","Anakinra (anti IL-1), single-dose IM ACTH injection, and IV pegloticase (recombinant uricase)","Methotrexate, leflunomide and sulfasalazine","Colchicine plus probenecid only","Prednisolone plus allopurinol only",exp="Second line: anakinra anti IL-1; IM ACTH injection (single dose); IV pegloticase (recombinant uricase)."),
 q(548,"recall","Which three items form the printed ACR criteria of gout?","Acute monoarticular arthritis, hyperuricemia and dramatic response to colchicine","Only elevated ESR and RF positivity","Joint stiffness over one hour with malar rash","Tophi plus classically normal urate",exp="ACR criteria of gout: acute monoarticular arthritis; hyperuricemia; dramatic response to colchicine."),
 q(548,"numeric","What relapse percentage and ongoing deposition note define the intercritical period?","60% second flare within a year with continued tophaceous deposition and erosion","100% never relapse with no deposition","0% relapse","Only 5% flare",exp="Intercritical period: symptom-free period, classical feature of crystal arthropathy; 60% second flare within a year; continued deposition of tophaceous gout and erosion."),
 q(548,"recall","Which chronic-gout x-ray features are printed?","Asymmetric punched-out lytic lesions with overhanging edges (martel/G sign), sclerotic rat-bite erosions and maintained joint space","Symmetrical narrow joint space only","Pure osteopenia without lesions","Subchondral sclerosis alone",exp="Chronic gout x-ray: asymmetric, punched out lytic, overhanging edges — martel sign / G sign; sclerotic margins — rat bite erosions; joint space maintained."),
 q(548,"recall","Which three structures are labeled on the knee ultrasound image?","Uric acid crystals, hypoechoic hyaline cartilage and femoral cortex","Meniscus, ACL and bursa only","Effusion, synovium and cyst only","No labeled structures",exp="Ultrasound of knee labels uric acid crystals, hypoechoic hyaline cartilage and femoral cortex."),
]),
("Tophi, xanthine-oxidase inhibitors, uricosurics and uricases",
 "Tophi, xanthine-oxidase inhibitors, uricosurics and uricases",
 "Tophus morphology, acute-on-chronic flares and preferred sites open the unit. Febuxostat/allopurinol with HLA-B5801 hypersensitivity lead the hypouricemics. Uricosuric list, recombinant uricases and 12-year natural history close Chapter 28's gout therapy.", [
 q(549,"recall","How are tophi defined on this page?","Irregular asymmetric moderately discrete tumescence of fingers due to subcutaneous MSUM crystal deposition, painless, sometimes with acute-on-chronic surrounding inflammation","Symmetrical warm nodules that are always painful","Intracellular lipid deposits","Calcium oxalate cones only",exp="Tophi: irregular asymmetric moderately discrete tumescence of fingers d/t s/c deposition of msum crystals; painless; acute on chronic — acute inflammation surrounding tophi."),
 q(549,"numeric","Which tophus site is marked most common, and what other sites are listed?","Olecranon most common; also prepatellar bursa, ulnar surface, Achilles surface, myocardium and heart valves","First MTP only","Knee joint capsule only","Sacrum exclusively",exp="Sites: olecranon (m/c), prepatellar bursa, ulnar surface, Achilles surface, myocardium, heart valves."),
 q(549,"management","Which xanthine-oxidase inhibitors and key toxicities are printed?","Febuxostat with cardiotoxicity; allopurinol 300 mg daily with HLA-B5801 hypersensitivity, hairfall, liver and renal disease","Methotrexate with hepatotoxicity only","Colchicine as a xanthine oxidase blocker","Warfarin with bleeding risk",exp="Xanthine oxidase inhibitors: febuxostat (s/e cardiotoxicity); allopurinol 300 mg daily (s/e hypersensitivity in HLA B58-01 susceptibility, hairfall, liver and renal disease)."),
 q(549,"numeric","What allopurinol daily dose and hypersensitivity gene are printed?","300 mg daily with HLA-B5801 susceptibility","100 mg daily with HLA-B27","50 mg twice weekly with HLA-DR4","No fixed dose and no HLA link",exp="Allopurinol 300 mg daily; s/e hypersensitivity in HLA B58-01 susceptibility."),
 q(549,"recall","Which agents are listed as uricosurics that enhance uric-acid excretion?","Probenecid, sulfinpyrazone, benzbromarone, losartan (noted ACE inhibitor) and lesinurad","Allopurinol and febuxostat only","Colchicine and indomethacin only","Rasburicase and pegloticase",exp="Uricosuric agents: probenecid, sulfinpyrazone, benzbromarone, losartan (ACE inhibitor), lesinurad."),
 q(549,"management","Which recombinant uricases are printed and where else are they used?","Rasburicase and pegloticase, also used in acute gout and tumour lysis syndrome","Uricase supplements as daily prophylaxis","Only pegloticase for chronic joints","Allopurinol listed as a uricase",exp="Recombinant uricase: rasburicase, pegloticase — also used in acute gout and TLS."),
 q(549,"numeric","What interval between first attack and chronic gout is printed, and what drives tophus rate?","12 years between first attack and chronic gout; tophus formation rate correlates with degree and duration of hyperuricemia","2 years with no correlation","20 years only","Rate independent of urate level",exp="Features: 12 yrs between first attack and chronic gout; rate of tophus formation correlates with degree and duration of hyperuricemia."),
]),
("CPPD presentations, associations and the basic crystal remainder",
 "CPPD presentations, associations and the basic crystal remainder",
 "Elderly ANKH-linked CPPD opens with chondrocalcinosis and pseudo-gout features. Pseudo-RA, hook osteophytes, crowned dens and association list follow. BCP Milwaukee/CREST material and calcium-oxalate transplant note close Chapter 28.", [
 q(550,"recall","Which demographic, symptom and gene notes open the CPPD section?","Elderly, often asymptomatic and non-inflammatory, gene ANKH","Children with inflammatory monoarthritis and ANKH normal","Middle-aged with mandatory fever","No genetic association printed",exp="CPPD: age elderly; asymptomatic; non-inflammatory; gene ANKH."),
 q(550,"recall","How is chondrocalcinosis defined as the first CPPD presentation?","Asymptomatic calcification of articular cartilage, predominantly of the knee","Painful erosion of the hip only","Soft-tissue mass without calcification","Septic arthritis equivalent",exp="1. Chondrocalcinosis: asymptomatic; calcification of articular cartilage; predominantly knee."),
 q(550,"scenario","Acute monoarticular CPPD arthritis with bloody aspiration, no hematogenous focus and no response to antibiotics or colchicine shows rhomboid weak-positive crystals. Which diagnosis?","Pseudo-gout (CPPD acute arthritis)","Crystal-proven gout","Classic septic arthritis","Rheumatoid flare",exp="Acute monoarticular CPPD: bloody aspiration; no hematogenous source of foci; no response to antibiotics and colchicine; rhomboid crystals with weak positive birefringence; pseudo-gout."),
 q(550,"recall","What morphology and birefringence are printed for CPPD crystals?","Rhomboid crystals with weak positive birefringence","Needle crystals with strong negative birefringence","Pyramidal strongly positive crystals","Non-birefringent spheres",exp="Rhomboid crystals with weak positive birefringence."),
 q(550,"recall","How is the chronic inflammatory CPPD polyarthritis pattern described?","Waxing and waning, non-erosive, pseudo-RA","Rapidly erosive like classic RA","Pure mechanical OA","Always monoarticular",exp="3. Chronic inflammatory polyarthritis: waxing & waning progression; non-erosive; pseudo RA."),
 q(550,"recall","What MCP/wrist pattern with hook-like osteophytes is printed, and which disease is linked?","Second and third MCP with wrist hook-like osteophytes seen in hemochromatosis; pseudo-OA","First CMC only with no link","DIP nodes with Wilson disease","No osteophytes in CPPD",exp="4. Involvement of MCP (2nd, 3rd), wrist: hook like osteophytes (seen in hemochromatosis); pseudo-OA."),
 q(550,"recall","Which late presentations round out the CPPD list?","Pseudo-neuropathic disease like Charcot; spondyloarthritis with crowned dens syndrome (dens in atlas); septic arthritis usually knee with fever","Only chondrocalcinosis","Gouty tophi only","Isolated calcinosis cutis",exp="5. Pseudo neuropathic disease presents like Charcot's; 6. spondyloarthritis — crowned dens syndrome (dens in atlas); 7. septic arthritis (m/c knee): fever."),
 q(550,"oddoneout","Which condition is printed as a CPPD association rather than a non-association?","Hypomagnesemia as seen in Gitelman syndrome","Normal calcium with normal PTH","Familial Mediterranean fever","Primary hyperoxaluria",exp="Associations: hyperparathyroidism; hypophosphatasia (d/d of rickets with ↓ alkaline phosphatase); hypomagnesemia (seen in Gitelman syndrome); hemochromatosis."),
 q(551,"recall","What crystal class and optical property define basic calcium phosphate?","Hydroxyapatite deposition that is non-birefringent","CPPD crystals that are weakly positive","MSUM needles that are strongly negative","Oxalate pyramids strongly positive",exp="Basic calcium phosphate: deposition of calcium hydroxyapatite crystals; non-birefringent."),
 q(551,"recall","Which three BCP presentations are printed?","Chronic calcific periarthritis most common in supraspinatus tendon; Milwaukee shoulder with rotator-cuff arthropathy and glenohumeral destruction; calcinosis cutis","Only Milwaukee shoulder","Gouty tophi only","Pseudo-gout alone",exp="Presentations: chronic calcific periarthritis m/c supraspinatus tendon; Milwaukee shoulder — rotator cuff arthropathy + glenohumeral destruction; calcinosis cutis."),
 q(551,"recall","Which diseases are listed under calcinosis cutis?","CREST syndrome and juvenile dermatomyositis (lipodystrophy, myofascial involvement)","SLE and scleroderma only","Gout and CPPD","RA and OA",exp="Calcinosis cutis seen in CREST syndrome and juvenile dermatomyositis (lipodystrophy, myofascial involvement)."),
 q(551,"recall","What shape and birefringence are printed for calcium oxalate crystals, and what type-system is given?","Pyramidal envelope-shaped crystals with strong positive birefringence; primary in hyperoxaluria, secondary in CKD","Needles with strong negative birefringence","Rhomboids weakly positive","Non-birefringent plates",exp="Calcium oxalate: strong positive birefringence; pyramidal, envelope shaped crystals; primary — hyperoxaluria, secondary — CKD."),
 q(551,"management","What treatment note is printed for hyperoxaluria?","Combined kidney and liver transplantation","Colchicine alone","Allopurinol monotherapy","No transplant needed",exp="Note: mx of hyperoxaluria → combined kidney & liver transplantation."),
]),
])

ch29 = make_chapter(29, "Adult-Onset Still's Disease and Septic Arthritis", "552-554", [
("Adult-onset Still's disease phenotype, triad and Yamaguchi major criteria",
 "Adult-onset Still's disease phenotype, triad and Yamaguchi major criteria",
 "Age, systemic presentation and sore-throat prodrome open the chapter. The fever–salmon-rash–polyarthritis triad with destructive 25% risk and poor-prognosis signs follow. Blood parameters and Yamaguchi major items are kept in printed order.", [
 q(552,"numeric","What age band and form of presentation are printed for adult-onset Still's disease?","25–45 years with systemic form of presentation","Under 15 years with articular only","Over 70 with localized joints","No defined age with skin-limited disease",exp="Adult Onset Still's Disease: age 25–45 yrs; systemic form of presentation."),
 q(552,"recall","What prodromal phase feature is printed for AOSD?","Sore throat","Headache only","Dysuria","No prodrome",exp="Features: prodromal phase — sore throat."),
 q(552,"recall","How is the fever component of the clinical triad described?","Persistent high spiking fever that reaches subnormal levels during the day (quotidian pattern)","Continuous low-grade fever only","Night sweats without spikes","No fever in classic triad",exp="Clinical triad: fever — persistent high spiking reaches subnormal levels during day (quotidian)."),
 q(552,"recall","What rash morphology and behavior are printed in the triad?","Salmon-colored transient evanescent maculopapular rash","Fixed hyperpigmented plaques","Palpable purpura on legs","Ichthyosis only",exp="Salmon colored rash: transient evanescent maculo papular rash."),
 q(552,"numeric","What arthritis distribution and site order are printed for AOSD?","Symmetric polyarticular with knee greater than wrist greater than ankle greater than elbow","Asymmetric oligoarthritis of DIP only","Monoarticular hip only","Axial spine only",exp="Arthritis: symmetric, polyarticular (knee greater than wrist greater than ankle greater than elbow)."),
 q(552,"numeric","What percentage progresses to severe or destructive arthritis, and where are erosions most common?","25% severe/destructive arthritis; joint erosions most common in children","5% severe with adult-only erosions","90% severe","No progression risk printed",exp="Progress to severe/destructive arthritis in 25% of cases; joint erosions m/c in children."),
 q(552,"oddoneout","Which cluster is labelled bad prognosis in AOSD?","Serositis, lymphadenopathy and hepatosplenomegaly","Sore throat and salmon rash alone","Isolated arthralgia","Quotidian fever without organomegaly",exp="Serositis, lymphadenopathy and hepatosplenomegaly are bracketed as bad prognosis."),
 q(552,"recall","Which blood parameters are printed for AOSD?","Leukocytosis, raised ESR, raised CRP, raised ferritin and low serum albumin","Pancytopenia with low ESR","Normal white count with high albumin","Thrombocytosis with low CRP",exp="Blood parameters: leukocytosis; ESR increased; CRP increased; ferritin increased; S. albumin decreased."),
 q(552,"numeric","What score threshold and four major criteria items are printed for Yamaguchi criteria?","Greater than 5; fever over 39°C for 7 days, arthritis/arthralgia for 2 weeks, rash and leukocytosis","Greater than 3 with sore throat only","Exactly 2 with negative labs","Greater than 10 including organomegaly as major",exp="Yamaguchi criteria (greater than 5): major — fever (>39°C) for 7 days; arthritis/arthralgia for 2 weeks; rash; leukocytosis."),
]),
("Yamaguchi minor criteria, HLH, AOSD therapy and septic-arthritis foundations",
 "Yamaguchi minor criteria, HLH, AOSD therapy and septic-arthritis foundations",
 "Minor criteria and lab abnormalities finish Yamaguchi. HLH as 10% rheumatologic emergency with cytopenia and coagulation features follows. NSAID→steroid/MTX→anti-IL ladder, sulfasalazine avoidance and septic hosts/causes close the unit.", [
 q(553,"recall","Which items are printed as Yamaguchi minor criteria?","Sore throat; negative ANA and RF; hepatosplenomegaly with lymphadenopathy; abnormal ALT/AST","Fever over 39°C for 7 days","Rash with leukocytosis","Arthritis for 2 weeks",exp="minor: sore throat; negative ANA, RF; hepatosplenomegaly, lymphadenopathy; abnormal ALT/AST."),
 q(553,"recall","How is hemophagocytic lymphohistiocytosis introduced relative to AOSD?","Rheumatological emergency seen in 10% of AOSD","Universal late complication","Skin-limited finding","Never associated with AOSD",exp="HLH: rheumatological emergency; seen in 10% of AOSD."),
 q(553,"recall","Which feature set with directions is printed for HLH?","Pancytopenia, unsubsiding fever, very high ferritin, low ESR, low fibrinogen and high triglycerides","High ESR with high fibrinogen","Normocellular marrow with low TG","Thrombocytosis with high fibrinogen",exp="Features: pancytopenia; ESR decreased; unsubsiding fever; fibrinogen decreased; ferritin increased increased; triglycerides increased."),
 q(553,"recall","Which complications follow the HLH block?","Bleeding from thrombocytopenia, transient thrombocytopenic purpura, DIC with consumptive coagulopathy and AA amyloidosis","Isolated hepatomegaly only","No coagulopathy","Pure skin vasculitis only",exp="Complications: bleeding d/t thrombocytopenia; transient thrombocytopenic purpura; DIC with consumptive coagulopathy; AA amyloidosis."),
 q(553,"management","How is steroid therapy sequenced in AOSD according to the printed note?","Pulse therapy then oral therapy","Oral therapy only without pulse","No steroids","Topical steroids only",exp="Treatment: steroid — pulse therapy then oral therapy."),
 q(553,"management","What is the printed step-up ladder for AOSD treatment?","Mild: NSAID; no response → steroid plus methotrexate; then anti IL-1 and IL-6","Methotrexate first with no NSAID step","Colchicine only","Sulfasalazine first line",exp="Treatment of AOSD: mild — NSAID; no response → steroid + methotrexate → anti IL-1, IL-6."),
 q(553,"oddoneout","Which drug is explicitly avoided in AOSD?","Sulfasalazine","Methotrexate after NSAID failure","Anakinra (anti IL-1)","NSAIDs in mild disease",exp="Note: sulfasalazine is avoided."),
 q(553,"recall","Which hosts are listed as susceptible to acute monoarticular septic arthritis?","Children, elderly, immunocompromised and IV drug abusers (oligo/polyarticular)","Only healthy young athletes","Pregnant women exclusively","Adults with hyperuricemia only",exp="Susceptible host: children, elderly; immunocompromised; IV drug abuse (oligo/polyarticular)."),
 q(553,"recall","What clinical presentation is printed for septic arthritis?","Fever, pain with limited range of motion (most common knee) and no history of similar episodes","Painless swelling only","Migratory polyarthralgia only","Quotidian salmon rash",exp="Clinical presentation: fever; pain + limited range of motion (m/c: knee); no h/o similar episode."),
 q(553,"recall","What infection percentage, organism hierarchy and spread route are printed?","Infection 20%: Staphylococcus aureus greater than Streptococcus pneumoniae greater than Gram-negative bacillus; spread hematogenous","50% viral with lymphatic spread","100% Gram-negative only","No organisms listed",exp="Causes: infection (20%) — staph. aureus greater than strep. pneumonia greater than gram-negative bacillus; spread: hematogenous."),
 q(553,"oddoneout","Which non-infectious causes are listed among acute monoarticular arthritis mimics?","Trauma, tumour, osteoarthritis of a single joint and sarcoidosis","Chlamydia and Shigella only","Crystal deposition with sterile cultures only","Quotidian fever alone",exp="Other causes: trauma; tumour; osteoarthritis of single joint; sarcoidosis."),
]),
("Gonococcal versus septic comparison, septic-arthritis management and arthritis approach",
 "Gonococcal versus septic comparison, septic-arthritis management and arthritis approach",
 "Tendinitis/bursitis and hemophilia d/d plus the gonococcal–septic table open the final unit. Synovial-fluid gold standard, WBC threshold and antibiotic/drainage rules follow. Chronic monoarticular causes and the mono-versus-poly approach tree close Chapter 29.", [
 q(554,"oddoneout","Which differentials are first printed to be ruled out before labeling monoarticular arthritis as septic?","Tendinitis and bursitis; hemophilia as a similar presentation","Gout and CPPD only","RA and SLE","GCA and PMR",exp="D/d: tendinitis, bursitis to be ruled out; hemophilia — similar presentation."),
 q(554,"recall","In the gonococcal versus septic table, which host and pattern row is correct?","Gonococcal: young healthy with migratory polyarthralgia/arthritis; septic: immunocompromised with monoarticular arthritis","Both occur only in healthy athletes","Gonococcal monoarticular; septic migratory","Both immunocompromised with rash",exp="Table: host — gonococcal young healthy versus septic immunocompromised; pattern — migratory polyarthralgia/arthritis versus monoarticular arthritis."),
 q(554,"oddoneout","Which feature favors gonococcal infection over septic arthritis in the printed table?","Tenosynovitis and skin rash present; good prognosis with lower joint/blood culture yield","Monoarticular presentation without rash","Higher culture yield and poor prognosis","Immunocompromised host",exp="Tenosynovitis + and skin rash + favor gonococcal, with less culture yield and good prognosis versus septic negative for both, more yield and poor prognosis."),
 q(554,"numeric","What is the gold-standard diagnostic test and WBC threshold printed for septic arthritis?","Synovial fluid analysis with WBC greater than 50,000 per microlitre","Serum RF with 10,000 cells","Plain x-ray alone with normal WBC","Blood culture only with 1,000 cells",exp="Diagnosis: synovial fluid analysis — gold standard; WBC greater than 50000 /μL."),
 q(554,"management","Which antibiotic pair and drainage indications are printed for septic arthritis?","Vancomycin plus ceftriaxone; drain for thick pus or shoulder/hip involvement","Colchicine plus allopurinol only","No antibiotics with aspiration alone always","NSAIDs alone without drainage",exp="Rx: antibiotics — vancomycin + ceftriaxone; drainage indications — thick pus; shoulder, hip joint involvement."),
 q(554,"recall","Which causes of chronic monoarticular arthritis are listed?","TB, fungal disease, Lyme disease, sarcoidosis, spondyloarthritis and non-inflammatory causes","Only crystal arthritis","RA and SLE exclusively","Gout and septic arthritis only",exp="Chronic monoarticular arthritis causes: TB; fungal disease; Lyme; sarcoidosis; spondyloarthritis; non-inflammatory."),
 q(554,"recall","How does the printed approach tree first split arthritis?","Monoarticular arthritis versus polyarticular arthritis","Acute versus chronic only","Inflammatory versus non-inflammatory only","Upper versus lower limb",exp="Approach to arthritis begins with monoarticular arthritis and polyarticular arthritis branches."),
 q(554,"recall","What sub-branches follow monoarticular and polyarticular arthritis in the flowchart?","Monoarticular → septic and crystal; polyarticular → acute (undifferentiated, post-viral) and chronic inflammatory (RA with d/d SLE, psoriatic arthritis)","Monoarticular → septic only; polyarticular → OA only","Acute tree under monoarticular only","No further branches printed",exp="Monoarticular branches septic and crystal; polyarticular branches acute (undifferentiated, post viral) and chronic inflammatory: RA with d/d SLE and psoriatic arthritis."),
]),
])


if __name__ == "__main__":
    write(ch27)
    write(ch28)
    write(ch29)
