#!/usr/bin/env python3
"""Author the audited, source-ordered learning sets for Chapters 33-38.

The source pages are scanned (uploads/03.pdf PDF5-40 = Book p566-601). Every
prompt below was authored after reading the printed page top-to-bottom at a
2x PyMuPDF render - headings, bullets, sub-bullets, notes, table cells,
flowchart arms, diagrams, thresholds, scores, criteria and doses. Printed
p586, p590 and p591 are absent from the supplied scan (verified by corner
number reads); each carries one transparently-flagged bridge question,
following the Chapter 26 p527 precedent. `data/chNN.json` is the app source
of truth.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data"


def make_chapter(number, title, page_range, unit_specs):
    questions = []
    units = []
    for unit_no, (section, unit_title, guide, rows) in enumerate(unit_specs, 1):
        ids = []
        for page, fmt, stem, correct, distractors, explanation in rows:
            qid = f"MED-C{number}-{len(questions)+1:02d}"
            # Rotate answer position while retaining hand-authored plausible
            # distractors. The displayed app randomises these again.
            choices = [correct, *distractors]
            shift = (len(questions) * 3 + number) % 4
            choices = choices[shift:] + choices[:shift]
            questions.append({
                "id": qid, "sec": section, "page": page, "fmt": fmt,
                "q": stem, "opts": choices, "ans": choices.index(correct),
                "exp": explanation + f" (Book p{page})",
            })
            ids.append(qid)
        units.append({
            "id": f"MED-U{number}-{unit_no}", "ch": number, "n": unit_no,
            "title": f"{unit_no}. {unit_title}", "sec": section,
            "guide": guide, "qs": ids,
        })
    return {"chapter": number, "title": title, "pageRange": page_range,
            "questions": questions, "units": units}


def q(page, fmt, stem, correct, *distractors, exp):
    assert len(distractors) == 3, (stem, distractors)
    return (page, fmt, stem, correct, list(distractors), exp)


def write(chapter):
    path = OUT / f"ch{chapter['chapter']:02d}.json"
    path.write_text(json.dumps(chapter, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{path.name}: {len(chapter['questions'])} questions / {len(chapter['units'])} units")


# ---------------------------------------------------------------- Chapter 33
ch33 = make_chapter(33, "Language V/S Speech", "566-568", [
("Language vs Speech & the Auditory Pathway", "Language vs Speech & the Auditory Pathway",
 "Language is the dominant-hemisphere concept of communication; speech is its motor output.\nThe perisylvian auditory-pathway diagram assigns functions to Broca's (44,45), Wernicke's (22) and the connecting fibres.\nProsody and the brainstem-to-muscle output close the first diagram.", [
 q(566,"recall","The book defines language as which of the following?","The basic concept of communication, a dominant-hemisphere function","The motor output of language","Emotional intonation of speech","Processing of sound in area 22",exp="Language is defined as the basic concept of communication and is a dominant-hemisphere function; its abnormality is aphasia."),
 q(566,"recall","Speech, per the opening definition, is which, and its abnormality is which?","Motor output of language, whose abnormality is dysarthria","Comprehension of words, abnormality aphasia","Emotional intonation, abnormality paraphasia","Written communication, abnormality alexia",exp="Speech is the motor output of language; its abnormality is dysarthria, whereas the abnormality of language is aphasia."),
 q(566,"scenario","In the auditory-pathway diagram, prosody (emotional intonation of language) is attributed to which hemisphere?","The non-dominant hemisphere","The dominant hemisphere at Broca's area","The dominant hemisphere at Wernicke's area","Area 17 of either hemisphere",exp="The diagram marks prosody - emotional intonation of language - as a non-dominant hemisphere function."),
 q(566,"scenario","A lesion severs the connecting fibres between the primary auditory area and Wernicke's area. Which deficit does the diagram label this as?","Pure word deafness","Auditory agnosia","Pure alexia","Global aphasia",exp="The auditory-pathway diagram labels connecting-fibre abnormality as pure word deafness; the peripheral muscles (larynx vocal cords, pharynx palate, oesophagus) are driven below the brainstem nuclei."),
 q(566,"recall","Which pairing of the speech areas' functions is printed in the perisylvian diagram?","Broca's (44,45): grammar, syntax, rhythm, fluency; Wernicke's (22): processing sound, comprehension","Broca's (44,45): comprehension; Wernicke's (22): fluency","Broca's (22): syntax; Wernicke's (44,45): prosody","Broca's (44,45): prosody; Wernicke's (22): grammar",exp="Broca's speech area (44,45) carries grammar, syntax, rhythm and fluency while Wernicke's area (22) processes sound and comprehension; the companion Areas-of-Brain diagram labels the perisylvian region, premotor, primary motor, supplementary motor, Rolandic fissure, primary sensory, supramarginal and arcuate gyri, Sylvian fissure and primary auditory area."),
 q(566,"recall","Below the brainstem nuclei, the pathway diagram lists which peripheral effectors of speech?","Larynx (vocal cords), pharynx (palate) and oesophagus","Diaphragm, intercostals and abdominal muscles","Tongue, soft palate and neck flexors only","Pharynx, larynx and diaphragm",exp="The diagram's final line lists the peripheral muscles: larynx (vocal cords), pharynx (palate) and oesophagus."),
]),
("Aphasia Lesion Map & Flowchart", "Aphasia Lesion Map & Flowchart",
 "Three note lines map fibre/lesion sites to auditory agnosia, pure word deafness and pure alexia.\nThe lesion-site table assigns fluency, comprehension, repetition and naming to sulcal regions.\nMotor (non-fluent DESP) and sensory (fluent jargon) aphasia open the comprehension/repetition flowchart.", [
 q(567,"recall","The note lines on this page pair which lesion with which deficit?","Auditory association fibres -> auditory agnosia; connecting fibres -> pure word deafness; fusiform gyrus -> pure alexia","Auditory association fibres -> pure alexia; fusiform gyrus -> pure word deafness","Connecting fibres -> auditory agnosia; fusiform gyrus -> global aphasia","Fusiform gyrus -> auditory agnosia; connecting fibres -> transcortical aphasia",exp="Notes: auditory association fibres abnormality -> auditory agnosia; connecting fibres abnormality -> pure word deafness; lesion in fusiform gyrus -> pure alexia."),
 q(567,"scenario","Per the lesion-site table, a lesion anterior to the central sulcus impairs which function?","Fluency","Comprehension","Repetition","Naming",exp="Lesion/disease table: anterior to central sulcus -> fluency; posterior to central sulcus -> comprehension; in and around Sylvian fissure -> repetition; dominant lobe -> naming. Prosody of speech is d/t non-dominant lobe disease."),
 q(567,"scenario","In the aphasia flowchart, a patient has preserved comprehension and preserved repetition. Which aphasia is reached, and its stated cause?","Transcortical motor aphasia, d/t watershed infarct (MCA, PCA)","Conduction aphasia, d/t arcuate fasciculus lesion","Isolation aphasia, with echolalia","Broca's aphasia, d/t frontal infarct",exp="Preserved comprehension with preserved repetition leads to transcortical motor aphasia (d/t watershed infarct MCA, PCA); impaired repetition in that branch gives Broca's aphasia."),
 q(567,"recall","The flowchart's Broca's aphasia arm lists which cluster?","Agrammatic (telegraphic) speech, poor reading/writing, associated weakness, good comprehension","Jargon speech, neologisms, logorrhoea, paraphasia","Echolalia with intact comprehension and repetition","Loud reading, writing formed with errors, no weakness",exp="Broca's aphasia in the flowchart: agrammatic (telegraphic), poor reading/writing, associated sign weakness and good comprehension; motor aphasia overall is non-fluent speech: DESP (dysarthria, effortful, sparse with reduced word output, prosody lost, naming impaired)."),
 q(567,"scenario","Sensory aphasia is described as fluent speech with which features?","Jargon speech (pen -> hen), neologisms, logorrhoea, impaired naming (paraphasia)","Non-fluent, effortful, sparse speech with prosody lost","Echolalia with preserved repetition","Slow scanning staccato output",exp="Sensory aphasia: fluent speech with jargon substitution (eg pen -> hen), neologisms (create new words), logorrhoea (increased word output) and naming impaired (paraphasia)."),
]),
("Aphasia Flowchart Continued", "Aphasia Flowchart Continued",
 "The four remaining flowchart arms are read from comprehension x repetition.\nWernicke's arm carries its associated signs and the parietal quadrantanopia note.", [
 q(568,"scenario","Comprehension preserved but repetition impaired in the flowchart gives which aphasia and lesion?","Conduction aphasia, lesion of the arcuate fasciculus","Anomic aphasia, lesion of the angular gyrus","Transcortical sensory aphasia, d/t infarct","Wernicke's aphasia, d/t infarct",exp="Preserved comprehension with impaired repetition = conduction aphasia (arcuate fasciculus lesion); preserved repetition in that branch = anomic aphasia (angular gyrus lesion); impaired comprehension with preserved repetition = transcortical sensory aphasia (d/t infarct)."),
 q(568,"scenario","Comprehension impaired and repetition impaired in the flowchart: which aphasia, with which associated sign?","Wernicke's aphasia, with superior quadrantanopia and no weakness","Global aphasia, with bilateral weakness","Transcortical sensory aphasia, with echolalia","Isolation aphasia, with preserved comprehension",exp="Impaired comprehension with impaired repetition = Wernicke's aphasia (d/t infarct; reading loud, writing formed with errors, preservation poor, associated sign superior quadrantanopia, no weakness)."),
 q(568,"recall","Which statement is printed as the note beneath the flowchart?","Lesion of parietal lobe: inferior quadrantanopia","Lesion of parietal lobe: superior quadrantanopia","Lesion of occipital lobe: inferior quadrantanopia","Lesion of frontal lobe: quadrantanopia",exp="Note beneath the flowchart: lesion of parietal lobe -> inferior quadrantanopia (the Wernicke's arm separately lists superior quadrantanopia)."),
]),
("Dysarthria", "Dysarthria",
 "Four dysarthria types are listed by their anatomical level.\nCorticobulbar UMN disease maps to the spastic (pseudo-bulbar) type.", [
 q(568,"oddoneout","Pick the ODD ONE OUT - the dysarthria type NOT listed in the book's four types:","Muscular dystrophy dysarthria","Cortical (in Broca's aphasia)","Pseudo-bulbar (spastic dysarthria)","Bulbar (flaccid dysarthria)",exp="The four printed types: cortical (in Broca's aphasia), pseudo-bulbar/spastic (corticobulbar fibres abnormality), bulbar/flaccid (LMN - brain stem nuclei and below; test sounds produced from lip, tongue and oropharynx) and cerebellar (slow scanning staccato speech)."),
 q(568,"scenario","A corticobulbar (UMN, cortex to anterior horn cell) abnormality produces which dysarthria per the types list?","Pseudo-bulbar (spastic) dysarthria","Bulbar (flaccid) dysarthria","Cerebellar staccato dysarthria","Cortical dysarthria of Broca's aphasia",exp="Pseudo-bulbar (spastic) dysarthria = corticobulbar fibres abnormality (UMN -> cortex to anterior horn cell); bulbar (flaccid) is LMN at brain stem nuclei and below."),
]),
])

# ---------------------------------------------------------------- Chapter 34
ch34 = make_chapter(34, "Memory", "569-571", [
("Processes & Classification", "Processes & Classification",
 "Three processes (encoding, consolidation, retrieval) precede the old duration table.\nThe current classification splits explicit vs implicit memory, with episodic/semantic branches.", [
 q(569,"recall","The three processes of memory per the page are:","Encoding (registration), consolidation (storage), retrieval","Encoding, decay, reconsolidation","Attention, storage, rehearsal","Registration, priming, conditioning",exp="Processes of memory: encoding (registration), consolidation (storage) and retrieval."),
 q(569,"scenario","Per the old duration table, which store has NO storage and is exemplified by recalling a phone number within 1 minute?","Immediate (working memory)","Short term/recent (hippocampus, recalling breakfast)","Long term (neocortex, distant past)","Episodic (hippocampus, time and context)",exp="Duration table: immediate/working memory = no storage, e.g. recalling a phone number within 1 min; short term/recent = hippocampus storage, e.g. recalling breakfast; long term = neocortex, e.g. recalling something from distant past."),
 q(569,"recall","Which structure does the duration table name as the storage site for short-term/recent memory?","Hippocampus (medial temporal lobe)","Neocortex","Prefrontal cortex","Basal ganglia",exp="Storage row: immediate = no storage; short term/recent = hippocampus (medial temporal lobe); long term = neocortex - and retrieval in all three columns is the prefrontal cortex."),
 q(569,"recall","The current classification splits memory by mode of retrieval into which two branches?","Explicit (declarative) and implicit (non-declarative)","Immediate and long term","Procedural and semantic","Anterograde and retrograde",exp="Mode of retrieval (current classifications): explicit (declarative) - episodic and semantic - and implicit (non-declaratives): procedural, priming, associative (conditional), non associative."),
 q(569,"scenario","Episodic memory per the flowchart is based on time and context (autobiographical), is hippocampal, and is affected early in which disease?","Alzheimer's disease","Frontotemporal dementia","Parkinson's disease","Vascular dementia",exp="Episodic: based on time and context (autobiographical), area hippocampus, affected early in Alzheimer's disease; semantic: based on facts, association areas, rarely affected in late Alzheimer's disease."),
 q(569,"oddoneout","Pick the ODD ONE OUT - the type NOT listed under implicit (non-declarative) memory:","Episodic","Procedural","Priming","Associative (conditional)",exp="Implicit (non-declaratives) listed: procedural, priming, associative (conditional) and non associative; episodic belongs to explicit (declarative) memory."),
]),
("Implicit Memory & Anatomy", "Implicit Memory & Anatomy",
 "The implicit-memory table pairs each type with its areas and characteristics.\nThe cortex and sub-cortex anatomy tables then assign memory types to lobes and nuclei.", [
 q(570,"scenario","Per the implicit-memory table, procedural memory (e.g. driving) uses which areas?","Basal ganglia, supplementary motor area and cerebellum","Neo cortex alone","Amygdala and reflex pathway","Hippocampus and entorhinal cortex",exp="Procedural: basal ganglia, supplementary motor area, cerebellum (e.g. driving); priming: neo cortex (remembering facts d/t exposure, duration or intensity); associative (conditional): amygdala (not seen in humans - animals associating fear to lion and environment); non-associative: reflex pathway (habitual response)."),
 q(570,"scenario","An animal's fear-association response to a predator in its environment is mapped in the table to which area?","Amygdala (associative/conditional memory)","Neo cortex (priming)","Cerebellum (procedural)","Reflex pathway (non-associative)",exp="Associative (conditional) memory: amygdala; characteristics - not seen in humans; animals associating fear to lion and environment."),
 q(570,"scenario","Per the cortex anatomy table, which lobe's area stores semantic memory?","Parietal - association area (parieto-occipital)","Frontal - prefrontal cortex (all types)","Temporal - hippocampus (episodic semantic)","Occipital - hippocampus (semantic)",exp="Cortex table: frontal (prefrontal cortex, all types), parietal (association area parieto-occipital, semantic), temporal (hippocampus, episodic semantic), occipital (area '-', semantic)."),
 q(570,"recall","Which subcortical area is labelled the 'gateway of memory' storing long-term memory?","Entorhinal cortex","Amygdala (conditional)","Cerebellum (procedural)","Basal ganglia (procedural)",exp="Sub-cortex table: amygdala -> conditional; cerebellum -> procedural; entorhinal cortex -> long term memory (gateway of memory); basal ganglia -> procedural. The zones-of-brain medial diagram follows."),
]),
("Papez Circuit", "Papez Circuit",
 "The mammillo-thalamic circuit is traced station by station.\nThe mammillary body carries the Wernicke-Korsakoff annotation; the entorhinal cortex closes the loop.", [
 q(571,"recall","The Papez circuit is also known as what, and which station is annotated with Wernicke-Korsakoff syndromes?","Mamillo-thalamic circuit; the mammillary body","Dorsal-median circuit; the thalamus","Mamillo-thalamic circuit; the subiculum","Cingulate loop; the fornix",exp="Papez circuit aka mammillo-thalamic circuit: hippocampus/subiculum -> fornix -> mammillary body (Wernicke-Korsakoff syndromes) -> mammillo-thalamic tract -> thalamus -> internal capsule -> cingulate gyrus -> parahippocampal gyrus -> entorhinal cortex (gateway of memory) -> back to hippocampus."),
 q(571,"recall","In the Papez circuit, which station is the 'gateway of memory' that closes the loop back to the hippocampus?","Entorhinal cortex","Mammillary body","Cingulate gyrus","Fornix",exp="The circuit closes via the parahippocampal gyrus into the entorhinal cortex, labelled gateway of memory, which returns to the hippocampus/subiculum."),
]),
])

# ---------------------------------------------------------------- Chapter 35
ch35 = make_chapter(35, "Dementia : Part 1", "572-576", [
("Definition, Domains & Causes", "Definition, Domains & Causes",
 "ADL splits and the minor/major cognitive-impairment divide set up the dementia definition.\nThe six cognitive domains map to their cortical areas; four causes follow with the PFC functions note.", [
 q(572,"recall","Activities of daily living per the page split into which two groups?","Basic (self-care related) and instrumental (handling own phone, money, etc.)","Motor and sensory","Overt and covert","Voluntary and automatic",exp="ADL: basic = self-care related; instrumental = handling own phone, money, etc. Cognitive impairment: minor = ADL unaffected; major = ADL affected."),
 q(572,"numeric","The book's dementia definition: major cognitive impairment plus how many of the 6 cognitive domains affected?","At least 1 (>=1) out of 6","At least 2 out of 6","At least 3 out of 6","All 6",exp="Definition as printed: major cognitive impairment + >=1 out of 6 cognitive domains affected."),
 q(572,"scenario","The language domain in the 6-domain table maps to which areas?","Inferior frontal gyrus (Broca's) and superior temporal gyrus (Wernicke's)","Hippocampus (median temporal lobe)","Prefrontal cortex","Superior parietal lobule",exp="Domain table: episodic memory -> hippocampus (median temporal lobe); language -> inferior frontal gyrus (Broca's) + superior temporal gyrus (Wernicke's); complex attention, executive function and social cognition -> prefrontal cortex; perceptual motor (praxicons) -> superior parietal lobule."),
 q(572,"recall","The four causes of dementia listed on this page are:","Alzheimer's disease (m/c), diffuse Lewy body dementia, vascular dementia, normal pressure hydrocephalus","Alzheimer's, FTD, prion, Huntington's","AD, vascular, NPH, Creutzfeldt-Jakob","DLB, PSP, MSA, Binswanger",exp="Causes: 1. Alzheimer's disease (m/c); 2. diffuse Lewy body (DLB) dementia; 3. vascular dementia (branches: post-stroke, multi-infarct dementia, white matter dementia/Binswanger disease); 4. normal pressure hydrocephalus (NPH)."),
 q(572,"recall","Based on the parts of brain affected, the subcortical-dementia list includes:","DLB dementia, progressive supranuclear palsy, Binswanger disease, NPH","Alzheimer's, FTD, CJD, Binswanger","AD, DLB, vascular, NPH","PSP, MSA, CBD, cortical basal",exp="Dementia -> cortical; subcortical -> diffuse Lewy body (DLB) dementia, progressive supranuclear palsy, Binswanger disease, NPH."),
 q(572,"recall","The PFC-functions note assigns which function to the orbital PFC?","Behaviour","Executive function (dorsolateral PFC)","Energisation and motivation (medial PFC)","Episodic memory (medial PFC)",exp="Note - functions of PFC: dorsolateral PFC executive function; medial PFC energisation and motivation; orbital PFC behaviour."),
]),
("Reversible Causes & Onset Patterns", "Reversible Causes & Onset Patterns",
 "The DENTANTIA-style reversible list is read letter by letter with the B12 and NPH notes.\nYoung-onset and rapidly-progressive lists bracket the pathology note that opens Alzheimer's.", [
 q(573,"scenario","A reversible-cause workup lists benzodiazepines, tricyclic antidepressants and lithium under which mnemonic letter?","D - Drugs","M - Metabolic","E - Endocrine","A - Anemia",exp="Reversible causes: D drugs (benzodiazepines, tricyclic antidepressants, lithium); E endocrine (hypothyroidism: metabolic slowing); M metabolic (vit B12 deficiency); E chronic infections of ear; N normal pressure hydrocephalus; T trauma, tumors; I infections (chronic meningitis); A anemia, autoimmune encephalitis."),
 q(573,"scenario","Peripheral neuropathy plus dementia plus subacute combined cord degeneration points to which reversible cause?","Vitamin B12 deficiency","Hypothyroidism","Chronic otologic infection","Autoimmune encephalitis",exp="Note: vit B12 deficiency -> peripheral neuropathy, dementia and subacute combined cord degeneration; Rx of NPH: surgery."),
 q(573,"recall","The treatment of NPH stated in the reversible-causes note is:","Surgery","Acetazolamide","Repeated lumbar puncture","Cholinesterase inhibitors",exp="Note under reversible causes: Rx of NPH - surgery."),
 q(573,"oddoneout","Pick the ODD ONE OUT - the condition NOT listed under young-onset dementia:","Alzheimer's disease","Frontotemporal dementia (Pick's disease), the m/c","Huntington's disease","DLB dementia",exp="Young onset dementia: frontotemporal dementia (Pick's disease) m/c, prion disease, Huntington's disease, DLB dementia."),
 q(573,"recall","Among rapidly progressive dementias, which two are bracketed as non-degenerative?","HIV and Whipple's disease","FTD (Pick's) and prion","DLB and tumors","Prion and FTD (Pick's)",exp="Rapidly progressive: FTD (Pick's) m/c, prion, DLB, HIV and Whipple's (bracketed non-degenerative), tumors (based on location)."),
 q(573,"recall","The pathology note says entorhinal cortex atrophy is specific for which disease?","Alzheimer's disease","Frontotemporal dementia","Vascular dementia","Normal ageing",exp="Atrophy of: entorhinal cortex - specific for Alzheimer's; dentate nucleus - occurs with ageing. Alzheimer's disease: m/c cause of dementia; most important risk factor age; sporadic."),
 q(573,"numeric","The book prints what chance of Alzheimer's for age >85 years?","40%","20%","60%","80%",exp="Most important risk factor: age (>85 years: 40% chance of Alzheimer's)."),
]),
("Alzheimer's Pathogenesis", "Alzheimer's Pathogenesis",
 "The APP pathway diverges at A-beta 40/42 into CAA and tauopathy.\nBrain diabetes, the MRI atrophy list and the cholinergic DOC follow in printed order.", [
 q(574,"scenario","In the APP pathway, abnormal kinetics with metabolism by which enzyme produces A-beta amyloid (beta-pleated sheets)?","Beta-secretase","Alpha-secretase (normal metabolism)","Gamma-secretase alone","Insulin degrading enzyme",exp="APP (amyloid precursor protein, gene on chr 21) with abnormal kinetics is metabolised by beta-secretase producing A-beta amyloid (beta-pleated sheets); note: normal metabolism uses alpha-secretase."),
 q(574,"scenario","A-beta 40 and A-beta 42 diverge in the pathway: which outcome pairs with A-beta 40?","Cerebral amyloid angiopathy with microhemorrhages in brain","Alzheimer's disease with tauopathy","Hirano bodies","Granulovacuolar degeneration",exp="A-beta 40 -> cerebral amyloid angiopathy (microhemorrhages in brain); A-beta 42 -> Alzheimer's disease -> depositions of hyperphosphorylated tau proteins (tauopathy)."),
 q(574,"scenario","Deposited inside the neuron, hyperphosphorylated tau forms what, and which sequence follows?","Neurofibrillary tangles -> mitochondrial injury -> progressive neuronal destruction","Amyloid/neuritic plaques -> toxic response from glia","Pick's bodies -> behavioural change","Cortical ribboning -> spongiform change",exp="Inside neuron: neurofibrillary tangles -> mitochondrial injury to neurons -> progressive neuronal destruction; outside neuron: amyloid/neuritic plaques elicit toxic response from oligodendrocytes, microglia, astrocytes."),
 q(574,"scenario","In 'type 3 DM / brain diabetes', why does A-beta 42 accumulate?","Hyperinsulinemia uses up the insulin degrading enzyme, leaving A-beta 42 undegraded","Beta-secretase overexpression in the pancreas","ApoE4 loss in the brain","Insulin directly converts into A-beta",exp="Normal physiology: insulin degrading enzyme (IDE) degrades insulin and A-beta 42; in diabetes hyperinsulinemia -> IDE used up in degrading insulin -> A-beta 42 accumulates."),
 q(574,"recall","The AD pathology list on MRI includes atrophy of which regions?","Median temporal lobe, lateral temporal lobe, cingulate gyrus and entorhinal cortex","Prefrontal cortex, cingulate, caudate","Basal ganglia, thalamus, corpus callosum","Superior parietal, angular gyrus, cerebellum",exp="Pathology: atrophy of median temporal lobe, lateral temporal lobe, cingulate gyrus and entorhinal cortex (gateway of memory) - seen on MRI; plus Hirano bodies and granulovacuolar degeneration."),
 q(574,"management","Depleted cholinergic neurons of the nucleus basalis of Meynert justify which DOC class?","Cholinesterase inhibitors","NMDA antagonists","CGRP antagonists","COMT inhibitors",exp="Depleted cholinergic neurons of nucleus basalis of meynert -> DOC: cholinesterase inhibitors."),
]),
("Genetics, Risk & Clinical Stages", "Genetics, Risk & Clinical Stages",
 "Presenilin-1/2 and ApoE4 chromosomes set the familial-versus-sporadic split.\nRisk factors (and their printed negations) lead into the clinical-stages loop.", [
 q(575,"numeric","The genetic-basis list places Presenilin-1, Presenilin-2 and ApoE4 on which chromosomes respectively?","14, 1 and 19","1, 14 and 21","19, 14 and 1","21, 19 and 14",exp="Genetic basis: Presenilin-1 (chr 14) and Presenilin-2 (chr 1) - m/c defect in familial AD -> early onset -> characteristic features (<45 years, seizures, sleep disturbances); ApoE4 (chr 19) in late-onset dementia, ineffective degradation of A-beta amyloid, most important risk factor (biomarker) for sporadic AD in elderly."),
 q(575,"oddoneout","Pick the ODD ONE OUT - the item that IS a risk factor, against the printed 'Not risk factors' list:","Age","Low IQ","Smoking","NSAIDs",exp="Risk factors: age, positive family history (Presenilin 1 > 2), F > m, h/o head trauma/concussions, h/o stroke, metabolic syndrome, hypertension, diabetes. Printed NOT risk factors: low IQ, smoking, NSAIDs. Note: theory of cognitive reserve - individuals with daily use of cognitive domains are protected from AD."),
 q(575,"scenario","A patient who uses cognitive domains daily is described as protected from AD by which printed theory?","Theory of cognitive reserve","Type 3 DM hypothesis","Vascular theory","Cortical ribboning theory",exp="Note - theory of cognitive reserve: individuals with daily use of cognitive domains -> protected from AD."),
 q(575,"scenario","In the clinical-stages loop, naming and comprehension abnormalities (stage II) follow hippocampal stage I and arise at which structure?","Angular gyrus feeding the association areas","Superior parietal lobe (praxicons)","PFC","Subiculum",exp="Loop: hippocampus -> stage I (Korsakoff amnestic stage: episodic memory loss, difficulty in consolidating memory) -> angular gyrus -> association areas (stage II: stage of anomia, naming and comprehension abnormalities) -> superior parietal lobe praxicons (stage III: visuo-spatial disorientation; apraxia) -> PFC (stage IV: behavioural abnormalities and personality changes). Note: memory = time dependant, contextual, autobiographic."),
]),
("Investigations & Treatment", "Investigations & Treatment",
 "EEG, CSF and PET lines are read with the MRI and PiB PET image pairs.\nThe three-line treatment ladder and the tacrine note close Part 1.", [
 q(576,"numeric","The CSF analysis findings printed for Alzheimer's are:","Down A-beta 42 levels with up hyperphosphorylated tau levels","Up A-beta 42 with down tau","Low protein with high glucose","Xanthochromia with red cells",exp="Investigations: EEG normal/non-specific slowing; CSF analysis down A-beta 42 levels, up hyperphosphorylated tau levels; PET scan IOC detecting hypometabolism and amyloid fibrils (PiB PET scans shown for AD vs control)."),
 q(576,"recall","The PET scan is marked as what for AD, and what does it detect?","IOC; hypometabolism and amyloid fibrils","Screening only; ventricular size","Gold standard; tau only","Second line; glucose uptake only",exp="PET scan: IOC; detects hypometabolism and amyloid fibrils."),
 q(576,"management","The cholinesterase-inhibitor (DOC) list contains which three drugs?","Donepezil, rivastigmine, galantamine","Memantine, aducanumab, tacrine","Levodopa, pramipexole, rotigotine","Amitriptyline, venlafaxine, TCA",exp="Treatment: 1. cholinesterase inhibitors (DOC): donepezil, rivastigmine, galantamine; 2. NMDA antagonist: memantine; 3. monoclonal antibody against A-beta 42: aducanumab."),
 q(576,"recall","The obsolete drug retired for hepatotoxicity in the note is:","Tacrine","Galantamine","Memantine","Aducanumab",exp="Note: tacrine - obsolete (d/t hepatotoxicity)."),
]),
])

# ---------------------------------------------------------------- Chapter 36
ch36 = make_chapter(36, "Dementia : Part 2", "577-582", [
("Frontotemporal & Lewy Body Dementia", "Frontotemporal & Lewy Body Dementia",
 "FTD/Pick's: sporadic proportion, MAPT proteins, behavioural variant and the tauopathy/PFC notes.\nDLB opens with its rank and the Parkinson-plus components; the DLB-versus-PD table and rocket sign follow.", [
 q(577,"numeric","The page prints what percentage of FTD (Pick's disease) as sporadic?","70%","90-95%","50%","100%",exp="FTD (Pick's disease): 70% sporadic, young onset dementia (50-60 years), rapidly progressive dementia; note contrasts Alzheimer's -> 90-95% sporadic (cerebral atrophy MRI pair)."),
 q(577,"recall","FTD pathology involves the MAPT gene on which chromosome, with which m/c protein?","Chromosome 17; TDP-43","Chromosome 14; tau","Chromosome 19; FUS","Chromosome 21; alpha-synuclein",exp="Pathology involves MAPT gene chromosome 17; proteins involved: TDP-43 (m/c), tau (hyperphosphorylated: loss of function of tau molecule) -> Pick's bodies, FUS; b/l prefrontal cortex atrophy."),
 q(577,"scenario","Loss of social embarrassment, apathy, impaired planning and judgement with relatively preserved memory - which FTD type is the m/c one?","Behavioural variant","Logopenic variant","Primary progressive aphasia","Semantic variant",exp="Clinical features: m/c type behavioural variant; loss of social embarrassment; social and emotional systems dysfunction (apathy, overeating - temporal); impaired planning and judgement; memory relatively preserved; hyperorality - temporal lobe involvement."),
 q(577,"recall","The side notes pair hyperphosphorylated tau with which diseases, and split the PFC into which three parts?","Alzheimer's and Pick's; Id, superego, ego","CJD and Binswanger; ego, id, memory","PSP and MSA; attention, memory, motor","AD only; cortex, thalamus, hippocampus",exp="Notes: tauopathy -> hypophosphorylated tau / hyperphosphorylated tau (Alzheimer's, Pick's); PFC -> Id, superego, ego. Diffuse Lewy Body Dementia: 2nd m/c cause of dementia; part of Parkinson-plus/atypical Parkinson's syndrome."),
 q(577,"recall","Which pairing lists only the 'alpha synuclein'-opathies in the Parkinson-plus components tree?","Multiple system atrophy and diffuse Lewy body dementia","Progressive supranuclear palsy and corticobasal degeneration","PSP and multiple system atrophy","Corticobasal degeneration and DLB",exp="Components of Parkinson plus syndrome: 'Tau'opathies - progressive supranuclear palsy, corticobasal degeneration; 'alpha synuclein'-opathies - multiple system atrophy, diffuse Lewy Body dementia."),
 q(578,"recall","Lewy bodies are intraneuronal cytoplasmic inclusions whose content is:","Alpha-synuclein","Hyperphosphorylated tau","TDP-43","A-beta 42",exp="Lewy bodies: intraneuronal cytoplasmic inclusions; content alpha-synuclein. Note: Parkinson's = alpha synucleinopathy; Alzheimer's = 'Tau'pathy (degenerated cholinergic neurons in the nucleus basalis of meynert); anticholinergics are the Rx of drug-induced parkinsonism."),
 q(578,"numeric","Characteristic changes of 'alpha synuclein'-opathies precede disease onset by how long?","5-10 years","1-2 years","15-20 years","2-4 weeks",exp="Characteristic changes 5-10 years before onset of disease: 1. REM sleep disorders; 2. autonomic nervous system symptoms - postural hypotension, erectile > ejaculatory dysfunction, urinary abnormalities."),
 q(578,"oddoneout","Pick the ODD ONE OUT - the autonomic symptom NOT listed for 'alpha synuclein'-opathies:","Sialorrhea","Postural hypotension","Erectile > ejaculatory dysfunction","Urinary abnormalities",exp="Listed ANS symptoms: postural hypotension, erectile > ejaculatory dysfunction and urinary abnormalities."),
 q(578,"scenario","Cognitive impairment within 1 year of motor manifestations, visual hallucinations before motor symptoms, b/l axial rigidity with rocket sign, tremor uncommon, antipsychotics worsening, L-dopa unresponsive - which diagnosis?","DLB dementia","Parkinson's disease","Normal pressure hydrocephalus","Corticobasal degeneration",exp="DLB v/s PD table: DLB - cognitive impairment precedes/within 1 year (predominant rapidly progressive dementia), visual hallucinations and fluctuating alertness precede motor symptoms, tremors uncommon, b/l axial rigidity (rocket sign +), gait abnormalities common, antipsychotics worsen (d/t D2 receptor inhibition), L-dopa no improvement, treatment none available; PD - after 4-5 years of motor manifestations, tremor common, asymmetrical rigidity, gait uncommon, L-dopa improves, Rx L-dopa and deep brain stimulation."),
 q(578,"recall","The rocket sign is defined in the note as:","Falling backwards immediately after trying to get up from a chair","Forward lean on the pull test","Freezing of gait at doorways","Rest tremor with writing",exp="Note: rocket sign - falling backwards immediately after trying to get up from a chair."),
]),
("Subcortical vs Cortical & Prion", "Subcortical vs Cortical & Prion",
 "The subcortical-versus-cortical table is read row by row.\nPrion disease opens with its definition, the four types and the CJD block.", [
 q(579,"scenario","Severe memory impairment, early dysphasia, apraxia/agnosia/acalculia present, visuo-spatial defects more severe, indifferent personality - which column of the comparison table?","Cortical dementia (examples Alzheimer's, FTD)","Subcortical dementia (examples DLB, PSP, NPH, Binswanger)","Mixed dementia","Frontotemporal dementia only",exp="Cortical column: examples Alzheimer's, FTD; affected hippocampus, medial temporal lobe; memory severe; apraxia (superior parietal lobe lesion) / agnosia (association areas) / acalculia (angular gyrus) (+); early dysphasia; visuo-spatial more severe; personality indifferent; mood depressed (subcortical > cortical); coordination normal; cognitive and motor speed normal; abnormal movements rare; extrapyramidal symptoms -."),
 q(579,"recall","The subcortical dementia column's affected regions are:","Subcortical grey matter (basal ganglia, thalamus) and white matter (corticospinal, corticobulbar fibres)","Hippocampus and medial temporal lobe","Angular gyrus and association areas","Superior parietal lobule",exp="Subcortical column: examples DLB dementia, PSP, NPH, Binswanger's disease; regions subcortical grey matter (basal ganglia, thalamus) plus subcortical white matter (corticospinal, corticobulbar fibres); memory less severe; language normal; personality apathetic; coordination impaired; speed slow; abnormal movements common; extrapyramidal symptoms +."),
 q(579,"oddoneout","Pick the ODD ONE OUT - the row value NOT from the subcortical dementia column:","Early dysphasia (language)","Apathetic (personality)","Slow (cognitive and motor speed)","Common (abnormal movements)",exp="Subcortical column values: language normal (cortical: early dysphasia), personality apathetic, speed slow, abnormal movements common."),
 q(579,"recall","Prion is defined on the page as:","An infectious protein with no nucleic acid","A misfolded peptide carrying nucleic acid","A prion-derived RNA virus","A glycoprotein of the dura",exp="Prion: infectious protein with no nucleic acid; genetic/sporadic. Pathology: beta-pleated PrPsc protein -> spongiform degeneration of cortex -> neuronal loss."),
 q(580,"oddoneout","Pick the ODD ONE OUT - the prion disease NOT in the types list:","Whipple's disease","Creutzfeldt-Jakob disease (CJD)","Familial fatal insomnia","Kuru",exp="Types of prion diseases: 1. CJD, 2. familial fatal insomnia, 3. kuru, 4. Gerstmann Straussler Scheinker disease. Common features: young onset dementia, rapidly progressive dementia, no immune response. (Whipple's appears only in the p573 rapidly-progressive list.)"),
 q(580,"scenario","CJD: spongiform cortical changes with cortical ribboning, basal ganglia hyperintensities, dementia with myoclonus, long incubation and no immune response - which investigation confirms the diagnosis?","Brain biopsy","CSF cytology","PET scan","CT with contrast",exp="CJD investigations: EEG - low voltage background, high voltage sharp waves; CSF normal; brain biopsy to confirm diagnosis; Rx flupirtine maleate (centrally acting non-opioid analgesic)."),
 q(580,"recall","The dementia-protein table pairs DLB with which protein?","Alpha-synuclein","A-beta (Alzheimer's)","Tau (FTD)","PrPsc (CJD)",exp="Dementia-protein table: Alzheimer's A-beta; FTD tau; DLB alpha synuclein; CJD PrPsc. Vascular dementia: types large vessel disease (post-CVA dementia) and small vessel disease."),
]),
("Vascular Dementia & NPH", "Vascular Dementia & NPH",
 "Large-vessel criteria and the stroke-dementia relationship open the vascular block.\nSmall vessel disease (Binswanger, CAA, CADASIL) and the NPH tree/triad close the chapter.", [
 q(580,"recall","Large-vessel vascular dementia: the m/c site of infarct per the page is:","B/L PCA lesion","B/L MCA lesion","Anterior choroidal artery only","Strategic territory of the ACA",exp="Large vessel disease: m/c site of infarct b/l PCA lesion; criteria: 1. dementia; a. cerebrovascular disease - multi-infarct state with 'strategic territory' infarct (infarct in these areas leads to dementia)."),
 q(581,"numeric","The 'relationship between the two disorders' requires dementia onset when after a stroke?","Within 3 months","Within 1 week","Within 6 months","Within 1 year",exp="3. Relationship between the two disorders: onset of dementia within 3 months of stroke; stepwise decline in cognitive function (stepwise graph)."),
 q(581,"numeric","Binswanger disease pathology involves penetrating vessels of what size range?","30-300 micrometres","3-30 micrometres","300-500 micrometres","1-5 millimetres",exp="Small vessel disease - Binswanger disease: most important risk factor HTN; lacunar infarct; pathology lipohyalinotic infarct involving penetrating vessels (size 30-300 um); MRI finding white matter hyperintensities in elderly (gradual cognitive-decline graph); features similar to vascular Parkinson's."),
 q(581,"scenario","A small-vessel patient with gait apraxia, magnetic foot and falls - which tract's lower-limb fibres (close to the ventricle) are affected per the table?","Corticospinal tract","Corticobulbar tract","Corticostriate fibres","Fibres from the paracentral lobule",exp="Fibres affected -> manifestation: corticobulbar tract -> pseudobulbar palsy; corticospinal tract (affects lower limb fibres close to the ventricle) -> gait disturbances and falls, gait apraxia, magnetic/ignition foot phenomenon (feet 'stuck' to floor); fibres from paracentral lobule -> urinary abnormalities; corticostriate fibres (PFC to striatum) -> personality changes."),
 q(581,"oddoneout","Pick the ODD ONE OUT - the item NOT a feature of cerebral amyloid angiopathy:","NOTCH3 mutation","A-beta 40 protein deposition","Elderly patients","Microhemorrhages",exp="Cerebral amyloid angiopathy: A-beta 40 protein deposition, elderly, microhemorrhages. (NOTCH3 is the CADASIL mutation.)"),
 q(582,"recall","CADASIL is the m/c inherited vascular dementia with which mutation and presentation?","NOTCH3; aura + migraine + dementia + stroke","APP; chorea + tremor + dementia","PSEN1; spasticity + aphasia","HTN-related; gait + incontinence + dementia",exp="CADASIL: cerebral autosomal dominant arteriopathy with small vessel ischemic change/leukoencephalopathy, or CADA with stroke and ischemic leukoencephalopathy; m/c inherited vascular dementia; NOTCH3 mutation; presentation aura + migraine + dementia + stroke."),
 q(582,"recall","The NPH hydrocephalus tree places aqueductal stenosis under which branch?","Occlusive (non-communicating)","Non-occlusive (communicating) with down CSF adsorption","Idiopathic NPH","Familial congenital",exp="Hydrocephalus: occlusive (non-communicating) -> aqueductal stenosis; non-occlusive (communicating) -> up CSF production or down CSF adsorption -> idiopathic (NPH) / familial (congenital: arachnoid granulations; acquired: trauma, SAH). Note: atrophy - obtuse interventricular angle."),
 q(582,"management","NPH per the page: the GUD abnormalities, CSF profile and Rx are:","Gait apraxia (magnetic foot), urinary incontinence, subcortical dementia; normal CSF pressure (20 ml/day produced); shunting","Spastic paraparesis, urgency, cortical dementia; raised CSF pressure; acetazolamide","Tremor, ataxia, aphasia; low CSF pressure; fenestration","Apraxia, incontinence, amnesia; xanthochromic CSF; shunt revision",exp="NPH pathology: adsorption defect > outflow resistance of CSF -> ventriculomegaly, no atrophy. Clinical: symptoms progress over weeks to months; GUD - gait (gait apraxia/magnetic foot), urinary (incontinence), dementia (subcortical type); arrest in initiation of ambulation; gait instability with multiple falls; generalized slow movements; CSF pressure normal (20 ml/day produced); Rx shunting (good prognosis if effective); MRI - interventricular angle acute."),
]),
])

# ---------------------------------------------------------------- Chapter 37
ch37 = make_chapter(37, "Parkinson's Disease", "583-592", [
("Basal Ganglia Anatomy & Circuits", "Basal Ganglia Anatomy & Circuits",
 "The subcortex tree and the nuclei diagram set the basal-ganglia map with its lesion syndromes.\nDirect/indirect pathway rules, the nigrostriatal D1/D2 actions and the idiopathic-PD intro follow.", [
 q(583,"recall","The subcortex tree: grey matter and white matter give rise to which structures?","Basal ganglia; corticospinal tract and corticobulbar fibres passing through the internal capsule","Cerebellum; spinothalamic tract","Thalamus; medial lemniscus","Brainstem; corticospinal tract only",exp="Subcortex -> grey matter -> basal ganglion; white matter -> corticospinal tract, corticobulbar fibres (pass through internal capsule)."),
 q(583,"recall","Per the nuclei diagram, the corpus striatum and lenticular nucleus are formed by which pairings?","Caudate + putamen; putamen + globus pallidus","Caudate + GP; putamen + STN","Putamen + SN; caudate + STN","Caudate + STN; putamen + SN",exp="Nuclei: caudate nucleus (CN), putamen, globus pallidus (GP: GPi, GPe), subthalamic nucleus (STN), substantia nigra (SN); corpus striatum = CN + putamen; lenticular nucleus = putamen + GP."),
 q(583,"scenario","A lesion of the subthalamic nucleus produces which movement disorder per the diagram?","Hemiballismus","Chorea (caudate lesion)","Dystonia/athetosis (putamen-striatum lesion)","Rigidity only",exp="Lesion -> hypokinetic movements: caudate -> chorea; putamen/striatum -> dystonia/athetosis; STN -> hemiballismus."),
 q(583,"recall","The basal-ganglia physiology functions listed are:","Complex motor activity; initiation and scaling of movement; cognitive part; activity set for movement (planning, programming, initiation)","Sensory discrimination, memory consolidation, language naming","Respiratory drive, heart rate, blood pressure","Vision, hearing, balance",exp="Functions: complex motor activity; initiation and scaling of movement; cognitive part of motor activity; activity set for movement (planning, programming and initiation). Note: premotor cortex and supplementary motor area also involved in planning and programming."),
 q(584,"recall","The three general features of the direct and indirect pathways are:","All input from cortex to striatum; all output leaves through GPi; the only excitatory BG nucleus is the subthalamus","All input from thalamus; output via STN; only inhibitory nucleus is GPi","Input from brainstem; output via SN; only excitatory is caudate","All input from cerebellum; output via thalamus; subthalamus inhibitory",exp="General features: 1. all input from cortex -> striatum; 2. all output leave through GPi; 3. the only excitatory nucleus in BG: subthalamus."),
 q(584,"scenario","The nigrostriatal pathway (SN -> corpus striatum) acts via D1 and D2 receptors to do what?","D1 activates the direct pathway and D2 inhibits the indirect pathway, together stimulating the cortex","D1 inhibits the direct pathway and D2 activates the indirect pathway","Both receptors inhibit the thalamus","D1 excites STN and D2 excites GPe",exp="Nigrostriatal pathway: via D1 activate direct pathway; via D2 inhibits indirect pathway - together stimulating of cortex."),
 q(584,"scenario","Degeneration of the nigrostriatal pathway in PD produces which applied-aspect outcome?","Inhibition of the cortex -> akinesia and bradyphrenia (slowness of thoughts)","Excitation of the cortex -> hyperkinesia","Thalamic release -> chorea","STN disinhibition -> dystonia",exp="Applied aspect: degeneration of NS pathway (Parkinson's disease) -> inhibition of cortex -> akinesia, bradyphrenia (slowness of thoughts). Disorders of BG: hyperkinetic vs hypokinetic (paucity of movement - down amplitude, slowness - unrelated to weakness/spasticity). Idiopathic PD: and m/c neurodegenerative disease; majority cases sporadic, elderly > 60 years."),
]),
("Idiopathic PD: Appearance & Tremor", "Idiopathic PD: Appearance & Tremor",
 "The idiopathic profile (sporadic, >60 yrs) precedes the symptomatic-appearance figure.\nThe PD-versus-essential tremor table is read row by row; printed p586 is absent from the supplied scan.", [
 q(584,"numeric","Idiopathic Parkinson's disease: the majority cases are which distribution and age?","Sporadic; elderly > 60 years","Familial; children < 10 years","Sporadic; adolescents","Autosomal dominant; 40-50 years",exp="Idiopathic Parkinson's disease: and m/c neurodegenerative disease; majority cases: distribution sporadic, age elderly > 60 years."),
 q(585,"scenario","The 'typical symptomatic appearance' figure labels which constellation?","Stooped posture, masked facial expression, rigidity, forward tilt of trunk, flexed elbows and wrists, reduced arm swinging, slightly flexed hips and knees, trembling of extremities, shuffling short-stepped gait","Hyperextended posture, lively facies, flaccidity, wide-based ataxic gait","Kyphoscoliosis, facial grimacing, tremor-free hands","Forward lean with brisk arm swing and long strides",exp="Figure labels: stooped posture, masked facial expression, rigidity, forward tilt of trunk, flexed elbows and wrists, reduced arm swinging, slightly flexed hips and knees, trembling of extremities, shuffling short-stepped gait."),
 q(585,"numeric","The tremor-comparison table gives Parkinson disease tremor frequency as:","4-6 Hz","5-12 Hz (essential tremor)","1-2 Hz","10-15 Hz",exp="Frequency row: PD tremor 4-6 Hz; essential tremor 5-12 Hz."),
 q(585,"scenario","A rest tremor with re-emergent component, asymmetric, hands and legs, micrographia, progressive course, 1% family history, extrapyramidal signs present, levodopa-responsive, DBS at STN or GPi - which tremor?","Parkinson's disease tremor","Essential tremor","Cerebellar intention tremor","Orthostatic tremor",exp="PD column: at rest +/- re-emergent tremor, asymmetric, hands +/- legs, small writing (micrographia), progressive, family history uncommon (1%), extrapyramidal signs (bradykinesia, rigidity, loss of postural reflex) present, relieved by levodopa/dopamine agonists/anticholinergics, DBS site subthalamic nucleus or globus pallidus interna. Essential column: postural tremor, mostly symmetric, hands/head/voice, large and tremulous writing, stable or slowly progressive, family history common (>30%), EPS absent, relieved by alcohol/propranolol/primidone/topiramate/gabapentin/clonazepam, DBS ventral intermediate thalamus."),
 q(585,"oddoneout","Pick the ODD ONE OUT - the relieving factor NOT for Parkinson disease tremor per the table:","Propranolol","Levodopa","Dopamine agonists","Anticholinergics",exp="PD relieving factors: levodopa, dopamine agonists, anticholinergics; essential tremor relieving factors include alcohol, propranolol, primidone, topiramate, gabapentin, clonazepam."),
 q(586,"recall","The sheet for printed p586 is absent from the supplied scan. Which statement correctly places it in the Parkinson's sequence?","It lies between the p585 tremor-comparison table and the p587 rigidity list","It lies between the p583 title page and the p584 pathway diagram","It lies between the p589 L-dopa list and the p592 agonist examples","No sheet is missing - p587 follows p585 directly in the scan",exp="Printed p586 is absent from the supplied scan (it proceeds p585 -> p587); its bracketing content is the p585 PD-versus-essential tremor table and the p587 rigidity/akinesia list. Content verification of p586 remains unresolved, as with the missing p527 in Chapter 26."),
]),
("Motor Signs, Posture & Investigations", "Motor Signs, Posture & Investigations",
 "Rigidity types and Froment's sign open the motor-signs page.\nThe akinesia/bradykinesia cluster, atypical notes, postural instability and the swallow-tail MRI follow.", [
 q(587,"recall","Cogwheel and lead-pipe rigidity are distinguished at which sites per the page, and what is Froment's sign?","Cogwheel (rigidity + tremor) at the wrist; lead pipe at the elbow; Froment's sign = activity-induced increase in c/l rigidity","Cogwheel at the elbow; lead pipe at the wrist; Froment's sign = thumb pinch sign","Both at the ankle; Froment's sign = falling backwards","Both at the neck; Froment's sign = tremor vanishing in action",exp="Hypertonia - 2 types: cogwheel rigidity (rigidity + tremor) at wrist; lead pipe rigidity at elbow. Froment's sign: activity-induced increase in c/l rigidity (as printed on the page)."),
 q(587,"scenario","Bradyphrenia, reduced arm swing, stooped posture from flexion hypertonia, short quick steps with freezing, narrow-based festinant gait, micrographia, hypomimia, hypophonia and reduced blinking - this printed cluster is:","Akinesia/bradykinesia","Postural instability","Rigidity","Sensory symptoms of PD",exp="Akinesia/bradykinesia: bradyphrenia; reduced arm swing (difficulty with limb movements); flexion hypertonia (stooped posture); short quick steps and freeze in between; festinant gait (narrow-based); micrographia; hypomimia (minimal expression); hypophonia (down voice); reduced blinking - glabellar tap sign positive."),
 q(587,"oddoneout","Pick the ODD ONE OUT - the item NOT on the atypical-PD/hypokinesia note on this page:","Visual hallucinations with fluctuating alertness","B/l axial rigidity (wheelchair sign)","Hypothyroidism as a non-Parkinsonian hypokinesia","Difficulty turning in bed",exp="Note: atypical PD - b/l axial rigidity: difficulty turning in bed, rising from a chair (wheelchair sign); non-parkinsonian lesion having hypokinesia: hypothyroidism. (Visual hallucinations with fluctuating alertness are DLB features on p588.)"),
 q(587,"scenario","The pull test shows the patient falls backward (normal: takes 2-3 steps backwards to correct posture) - which feature is demonstrated?","Postural instability","Festination","Bradyphrenia","Rigidity",exp="Postural instability: unsteadiness and falls; pull test - patient falls backward (normal: takes 2-3 steps backwards to correct posture)."),
 q(587,"recall","The investigation line for Parkinson's disease states the diagnosis is:","Clinical diagnosis","DaT-SPECT based","Brain biopsy","CSF alpha-synuclein assay",exp="Investigation: clinical diagnosis."),
 q(587,"scenario","MRI at midbrain level shows b/l grey-matter hyperintensities surrounded by hypointense red nuclei and crural fibres, with absent swallow-tail sign - the sign's origin per the note is:","The substantia nigra (swallow tail sign d/t SN)","The subthalamic nucleus","The red nucleus","The globus pallidus",exp="MRI midbrain level: hyperintensities b/l in grey matter surrounded by hypointense red nuclei and crural fibres; absence of swallow tail sign (swallow tail sign d/t SN)."),
 q(587,"recall","The 'PD patient can also have' note lists which symptom groups?","Sensory (pain, anosmia), neuropsychiatric (depression > dementia), gastrointestinal (dysphagia)","Visual (cortical blindness), auditory (deafness), urinary","Motor (chorea), cognitive (aphasia), skin (rash)","Sensory (tinnitus), psychiatric (mania), GI (diarrhoea only)",exp="PD patients can also have sensory symptoms (pain, anosmia), neuropsychiatric symptoms (depression > dementia) and gastrointestinal symptoms (dysphagia)."),
]),
("Atypical PD & MSA", "Atypical PD & MSA",
 "Parkinson-plus hallmarks and the tau/synuclein classification set the atypical group.\nEntity-specific features, then MSA age, inclusions and subtype proportions.", [
 q(588,"recall","Atypical Parkinson's disease is also called what, with which listed hallmarks?","Parkinson plus syndromes - rapid progression, early onset dementia, symmetrical bradykinesia, facial dyskinesia","Parkinson minus syndromes - slow progression, late dementia","Juvenile PD - tremor, early onset","Drug-induced parkinsonism - acute onset, reversible",exp="Atypical PD aka Parkinson plus syndromes: rapid progression, early onset dementia, symmetrical bradykinesia, facial dyskinesia. Classifications: tauopathy (PSP, CBD) and alpha synucleinopathy (MSA, DLB)."),
 q(588,"scenario","The features common to atypical PD itself per the list are:","Absence of tremor, unresponsiveness to L-dopa, rapidly progressive","Prominent rest tremor, good L-dopa response, slowly progressive","Postural tremor, alcohol response, symmetric","Chorea, cognitive sparing, young onset",exp="Atypical PD: absence of tremor, unresponsiveness to L-dopa, rapidly progressive; DLB: dementia at presentation, visual hallucination, fluctuating alertness; CBD: myoclonus, cortical signs; PSP: falls d/t postural instability, dementia component, b/l axial rigidity, supranuclear gaze palsy; MSA: ANS symptoms, disproportionate cerebellar signs."),
 q(588,"scenario","Supranuclear gaze palsy with b/l axial rigidity and falls from postural instability - which atypical PD?","Progressive supranuclear palsy (PSP)","Corticobasal degeneration","Multiple system atrophy","Diffuse Lewy body dementia",exp="PSP: falls d/t postural instability, dementia component, b/l axial rigidity, supranuclear gaze palsy."),
 q(588,"recall","CBD's listed features are:","Myoclonus and cortical signs","Visual hallucination and fluctuating alertness","ANS symptoms and cerebellar signs","Dementia at presentation and hallucinations",exp="CBD: myoclonus, cortical signs; DLB: dementia at presentation, visual hallucination, fluctuating alertness; MSA: ANS symptoms, disproportionate cerebellar signs."),
 q(588,"numeric","MSA per the page: age range and defining inclusions are:","45-55 years; glial cytoplasmic inclusions staining for alpha synuclein","60-70 years; Lewy bodies in cortex","30-40 years; Pick bodies","50-60 years; neurofibrillary tangles",exp="MSA: 45-55 yrs; glial cytoplasmic inclusions (stain for alpha synuclein) - alpha synucleinopathy; REM sleep disorders (years before diagnosis); ANS predominant."),
 q(588,"numeric","The MSA classification prints what proportion as MSA-P (parkinson predominant)?","80%","15%","50%","95%",exp="MSA classification: MSA-P (80%) parkinson predominant; MSA-C cerebellar predominant; MSA-A/Shy-Drager syndrome (15%) ANS predominant."),
]),
("Treatment & Protocols", "Treatment & Protocols",
 "L-dopa, decarboxylase and COMT inhibitors with administration and fluctuation handling.\nAnticholinergics and agonist disadvantages; printed p590-p591 are absent from the supplied scan.\nThe p592 examples, amantadine MOA, newer drugs and the age-based protocol close the chapter.", [
 q(589,"recall","L-dopa is combined with a decarboxylase inhibitor because:","Peripheral metabolism of L-dopa is high","L-dopa cannot cross the blood-brain barrier without it","It prevents CSF accumulation","It masks orthostatic hypotension",exp="Drugs: L-Dopa - peripheral metabolism is high; combined with: dopa decarboxylase inhibitor (carbidopa, benserazide); COMT inhibitors - not used now: tolcapone (hepatotoxic), entacapone (hepatotoxic, orange coloured urine); L-Dopa + dopa decarboxylase inhibitor is the combination started."),
 q(589,"scenario","The L-dopa administration details printed on the page are:","Small doses, multiple times, crushed and mixed with carbonated water","Single large dose at night with plain water","Only when symptoms are severe, fasting","With meals to reduce nausea",exp="All patients are started on L-dopa: small doses, multiple times, crushed and mixed with carbonated water. Symptoms non-responsive to L-dopa: freezing, falls, dysphagia, dysarthria, ANS symptoms."),
 q(589,"oddoneout","Pick the ODD ONE OUT - the symptom NOT printed as non-responsive to L-dopa:","Rest tremor","Freezing","Falls","Dysarthria",exp="Symptoms non-responsive to L-dopa: freezing, falls, dysphagia, dysarthria, ANS symptoms."),
 q(589,"scenario","Peak-dose choreiform dyskinesia and off-period dystonia differ by what per the page?","High dose versus low drug concentration respectively","Young versus old age","Morning versus evening dosing","With versus without carbidopa",exp="Side effects: nausea/vomiting, postural hypotension; motor fluctuations - wearing off (space drug without much gap), on/off, delayed onset of action, drug failure; dyskinesias - peak dose dyskinesia: choreiform movements (d/t high dose), off period dyskinesia: dystonia (d/t low drug concentration)."),
 q(589,"management","The drug the page assigns to tackle motor fluctuations is:","Amantadine","Carbidopa","Entacapone","Trihexyphenidyl",exp="Motor fluctuations (wearing off, on/off, delayed onset of action, drug failure) - to tackle: amantadine."),
 q(589,"recall","Central anticholinergics and the dopaminergic-agonist disadvantage note state:","Trihexyphenidyl is used in drug-induced PD; DDS brings visual hallucinations, impulse control issues, addiction","Trihexyphenidyl is the DOC for idiopathic PD; DDS brings depression and amnesia","Propranolol is used in drug-induced PD; DDS brings pain and anosmia","Carbidopa is a central anticholinergic; DDS brings seizures and aphasia",exp="Central anticholinergics: trihexyphenidyl; used in drug-induced PD. Dopaminergic agonists: found as replacement for L-dopa; disadvantages - dopamine dysregulation syndrome (neuropsychiatric manifestations: visual hallucinations, impulse control issues, addiction)."),
 q(590,"recall","The supplied scan proceeds directly from p589 to p592. What is absent between them?","Printed p590 and p591, both missing from the supplied scan","Only printed p590 is missing","Only printed p591 is missing","Nothing is missing - p592 follows p589 in the book",exp="Printed p590 and p591 are absent from the supplied scan, so the dopaminergic-agonist material between the p589 disadvantages list and the p592 examples list cannot be visually verified; this follows the unresolved-missing-page precedent set by p527 in Chapter 26."),
 q(591,"recall","The p591 sheet is absent from the supplied scan. Which visible page carries the 'Example: pramipexole, ropinirole, rotigotine, apomorphine' list that follows it?","Printed p592, which opens with that examples list","Printed p589, which ends with the DDS note","Printed p594, the signs-of-raised-ICP page","Printed p584, the pathway-diagram page",exp="With p591 (and p590) absent from the supplied scan, the next visible sheet - p592 - opens with the dopaminergic-agonist examples list: pramipexole (antidepressant action also), ropinirole, rotigotine, apomorphine (used in rescue therapy, IV route)."),
 q(592,"recall","The dopaminergic-agonist examples list on this page includes which drug used in rescue therapy by the IV route?","Apomorphine","Pramipexole","Ropinirole","Rotigotine",exp="Example: pramipexole (antidepressant action also), ropinirole, rotigotine, apomorphine - i. used in rescue therapy, ii. IV route."),
 q(592,"numeric","Amantadine's printed mechanisms of action number how many, and which are they?","3 - dopaminergic agonist, anticholinergic, NMDA antagonist","2 - anticholinergic and NMDA antagonist","4 - including a COMT-inhibitor action","1 - dopaminergic agonist only",exp="Amantadine: 3 mechanisms of action - dopaminergic agonist, anticholinergic, NMDA antagonist. Newer drugs: istradefylline (A2a antagonist - minimizes motor fluctuations), pimavanserin (5HTa antagonist)."),
 q(592,"management","The treatment protocol prints which first-line choice for a patient <60 years with mild symptoms?","A dopaminergic agonist","L-dopa + carbidopa","Trihexyphenidyl","Amantadine",exp="Treatment protocol: <60 yrs old + mild symptoms -> dopaminergic agonist; >60 yrs / significant disease present -> L-dopa + carbidopa."),
]),
])

# ---------------------------------------------------------------- Chapter 38
ch38 = make_chapter(38, "Headache", "593-601", [
("Anatomy, Classification & Dangerous Headache", "Anatomy, Classification & Dangerous Headache",
 "Pain-sensitive versus pain-insensitive structures open the chapter.\nPrimary/secondary classification, giant cell arteritis, raised-ICP red flags and the herniation line follow.", [
 q(593,"scenario","Which of these structures is pain-INSENSITIVE per the relevant-anatomy list?","Choroid plexus","Dural venous sinuses","Dura around vessels","Circle of Willis",exp="Pain sensitive: dural venous sinuses, dura around vessels, large veins, circle of Willis, dural arteries (meningeal arteries), first few centimeters of medium sized vessels, pia mater, small cerebral vessels; pain insensitive: choroid plexus, ependyma."),
 q(593,"recall","The primary headache causes listed in the classification are:","Tension headache (m/c), migraine (2nd m/c), trigeminal autonomic cephalalgias (e.g. cluster headache)","Giant cell arteritis, SAH, brain tumour","Tension and cluster only","Migraine, TTH, paroxysmal hemicrania only",exp="Classification: primary (benign, recurrent, no organic cause) - tension headache m/c, migraine 2nd m/c, TACs (eg cluster headache); secondary - systemic infection, brain tumour (rare)."),
 q(593,"scenario","A new-onset headache after 55 years with scalp tenderness, thick/nodular vessels, jaw claudication, PUO and raised ESR points to which dangerous-headache cause?","Giant cell arteritis","Migraine with aura","Tension-type headache","Trigeminal neuralgia",exp="Dangerous headache - new onset headache after 55 yrs: seen in giant cell arteritis, associated with scalp tenderness, thick/nodular vessels, jaw claudication, PUO, ESR raised."),
 q(593,"recall","The raised-intracranial-tension features printed on the page include:","Subacute, rapidly progressive over a few weeks, nocturnal awakening, vomiting preceding/relieving headache, intensity increased by bending/coughing (meningeal inflammation), blurring of vision","Chronic steady pain relieved by NSAIDs with no red flags","Pulsatile tinnitus with papilledema only","Electric shock pain in V2 and V3 with triggers",exp="Up intracranial tension: subacute, rapidly progressive over a few weeks, nocturnal awakening, vomiting (precede/relieve headache), up intensity by bending/coughing (seen in meningeal inflammation), blurring of vision - do direct ophthalmoscopy, if papilledema (+) -> imaging (MRI, MRA, MRV)."),
 q(593,"scenario","Papilledema found on direct ophthalmoscopy in this headache block triggers which investigation set per the page?","MRI, MRA, MRV","CT head alone","EEG and LP only","Carotid Doppler and ESR",exp="Investigation line for the raised-ICP/dangerous-headache block: MRI, MRA, MRV (after direct ophthalmoscopy; papilledema (+) -> imaging)."),
 q(594,"recall","Signs of raised ICP per the p594 list are:","Bradycardia, bradypnoea, hypertension, cardiac arrhythmia","Tachycardia, tachypnoea, hypotension","Bradycardia, hyperventilation, hypertension only","Hypertension, tachycardia, bradypnoea",exp="Signs of up ICT: bradycardia, bradypnoea, hypertension, cardiac arrhythmia."),
 q(594,"scenario","The herniation complication line: the m/c herniation site and its sign are:","Uncus (inferior part of temporal lobe) with 3rd nerve palsy","Tonsil with 12th nerve palsy","Central herniation with 4th nerve palsy","Subfalcine herniation with 6th nerve palsy",exp="Complication: herniation -> coning -> death; m/c site: uncus (inferior part of temporal lobe); signs: 3rd nerve palsy; Rx: decompression."),
]),
("Tension-Type & Migraine", "Tension-Type & Migraine",
 "TTH features, its Mx and the 'against TTH' discriminators.\nMigraine features, the 80/20 type split, aura and the four-stage sequence follow.", [
 q(594,"scenario","Middle-aged female, holocranial band-like pressure, ADL preserved, one-third with depression - which headache, and its chronic prophylaxis per the page?","Tension-type headache; amitriptyline (TCA) d/t associated depression","Cluster headache; verapamil","Migraine; triptan","Trigeminal neuralgia; carbamazepine",exp="Tension type headache (TTH): middle-aged female; 1/3rd cases associated with depression; holocranial band-like or pressure sensation; does not affect activities of daily living; no danger signs. Mx: acute NSAIDs; chronic amitriptyline (TCA) d/t associated depression (prophylactic)."),
 q(594,"oddoneout","Pick the ODD ONE OUT - the feature AGAINST tension-type headache per the page:","Photophobia","Holocranial band-like sensation","No effect on activities of daily living","No danger signs",exp="Against TTH: vomiting, photophobia, phonophobia, aggravated by movement."),
 q(594,"recall","The migraine feature list on this page includes which items?","Episodic, adolescence onset, severity increases with age, F > m, family history +, normal systemic examination","Continuous for months, onset after 55, M > F","Pulsatile pain with V2/V3 cutaneous triggers","Orthostatic, daily, bilateral, worse in morning",exp="Migraine features: episodic; adolescence onset; severity up with age; F > m; family history +; not attributable to other diseases; normal systemic examination."),
 q(594,"numeric","The migraine type split printed is:","Common 80% (not associated with aura) and classical 20% (associated with aura)","Common 50% and classical 50%","Common 90% and classical 10%","Common 70% and classical 30%",exp="Types: common (80%) - not associated with aura; classical (20%) - associated with aura."),
 q(594,"numeric","Aura duration per the classical-migraine line is, and the m/c visual phenomenon is:","15 minutes - 1 hour; fortification spectra (zig-zag lines in peripheral vision, hazy central spot)","5 - 15 minutes; teichopsia alone","1 - 4 hours; micropsia","24 - 48 hours; scintillating scotoma of TTH",exp="Aura: subjective, duration 15 mins - 1 hr; visual (m/c) - fortification spectra (m/c): zig-zag lines in peripheral vision, hazy spot in centre of vision; sensory (tingling and numbness); auditory; motor."),
 q(595,"recall","The stages of migraine on this page run in which order?","Prodrome -> aura -> headache -> postdrome","Aura -> prodrome -> postdrome -> headache","Headache -> prodrome -> aura -> postdrome","Prodrome -> headache -> postdrome -> aura",exp="Stages of migraine: 1. prodrome -> 2. aura (zig-zag lines m/c) -> 3. headache -> 4. postdrome (lethargy, low mood/depressed)."),
 q(595,"recall","The prodrome and headache stages carry which features per the page?","Prodrome: mood disturbance, irritability, depressive symptoms; headache: unilateral -> holocranial, frontotemporal, throbbing/pounding, nausea/vomiting (rare), photophobia/phonophobia/osmophobia, photopsia, scintillating scotomas","Prodrome: photopsia; headache: pulsatile with V2/V3 triggers","Prodrome: lethargy; headache: orthostatic and daily","Prodrome: visual scotoma; headache: 24-48 hrs constant",exp="Prodrome: mood disturbance, irritability, depressive symptoms; aura: zig-zag lines (m/c); headache: unilateral -> holocranial, frontotemporal, throbbing/pounding type, nausea/vomiting (rare), photophobia/phonophobia/osmophobia, photopsia (flashing lights), scintillating scotomas; postdrome: lethargy, low mood/depressed."),
 q(595,"numeric","The migraine headache stage duration printed is:","4-72 hours","1-4 hours","24-48 hours","48-72 hours only",exp="Headache stage duration: 4-72 hrs."),
 q(595,"recall","The most common migraine trigger per the page, with its stated mechanism, is:","Sleep deprivation - d/t serotonin-melatonin cycle disruption","Menstruation - d/t hormonal fluctuation","Excess stress - d/t cortisol surge","Traffic - d/t noise",exp="Triggers: sleep deprivation (m/c) d/t serotonin-melatonin cycle disruption; menstruation d/t hormonal fluctuation; excess stress; traffic, climate, mosquito, henna, food etc."),
]),
("Migraine Criteria, Pathogenesis & Treatment", "Migraine Criteria, Pathogenesis & Treatment",
 "Common and classical criteria with their numeric thresholds.\nThe vascular/serotonin pathogenesis arms, the acute treatment table and the three-line prophylaxis follow with S/E and newer drugs.", [
 q(595,"numeric","The common-migraine criteria require a minimum of how many attacks, lasting how long?","5 attacks, lasting 4-72 hrs","3 attacks lasting 1-4 hrs","10 attacks lasting 48-72 hrs","2 attacks lasting 4-72 hrs",exp="Common migraine: minimum 5 attacks lasting 4-72 hrs; characteristics (at least 2): unilateral, pulsatile, moderate to severe intensity, aggravated by routine physical activity/movement; clinical features (at least 1): nausea/vomiting (rare), photophobia/phonophobic; not attributed to another disorder."),
 q(595,"numeric","Classical-migraine aura criteria require at least how many of the listed features?","3 - gradual, duration < 60 mins, reversible","2 - gradual and reversible","4 - including headache within 60 mins","1 - reversibility alone",exp="Classical migraine: at least 3 attacks lasting 4-72 hrs; aura - at least 3 of: gradual, duration <60 mins, reversible, headache within 60 mins of aura OR headache preceding/simultaneous with aura; not attributable to another disorder."),
 q(595,"scenario","In the pathogenesis diagram, vasoconstriction leads to which phase?","Aura","Headache","Postdrome","Prodrome",exp="Pathogenesis: vascular theory - vasoconstriction -> aura, vasodilation -> headache; serotonin theory - down level of serotonin. Important pathogenic cytokine: CGRP (calcitonin gene-related peptide); pathway: trigeminovascular complex."),
 q(595,"recall","The 5-HT1F agonist ('ditans') named in the serotonin-theory Rx is:","Lasmiditan","Sumatriptan","Rizatriptan","Metoclopramide",exp="Serotonin theory Rx: 5-HT1b/1d agonist: triptans (DOC); 5-HT1F agonist: ditans (Lasmiditan)."),
 q(596,"recall","The other migraine-with-aura types listed here are:","Ophthalmoplegic, retinal, basilar type, familial hemiplegic (Ca2+ channelopathy)","Hemicrania continua, cluster, paroxysmal hemicrania","SUNCT, SUNA, status migrainosus","Postdrome, prodrome, aura",exp="Other types of migraine with aura: 1. ophthalmoplegic (transient 3rd nerve palsy, involvement of pupil +); 2. retinal (unilocular visual impairment); 3. basilar type (occipital involvement, ataxia, tinnitus, vertigo); 4. familial hemiplegic migraine: Ca2+ channelopathy."),
 q(596,"management","The acute-attack antiemetic options printed are:","Metoclopramide 5-10 mg/D and domperidone","Ondansetron 8 mg IV and cyclizine","Prochlorperazine 10 mg and promethazine","Haloperidol and metoclopramide 10-20 mg",exp="Acute attack - antiemetics: metoclopramide 5-10 mg/D; domperidone."),
 q(596,"management","The mild-migraine column of the acute treatment table lists:","Paracetamol; NSAID - naproxen 550 mg BD, ibuprofen 400 mg QID","Sumatriptan 50-100 mg","Rizatriptan 5-10 mg","Zolmitriptan intranasal",exp="Treatment table - mild: paracetamol, NSAID (naproxen 550 mg BD, ibuprofen 400 mg QID); moderate to severe: triptan (5HT1b/1d agonists) - eletriptan, rizatriptan, almotriptan, sumatriptan; very severe: sumatriptan 6 mg S/C x 2 doses intranasal, zolmitriptan intranasal."),
 q(596,"numeric","The printed maxima in the moderate-to-severe column for rizatriptan and sumatriptan are:","30 mg and 200 mg respectively","10 mg and 100 mg","30 mg and 100 mg","60 mg and 200 mg",exp="Moderate to severe: rizatriptan 5-10 mg (max: 30mg); sumatriptan 50-100 mg (max: 200mg); eletriptan; almotriptan."),
 q(596,"oddoneout","Pick the ODD ONE OUT - the triptan disadvantage NOT printed on the page:","Causes permanent retinal damage","C/I in cardiovascular or cerebrovascular disease","Efficacy depends on Tmax","Ineffective in migraine with aura",exp="Disadvantages of triptan: C/I in cardiovascular or cerebrovascular disease; efficacy depends on Tmax; ineffective in migraine with aura. Note: ergotamine -> least recurrence of migraine."),
 q(596,"management","The prophylaxis first-line trio printed is:","Beta-blocker, valproate, topiramate","SNRI, TCA, clonidine","Pizotifen, flunarizine, candesartan","Amitriptyline, carbamazepine, lithium",exp="Prophylaxis: first line beta-blocker, valproate, topiramate; second line SNRI (venlafaxine), TCA; third line pizotifen (5-HTa antagonist), flunarizine (Ca2+ channel blocker), clonidine, candesartan."),
 q(596,"recall","The S/E notes: topiramate and valproate carry which adverse profiles?","Topiramate: weight loss, renal calculi; valproate: weight gain, liver disease, hyperammonemia, thrombocytopenia","Topiramate: weight gain, cataract; valproate: rash only","Topiramate: renal failure; valproate: aplastic anemia","Both: hepatotoxicity only",exp="Note S/E: topiramate - weight loss, renal calculi; valproate - weight gain, liver disease, hyperammonemia, thrombocytopenia."),
 q(596,"recall","The newer migraine drugs and therapies printed include which CGRP antagonist?","Erenumab","Lasmiditan","Sumatriptan","Pimavanserin",exp="Newer drugs and therapy: erenumab (CGRP antagonist), supraorbital transcutaneous stimulation, onabotulinum toxin A, greater occipital nerve block."),
]),
("TAC, Cluster & Variants", "TAC, Cluster & Variants",
 "The four TACs with their shared ANS requirement.\nCluster features and management, then paroxysmal hemicrania, SUNCT and hemicrania continua with their numeric attack data.", [
 q(597,"recall","The TAC group on this page includes which four conditions?","Cluster headaches, paroxysmal hemicrania, SUNCT, hemicrania continua","TTH, migraine, GCA, trigeminal neuralgia","Cluster, status migrainosus, HCT, SUNA","Paroxysmal hemicrania, TN, GPN, HCT",exp="Trigeminal Autonomic Cephalalgias includes: cluster headaches, paroxysmal hemicrania, SUNCT (short-lasting unilateral neuralgic headache with conjunctival congestion and tear), hemicrania continua."),
 q(597,"scenario","The TAC feature line: short-lasting, severe, unilateral, neuralgic headache plus which requirement?","At least one ipsilateral ANS symptom (conjunctival congestion/lacrimation, nasal congestion/rhinorrhoea, eyelid edema, forehead/facial sweating or flushing, ear fullness, miosis and/or ptosis)","Bilateral ANS symptoms","No ANS symptoms","Contralateral ANS symptoms",exp="Features: headache (short-lasting, severe, unilateral, neuralgic) + ipsilateral ANS symptoms; ANS symptoms at least 1: conjunctival congestion/lacrimation, nasal congestion/rhinorrhoea, eyelid edema, forehead and facial sweating, forehead and facial flushing, sensation of fullness in ear, miosis and/or ptosis."),
 q(597,"scenario","Young male, unilateral periorbital boring non-throbbing excruciating pain, nocturnal, 1-8 attacks/day for 8-10 weeks then a symptom-free period, alcohol trigger, no cutaneous trigger - which diagnosis?","Cluster headache","Paroxysmal hemicrania","SUNCT","Hemicrania continua",exp="Cluster headache: young males (M > F); unilateral periorbital non-throbbing, stabbing/boring, excruciating (most painful headache), associated with ipsilateral ANS, nocturnal; frequency 1-8 attacks/day, symptoms for 8-10 weeks followed by symptom-free period; migrainous features (photophobia may be seen); 20% chronic symptoms; trigger alcohol, no cutaneous trigger."),
 q(597,"numeric","Cluster headache attack duration per the page is:","15 min - 3 hours (30 mins)","5 - 300 seconds","2 - 30 min (average 5 mins)","4 - 72 hours",exp="Duration of attack: 15 min - 3 hours (30 mins)."),
 q(598,"management","The cluster-management flowchart's treatment of choice is:","100% oxygen 12-15 L/min for 10-20 minutes","Sumatriptan 6 mg S/C alone","Indomethacin","Verapamil as rescue therapy",exp="Management - treatment: 100% oxygen: treatment of choice, 12-15 L/min for 10-20 mins; sumatriptan 6 mg S/C."),
 q(598,"management","Short-term prevention of cluster per the list names which DOC?","Steroid","Verapamil (best long-term)","Lithium (long-term)","Topiramate (long-term)",exp="Prevention - short-term: steroid (DOC), verapamil, galcanezumab, greater occipital nerve injection; long-term: verapamil (best), topiramate, lithium."),
 q(598,"scenario","F = m, attacks 2-30 min (average 5 min), 1-30 attacks/day, ANS +, no migraine-like feature, no alcoholic trigger, no nocturnal preponderance, and indomethacin reduces attack frequency - which TAC?","Paroxysmal hemicrania","Cluster headache","SUNCT","Hemicrania continua",exp="Paroxysmal hemicrania: F = m; type throbbing/boring/stabbing; severity excruciating; 1-30 attacks/day; duration 2-30 mins (average 5 mins); ANS symptoms +; no migraine-like feature, no alcoholic trigger, no nocturnal preponderance; treatment: indomethacin (reduce frequency of attack); no effective treatment during attack."),
 q(598,"numeric","SUNCT attack duration and frequency per the page are:","5-240 seconds, 3-200 attacks/day","2-30 min, 1-30 attacks/day","15 min-3 hrs, 1-8 attacks/day","5-300 sec, 1-2 attacks/day",exp="SUNCT: M = F, unilateral, orbital or temporal pain, stabbing/throbbing, 3-200 attacks/day; duration of attack 5-240 sec; no migraine-like features; no alcohol preponderance; cutaneous trigger +, no refractory period."),
 q(598,"management","SUNCT management per the page is:","Treatment IV lignocaine; prevention lamotrigine or topiramate","Indomethacin; verapamil","Oxygen; steroid","L-dopa; carbidopa",exp="SUNCT management: treatment IV lignocaine; prevention lamotrigine or topiramate."),
 q(598,"scenario","Elderly female with a continuous unilateral background headache, episodic TAC, migrainous features, ANS + and response to indomethacin - which diagnosis?","Hemicrania continua","Cluster headache","SUNCT","Paroxysmal hemicrania",exp="Hemicrania continua: elderly females; continuous nature of unilateral background headache with episodic TAC; migrainous features +; ANS symptoms +; responsive to indomethacin."),
 q(599,"recall","The investigation-of-TAC list on this page contains which three items?","MRI brain, polysomnography, pituitary function test","CT head, ESR, scalp biopsy","DaT-SPECT, CSF analysis, PET","EEG, LP, fundoscopy",exp="Investigation of TAC: MRI brain; polysomnography; pituitary function test."),
]),
("Trigeminal & Glossopharyngeal Neuralgia", "Trigeminal & Glossopharyngeal Neuralgia",
 "TN clinical features with its vascular and demyelinating causes.\nTreatment with the HLA pre-tests, then glossopharyngeal neuralgia (eagle syndrome).", [
 q(599,"scenario","F > m, 50-60 yrs, brief electric shock-like unilateral V2/V3 pain with cutaneous trigger and refractory period, no objective sensory loss - which diagnosis and its unilateral cause?","Trigeminal neuralgia (tic douloureux) - compression on the superior cerebellar artery","Glossopharyngeal neuralgia - elongated styloid process","Cluster headache - cavernous ICA disease","TTH - myofascial trigger points",exp="Trigeminal neuralgia (00:55:15): F > m, 50-60 yrs; paroxysms of intense pain; unilateral d/t compression on superior cerebellar artery; bilateral d/t demyelination (multiple sclerosis); type brief, electric, shock-like superficial pain; tic douloureux - wincing d/t pain; maxillary (V2) and mandibular (V3) divisions; no objective sensory loss; cutaneous trigger +, refractory period +; investigation: specialized MRI."),
 q(599,"management","Trigeminal neuralgia treatment per the page, with its required pre-test, is:","Carbamazepine (>> lamotrigine) after HLA B-1502 testing; subcutaneous botulinum toxin; microvascular decompression in medically refractory cases","Lamotrigine first; no pre-test needed","Indomethacin with HLA B-5801 testing","Verapamil with no surgical option",exp="Treatment: carbamazepine >> lamotrigine - HLA B-1502 tested before administration of carbamazepine; subcutaneous botulinum toxin; microvascular decompression in medical refractory cases. Note: HLA B-5801 tested before administration of allopurinol."),
 q(599,"recall","Bilateral trigeminal neuralgia is attributed to what per the page?","Demyelination (multiple sclerosis)","Superior cerebellar artery compression","Notched styloid process","Pituitary tumour",exp="Unilateral: d/t compression on superior cerebellar artery; bilateral: d/t demyelination (multiple sclerosis)."),
 q(599,"scenario","Sudden severe short-lasting recurrent pain in the tonsil bed, throat and angle of jaw, aggravated by coughing, yawning, swallowing, associated with cardiac conduction abnormalities - which syndrome?","Glossopharyngeal neuralgia (aka eagle syndrome)","Trigeminal neuralgia V1","SUNCT","Hemicrania continua",exp="Glossopharyngeal neuralgia: aka eagle syndrome; d/t elongation of styloid process; type sudden, severe, short-lasting, recurrent bouts of pain; site tonsil bed, throat and angle of jaw; aggravation factors coughing, yawning, swallowing; associated with cardiac conduction abnormalities."),
]),
("Benign Intracranial Hypertension", "Benign Intracranial Hypertension",
 "The papilledema protocol with its LP threshold and modified Dandy criteria.\nSecondary causes, clinical features and the treatment ladder with the acute-ICP note close the chapter.", [
 q(600,"scenario","Papilledema with no neurologic signs except 6th nerve paresis is interpreted on the page as:","A false localizing sign","A localizing brainstem sign","A sign of cerebellar lesion","Normal in raised ICP",exp="Evaluation protocol: papilledema + no neurologic signs except 6th nerve paresis: false localizing sign -> CT/MRI normal -> LP -> up opening pressure (>25 cm H2O) -> MRI: BIH or IIH. Papilledema seen in: hypertension, bradycardia, bradypnoea."),
 q(600,"numeric","The LP opening-pressure threshold in the BIH evaluation protocol is:","Greater than 25 cm H2O","Greater than 15 cm H2O","Greater than 35 cm H2O","Greater than 50 cm H2O",exp="LP: up opening pressure (>25 cm H2O) -> MRI: benign intracranial hypertension (BIH) or idiopathic intracranial hypertension (IIH)."),
 q(600,"recall","The modified Dandy criteria require:","Symptoms of up ICP; no localising signs except 6th nerve palsy; normal CT/MRI; LP >25 cm H2O with normal CSF biochemistry/cytology and no other explanation","Seizures, focal signs, abnormal CSF, pressure >40 cm","Headache only, normal LP, abnormal MRI","Papilledema, abnormal EEG, CSF pleocytosis",exp="Modified Dandy criteria: symptoms of up ICP; no localising signs except 6th nerve palsy; normal CT, MRI findings; LP opening pressure >25 cm of H2O, CSF biochemistry/cytology normal; no other explanation for raised ICP."),
 q(600,"oddoneout","Pick the ODD ONE OUT - the drug NOT listed as a secondary cause of IIH:","Methotrexate","Outdated tetracycline","Nalidixic acid","Danazol",exp="Secondary causes - drugs: outdated tetracycline, nalidixic acid, NSAIDs, retinol, danazol, tamoxifen; endocrine: steroid withdrawal, growth hormone, anabolic steroid. Primary empty sella syndrome: benign intracranial hypertension, thin rim of pituitary intact."),
 q(600,"recall","The endocrine secondary causes of IIH printed are:","Steroid withdrawal, growth hormone, anabolic steroid","Addison's disease, hypothyroidism, Cushing's","Steroid use, insulin, testosterone only","Pituitary adenoma, acromegaly, diabetes",exp="Endocrine: steroid withdrawal, growth hormone, anabolic steroid."),
 q(601,"scenario","Headache m/c, orthostatic, daily, bilateral, worse in morning, aggravated by coughing/straining with retrobulbar pain; transient visual obscurations (seconds to minutes) and pulsatile tinnitus (unilateral > bilateral) - which disorder's clinical features?","Benign intracranial hypertension","Tension-type headache","Migraine without aura","Giant cell arteritis",exp="Clinical features - headache m/c: type orthostatic, frequency daily, bilateral, worse in morning; aggravating factors coughing, straining; associated with retrobulbar pain. Visual symptoms: transient visual obscuration (2nd m/c), blackouts/grayouts, duration seconds to minutes, unilateral/bilateral. Tinnitus: 3rd m/c, pulsatile, heard in silent surroundings, unilateral > bilateral."),
 q(601,"management","The BIH treatment list marks which drug as DOC and which procedure as the best option?","Acetazolamide (DOC); repeated lumbar puncture (up to 20-30 ml) the best option","Topiramate (DOC); shunting the best option","Mannitol (DOC); optic nerve sheath fenestration the best","Acetazolamide (DOC); shunting the best option",exp="Treatment: weight loss; acetazolamide (DOC); topiramate; repeated lumbar puncture (upto 20-30 ml): best option; surgery - optic nerve sheath fenestrations, shunting."),
 q(601,"recall","The acute raised-ICP note lists which five steps?","Elevate head, mannitol, sedation, hyperventilation, pressor therapy to maintain CPP >60 mmHg","Head-down, dexamethasone, intubation, hyperventilation, CPP >70 mmHg","Mannitol, shunt, acetazolamide, sedation, pressors","Elevate head, LP, acetazolamide, topiramate, pressors",exp="Mx of acute up ICP: 1. elevate head; 2. mannitol; 3. sedation; 4. hyperventilation; 5. pressor therapy to maintain CPP >60 mmHg."),
]),
])

for ch in (ch33, ch34, ch35, ch36, ch37, ch38):
    write(ch)
print("Chapters 33-38 authored.")
